import { DebugMenuWidget, DebugMenuState, DebugOverlay } from "components/debug.slint";
import { SettingsMenu, UserSettings } from "components/settings.slint";
import { ControlledFocusScope, ControlledFocusDomain, FocusHoverRect, FocusDomainRect, AnimatedFocusHoverRect, } from "components/focus_elements.slint";
import { SFDataParameter, SIDataParameter, SBDataParameter, SStrDataParameter } from "data/data_parameter.slint";
import { SCarData } from "data/car_data.slint";
import { SUnitSystem } from "data/units.slint";
import { ApplicationState, AccessibilitySettings } from "application/application_state.slint";
import { GlobalThemeData } from "themes/themes.slint";
import { ThemeLoader } from "themes/theme_loader_gen.slint";
import { CanDisplay, SCanFrameDisplay } from "components/can_display.slint";
import { WidgetContainerState } from "components/widget_container.slint";

// themes
import { DefaultTheme } from "themes/default/theme_main.slint";

// default fonts
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Black.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Bold.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-ExtraLight.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Light.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Medium.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Regular.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-SemiBold.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Thin.ttf";

import "../../resources/fonts/JetBrainsMono/fonts/ttf/JetBrainsMono-Regular.ttf";

// Export types
export { SFDataParameter, SIDataParameter, SBDataParameter, SStrDataParameter, SUnitSystem, SCanFrameDisplay }
// Export globals
export { ApplicationState, AccessibilitySettings, SCarData, DebugMenuState, GlobalThemeData, CanDisplay, WidgetContainerState }

export component App inherits Window {
    default-font-family: "Montserrat";
    default-font-weight: 400;

    title: "WRX Digital Instrument Cluster";

    preferred-width: 2400px;
    preferred-height: 900px;

    background: black;

    // TODO: revert settings menu to appear as a "floating window"
    if ApplicationState.settings-menu-visible: settings-menu := SettingsMenu { }
    if !ApplicationState.settings-menu-visible: theme-loader := ThemeLoader { }

    if AccessibilitySettings.animations-enabled: AnimatedFocusHoverRect { }
    if !AccessibilitySettings.animations-enabled: FocusHoverRect { }

    if ApplicationState.debug-mode: DebugOverlay { }
}
