import { DebugMenuWidget, DebugMenuState } from "components/debug.slint";
import { SettingsMenu, UserSettings } from "components/settings.slint";
import { SFDataParameter, SIDataParameter, SBDataParameter, SStrDataParameter } from "data/data_parameter.slint";
import { SCarData } from "data/car_data.slint";
import { SUnitSystem } from "data/units.slint";
import { ApplicationState } from "application/application_state.slint";
import { GlobalThemeData } from "themes/themes.slint";
import { ThemeLoader } from "themes/theme_loader_gen.slint";
import { MapTile, NavMapProperties } from "components/navmap.slint";
import { CanDisplay, SCanFrameDisplay } from "components/can_display.slint";

// themes
import { DefaultTheme } from "themes/default/theme_main.slint";

// default fonts
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Black.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Bold.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-ExtraLight.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Light.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Medium.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Regular.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-SemiBold.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Thin.ttf";
import { Button } from "std-widgets.slint";

// Export types
export { SFDataParameter, SIDataParameter, SBDataParameter, SStrDataParameter, SUnitSystem, MapTile, SCanFrameDisplay }
// Export globals
export { ApplicationState, SCarData, DebugMenuState, GlobalThemeData, NavMapProperties, CanDisplay }

export component App inherits Window {
    // todo: move three-d stuff to global-singleton thing like navmap and settings
    // in property <image> threed-widget-texture <=> threed-container-image.source;
    // out property <length> threed-widget-width: threed-container-image.width;
    // out property <length> threed-widget-height: threed-container-image.height;
    // out property <length> threed-widget-x: threed-container-image.absolute-position.x;
    // out property <length> threed-widget-y: threed-container-image.absolute-position.y;
    // out property <bool> threed-widget-visible: center-widget-container.current-page == 2;

    default-font-family: "Montserrat";
    default-font-weight: 400;

    title: "WRX Digital Instrument Cluster";

    preferred-width: 1920px;
    preferred-height: 720px;

    background: black;

    ThemeLoader { }

    settings-menu := SettingsMenu {
        open-height: 720px;
        open-width: 1920px;

        parent-height: 720px;
        parent-width: 1920px;
    }
}
