export component GaugeCircleBackground inherits Path {
    width: 100px;
    height: 100px;

    stroke: black;
    stroke-width: 1px;

    in property <float> thickness;
    in property <float> inner-radius;

    MoveTo {
        x: 50;
        y: 0;
    }

    ArcTo {
        radius-x: 50;
        radius-y: 50;
        x: 50;
        y: 100;
        sweep: true;
    }

    ArcTo {
        radius-x: 50;
        radius-y: 50;
        x: 50;
        y: 0;
        sweep: true;
    }

    LineTo {
        x: 50;
        y: root.thickness;
    }

    ArcTo {
        radius-x: root.inner-radius;
        radius-y: root.inner-radius;
        x: 50;
        y: 100 - root.thickness;
    }

    ArcTo {
        radius-x: root.inner-radius;
        radius-y: root.inner-radius;
        x: 50;
        y: root.thickness;
    }
}

export component GaugeCircleFill inherits Path {
    width: 100px;
    height: 100px;

    stroke: black;
    stroke-width: 1px;

    in property <float> thickness;
    in property <float> inner-radius;
    in property <float> progress;
    in property <float> start: 0;

    MoveTo {
        y: 50 - 50 * cos(-root.start * 360deg);
        x: 50 - 50 * sin(-root.start * 360deg);
    }

    LineTo {
        y: 50 - root.inner-radius * cos(-root.start * 360deg);
        x: 50 - root.inner-radius * sin(-root.start * 360deg);
    }

    ArcTo {
        radius-x: root.inner-radius;
        radius-y: root.inner-radius;
        y: 50 - root.inner-radius * cos(-(root.start + root.progress) * 360deg);
        x: 50 - root.inner-radius * sin(-(root.start + root.progress) * 360deg);
        sweep: root.progress > 0;
        large-arc: root.progress > 0.5;
    }

    LineTo {
        y: 50 - 50 * cos(-(root.start + root.progress) * 360deg);
        x: 50 - 50 * sin(-(root.start + root.progress) * 360deg);
    }

    ArcTo {
        radius-x: 50;
        radius-y: 50;
        y: 50 - 50 * cos(-root.start * 360deg);
        x: 50 - 50 * sin(-root.start * 360deg);
        sweep: root.progress < 0;
        large-arc: root.progress > 0.5;
    }

    LineTo {
        y: 50 - 50 * cos(-root.start * 360deg);
        x: 50 - 50 * sin(-root.start * 360deg);
    }
}

export component GaugeCircle {
    in property <brush> brush <=> fill.fill;
    in property <float> progress;
    in property <float> thickness: 15;
    in property <float> inner-radius: 50 - root.thickness;

    background := GaugeCircleBackground {
        width: 100%;
        height: 100%;
        thickness: root.thickness;
        inner-radius: root.thickness;
    }

    fill := GaugeCircleFill {
        width: 100%;
        height: 100%;
        thickness: root.thickness;
        inner-radius: root.inner-radius;
        progress: root.progress;
    }
}
