component GaugeCircleBackground inherits Path {
    MoveTo {
        x: 0;
        y: 50;
    }

    ArcTo {
        x: 100;
        y: 50;
        radius-x: 50;
        radius-y: 50;
        sweep: true;
    }

    ArcTo {
        x: 50;
        y: 100;
        radius-x: 50;
        radius-y: 50;
        sweep: true;
    }
}

export component GaugeCircle inherits Rectangle {
    in property <float> progress;

    clip: true;
    background: transparent;

    Edge := GaugeCircleBackground {
        width: 100%;
        height: 100%;
        stroke: red;
        stroke-width: 2px;
    }
}
