import { ApplicationState, AccessibilitySettings, DebugSettings } from "../data/application_state.slint";

export global GlobalSizing {
    out property <length> button-height: 40px;
}

struct FocusBox {
    x: length,
    y: length,
    width: length,
    height: length,
    border-radius: length,
}

enum ForceFailedReason {
    FocusDisabled,
    Stolen
}


export global FocusState {
    out property <int> num-focuses: 1;
    out property <int> current-focus-id: 0;
    out property <int> force-focus-id;
    out property <bool> attempting-force-focus;
    out property <int> last-focus-id;
    out property <FocusBox> focus-box: { x: 4px, y: 4px, width: 100px, height: 75px, border-radius: 75px / 3 };
    out property <int> failed-forces: 0;

    private property <bool> i-force-complete;

    public function create-focus-id() -> int {
        self.num-focuses += 1;
        self.num-focuses - 1
    }

    public function force-focus(id: int) {
        self.force-focus-id = id;
        self.attempting-force-focus = true;
    }

    pure public function has-focus(id: int) -> bool {
        self.current-focus-id == id
    }

    public function set-focus-id(id: int) {
        self.current-focus-id = id;
    }

    public function force-complete(id: int) {
        if id == self.force-focus-id {
            self.attempting-force-focus = false;
        }
    }

    public function force-failed(id: int, reason: ForceFailedReason) {
        self.attempting-force-focus = false;
    }

    public function set-focus-box(focus-box: FocusBox) {
        self.focus-box = focus-box;
    }

    public function set-last-focus-id(id: int) {
        self.last-focus-id = id;
    }
}

// TODO: add sub-domain with focus wrapper for components like sliders or settings boxes that contain their own focusscope, but exist in a larger scope
// allows the main focusscope to be interacted with while indicating which sub-domain is active

export global DomainState {
    out property <int> num-domains: 1;
    out property <int> current-domain-id: 0;
    out property <int> last-domain-id: 0;
    out property <int> navigation-errors: 0;

    in-out property <FocusBox> focus-box: { x: 0, y: 0, width: 0, height: 0 };

    public function create-domain-id() -> int {
        num-domains += 1;
        num-domains - 1
    }

    public function enter-domain(domain-id: int) {
        self.last-domain-id = self.current-domain-id;
        self.current-domain-id = domain-id;
    }

    public function domain-exit(domain-id: int) -> bool {
        if domain-id == self.current-domain-id {
            enter-domain(self.last-domain-id);
            true
        }
        false
    }

    public function set-focus-coords(x: length, y: length, width: length, height: length) {
        if self.focus-box.x != x {
            self.focus-box.x = x;
        }
        if self.focus-box.y != y {
            self.focus-box.y = y;
        }
        if self.focus-box.width != width {
            self.focus-box.width = width;
        }
        if self.focus-box.height != height {
            self.focus-box.height = height;
        }
    }

    public function set-last-domain-id(id: int) {
        self.last-domain-id = id;
    }

    public function navigation-error-occured(id: int) {
        self.navigation-errors += 1;
    }
}

export component DebugHighlight {
    in property <brush> background <=> i-rect.border-color;

    width: 100%;
    height: 100%;

    i-rect := Rectangle {
        background: transparent;
        visible: ApplicationState.debug-mode && DebugSettings.debug-highlights;

        border-width: 2px;
        border-color: purple;
    }
}

export component Arc inherits Path {
    in property <angle> start: 90deg;
    in property <angle> end: 180deg;
    in property <length> inner-radius: self.width / 3;
    in property <length> outer-radius: self.width / 2;

    property <angle> angle-range: end - start;

    fill: white;
    viewbox-width: self.width / 1px;
    viewbox-height: self.height / 1px;

    MoveTo {
        x: (parent.viewbox-width / 2) + cos(start) * (outer-radius / 1px);
        y: (parent.viewbox-height / 2) - sin(start) * (outer-radius / 1px);
    }

    LineTo {
        x: (parent.viewbox-width / 2) + cos(start) * (inner-radius / 1px);
        y: (parent.viewbox-height / 2) - sin(start) * (inner-radius / 1px);
    }

    ArcTo {
        x: (parent.viewbox-width / 2) + cos(end) * (inner-radius / 1px);
        y: (parent.viewbox-height / 2) - sin(end) * (inner-radius / 1px);
        radius-x: inner-radius / 1px;
        radius-y: inner-radius / 1px;
        sweep: angle-range < 0deg;
        large-arc: abs(angle-range) > 180deg;
    }

    LineTo {
        x: (parent.viewbox-width / 2) + cos(end) * (outer-radius / 1px);
        y: (parent.viewbox-height / 2) - sin(end) * (outer-radius / 1px);
    }

    ArcTo {
        x: (parent.viewbox-width / 2) + cos(start) * (outer-radius / 1px);
        y: (parent.viewbox-height / 2) - sin(start) * (outer-radius / 1px);
        radius-x: outer-radius / 1px;
        radius-y: outer-radius / 1px;
        sweep: angle-range > 0deg;
        large-arc: abs(angle-range) > 180deg;
    }

    LineTo {
        x: (parent.viewbox-width / 2) + cos(start) * (outer-radius / 1px);
        y: (parent.viewbox-height / 2) - sin(start) * (outer-radius / 1px);
    }
}

export component FocusHoverRect inherits Rectangle {
    private property <brush> hover-color: white;
    private property <float> hover-fade: 100%;
    private property <length> size-offset: 3px;
    private property <length> new-height: FocusState.focus-box.height + size-offset * 2;
    private property <length> corner-size: self.border-radius;

    property <float> radial-percentage: (size-offset / corner-size);

    x: FocusState.focus-box.x - size-offset;
    y: FocusState.focus-box.y - size-offset;
    width: FocusState.focus-box.width + size-offset * 2;
    height: new-height;
    border-radius: FocusState.focus-box.border-radius * (new-height / FocusState.focus-box.height);
    background: transparent;

    top-rect := Rectangle {
        y: 0;
        x: root.width / 2 - self.width / 2;
        height: root.size-offset;
        width: root.width - root.corner-size * 2;

        background: white;
        // background: @linear-gradient(0deg, root.hover-color, root.hover-color.transparentize(hover-fade));
    }

    bottom-rect := Rectangle {
        y: root.height - root.size-offset;
        x: top-rect.x;
        height: root.size-offset;
        width: top-rect.width;

        background: white;
        // background: @linear-gradient(180deg, root.hover-color, root.hover-color.transparentize(hover-fade));
    }

    left-rect := Rectangle {
        x: 0;
        y: root.height / 2 - self.height / 2;
        width: root.size-offset;
        height: root.height - root.corner-size * 2;

        background: white;
        // background: @linear-gradient(270deg, root.hover-color, root.hover-color.transparentize(hover-fade));
    }

    right-rect := Rectangle {
        x: root.width - self.width;
        y: left-rect.y;
        width: left-rect.width;
        height: left-rect.height;

        background: white;
        // background: @linear-gradient(90deg, root.hover-color, root.hover-color.transparentize(hover-fade));
    }

    // TODO: figure out the gradient rate mismatch
    top-left-corner-rect := Arc {
        start: 90deg;
        // fill: @radial-gradient(circle, root.hover-color radial-percentage, root.hover-color.transparentize(hover-fade) 100%);
        end: 180deg;
        x: 0;
        y: 0;
        width: root.corner-size * 2;
        height: root.corner-size * 2;
        inner-radius: root.corner-size - root.size-offset;
        anti-alias: true;
    }

    // Rectangle {
    //     background: red;
    //     x: 0;
    //     y: root.corner-size * radial-percentage;
    //     width: root.corner-size * 2;
    //     height: 1px;
    // }

    bottom-left-corner-rect := Arc {
        start: 180deg;
        end: 270deg;
        x: 0;
        y: root.height - self.height;
        width: top-left-corner-rect.width;
        height: top-left-corner-rect.height;
        inner-radius: root.corner-size - root.size-offset;
        anti-alias: true;
    }

    top-right-corner-rect := Arc {
        start: 0deg;
        end: 90deg;
        x: root.width - self.width;
        y: 0;
        width: root.corner-size * 2;
        height: root.corner-size * 2;
        inner-radius: root.corner-size - root.size-offset;
        anti-alias: true;
    }

    bottom-right-corner-rect := Arc {
        start: 270deg;
        end: 360deg;
        x: root.width - self.width;
        y: root.height - self.height;
        width: root.corner-size * 2;
        height: root.corner-size * 2;
        inner-radius: root.corner-size - root.size-offset;
        anti-alias: true;
    }
}

// TODO: finish slider
// should behave similar to combobox and take focus with global singleton

export component Slider {
    in property <float> max-value: 100;
    in property <float> min-value: 0;
    in property <int> delim: 10;

    property <int> sections: (max-value - min-value) / delim;

    Rectangle {
        height: 2px;
        background: white.transparentize(25%);
    }

    // HorizontalLayout {

    //     for i in sections: Rectangle {
    //         height: 6px;
    //         width: 2px;
    //     }
    // }
}

export component AnimatedFocusHoverRect inherits FocusHoverRect {
    animate x, y, width, height, border-radius { duration: 60ms; }
}

export component ControlledFocusScope inherits Rectangle {
    in property <bool> init-focus: true;
    in property <bool> enabled <=> i-focus.enabled;

    out property <bool> has-focus <=> i-focus.has-focus;
    out property <bool> has-hover <=> i-touch.has-hover;
    out property <int> focus-id;

    private property <bool> state-attempting-force-focus: FocusState.attempting-force-focus;
    private property <bool> i-forcing-focus: FocusState.attempting-force-focus && (FocusState.force-focus-id == root.focus-id);

    callback key-pressed(KeyEvent) -> EventResult;
    callback key-released(KeyEvent) -> EventResult;
    callback focus-gained(FocusReason);
    callback focus-lost(FocusReason);
    callback activated();
    callback init-ready();

    forward-focus: i-focus;

    function update-coords() {
        // TODO: tie to changes in geometry; https://github.com/slint-ui/slint/issues/7849
        FocusState.set-focus-box({
            x: root.absolute-position.x,
            y: root.absolute-position.y,
            width: root.width,
            height: root.height,
            border-radius: root.border-radius
        })
    }

    changed i-forcing-focus => {
        if i-forcing-focus {
            if root.enabled {
                root.focus();
            } else {
                FocusState.force-failed(root.focus-id, ForceFailedReason.FocusDisabled);
            }
        }
    }

    i-touch := TouchArea {
        enabled: root.enabled;

        clicked => root.focus();
        double-clicked => root.activated();
    }

    i-focus := FocusScope {
        width: 0;

        init => {
            root.focus-id = FocusState.create-focus-id();
            if init-focus || i-forcing-focus {
                self.focus();
            }
            root.init-ready();
        }
        key-pressed(event) => {
            if (event.text == Key.Return) || (event.text == Key.Space) {
                root.activated();
                accept
            } else {
                root.key-pressed(event)
            }
        }
        key-released(event) => root.key-released(event);
        focus-lost(reason) => {
            // TODO: potentially check that the domain did not change unexpectedly and take back focus if it did
            FocusState.set-last-focus-id(root.focus-id);
            root.focus-lost(reason);
        }
        focus-gained(reason) => {
            if !FocusState.has-focus(root.focus-id) {
                update-coords();
                FocusState.set-focus-id(root.focus-id);
                root.focus-gained(reason);
            }
            if root.state-attempting-force-focus {
                if (reason == FocusReason.programmatic) && root.i-forcing-focus {
                    FocusState.force-complete(root.focus-id);
                } else {
                    FocusState.force-failed(root.focus-id, ForceFailedReason.Stolen);
                }
            }
        }
    }
}

export component Button inherits Rectangle {
    in property <string> text <=> i-text.text;
    in property <TextHorizontalAlignment> text-alignment <=> i-text.horizontal-alignment;

    out property <bool> has-focus: FocusState.has-focus(i-focus.focus-id);
    out property <int> focus-id <=> i-focus.focus-id;

    private property <length> i-padding: 10px;

    callback focus-gained(FocusReason);
    callback focus-lost(FocusReason);
    callback init-ready();
    callback activated();

    border-radius: 2px;
    background: gray.darker(95%);
    forward-focus: i-focus;
    height: GlobalSizing.button-height;
    width: self.height * 2.5;

    HorizontalLayout {
        padding: i-padding;

        i-text := Text {
            color: white;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }

    i-focus := ControlledFocusScope {
        border-radius: root.border-radius;
        init-focus: false;

        focus-gained(FocusReason) => root.focus-gained(FocusReason);
        focus-lost(FocusReason) => root.focus-lost(FocusReason);
        activated => root.activated();
        init-ready => root.init-ready();
    }

    DebugHighlight {
        background: orange;
    }
}

export component FocusDomain inherits Rectangle {
    in property <bool> force-focus: true;
    in property <bool> force-exit-strategy: true;
    in property <length> exit-button-width <=> exit.width;

    out property <int> domain-id;
    out property <bool> domain-active: DomainState.current-domain-id == self.domain-id;

    in-out property <bool> no-graceful-return: false;

    private property <int> last-domain-id: DomainState.last-domain-id;
    private property <int> current-focus-id: FocusState.current-focus-id;
    private property <int> last-focus-id;
    private property <int> domain-last-focus-id;
    private property <bool> was-last: false;
    private property <bool> safe-return: false;

    callback nav-front-forward();
    callback nav-end-backward();
    callback exited();
    callback domain-returned();

    function i-domain-returned() {
        FocusState.force-focus(domain-last-focus-id);
        root.safe-return = true;
        root.domain-returned();
    }

    public function enter-domain() {
        DomainState.enter-domain(self.domain-id);
    }

    public function exit-domain() {
        DomainState.domain-exit(self.domain-id);
    }

    forward-focus: pre-nav-focus;
    width: 100%;
    height: 100%;

    changed domain-active => {
        if domain-active {
            DomainState.set-focus-coords(root.absolute-position.x, root.absolute-position.y, root.width, root.height);
            if was-last {
                was-last = false;
                i-domain-returned();
            }
            if !safe-return || no-graceful-return {
                pre-nav-focus.focus();
            }
            safe-return = false;
            no-graceful-return = false;
        } else {
            self.exited();
        }
    }

    changed last-domain-id => {
        if last-domain-id == domain-id {
            was-last = true;
        }
    }

    changed current-focus-id => {
        if domain-active {
            root.last-focus-id = current-focus-id;
        }
        if was-last {
            root.domain-last-focus-id = root.last-focus-id;
        }
    }

    init => {
        self.domain-id = DomainState.create-domain-id();

        if force-focus {
            enter-domain();
        }
    }

    pre-nav-lock := FocusScope {
        width: 0;

        focus-gained(reason) => {
            DomainState.navigation-error-occured(root.domain-id);
            pre-nav-focus.focus();
        }
    }

    pre-nav-focus := FocusScope {
        enabled: root.domain-active;
        width: 0;

        focus-gained(reason) => {
            if reason == FocusReason.tab-navigation {
                post-nav-focus.focus();
            } else {
                nav-front-forward();
            }
        }
    }

    DebugHighlight {
        background: red;
        visible: domain-active;
    }

    container := Rectangle {
        y: 0;
        clip: true;
        height: (root.domain-active && force-exit-strategy) ? root.height - exit.height : root.height;

        @children
    }

    HorizontalLayout {
        alignment: center;
        y: root.height - exit.height;

        exit := Button {
            visible: root.domain-active && root.force-exit-strategy;
            text: "Back";

            activated => exit-domain();
        }
    }

    post-nav-focus := FocusScope {
        enabled: root.domain-active;
        width: 0;

        focus-gained(reason) => {
            if reason == FocusReason.tab-navigation {
                pre-nav-focus.focus();
            } else if force-exit-strategy {
                exit.focus();
            } else {
                nav-end-backward();
            }
        }
    }

    post-nav-lock := FocusScope {
        width: 0;

        focus-gained(reason) => {
            DomainState.navigation-error-occured(root.domain-id);
            post-nav-focus.focus();
        }
    }
}

export global ComboBoxState {
    in-out property <int> first-model-focus-id;
    in-out property <int> last-model-focus-id;

    in property <string> current-value;
    in property <string> title;

    out property <[string]> model;
    public function set-model(model: [string]) {
        self.model = model;
    }

    out property <bool> visible: false;
    public function show-selection-box() {
        self.visible = true;
    }

    out property <FocusBox> focus-box;
    public function set-focus-coords(x: length, y: length, width: length, height: length) {
        if self.focus-box.x != x {
            self.focus-box.x = x;
        }
        if self.focus-box.y != y {
            self.focus-box.y = y;
        }
        if self.focus-box.width != width {
            self.focus-box.width = width;
        }
        if self.focus-box.height != height {
            self.focus-box.height = height;
        }
    }

    out property <bool> selection-made;
    out property <string> selection-value;
    out property <int> selection-index;

    in property <int> domain-id;

    public function make-selection(value: string, index: int) {
        self.selection-made = true;
        self.selection-value = value;
        self.selection-index = index;
    }

    public function complete-selection() {
        DomainState.domain-exit(self.domain-id);
        self.selection-made = false;
        self.visible = false;
    }
}

component ComboBoxSelectionBoxButton inherits Button {
    in property <bool> has-selection;
    width: self.height * 4;

    HorizontalLayout {
        padding: 6px;
        alignment: start;

        VerticalLayout {
            alignment: center;

            Rectangle {
                width: 6px;
                height: 90%;
                background: white;
                visible: has-selection;
                border-radius: 2px;
            }
        }
    }
}

// TODO: add animated version that fades in; https://github.com/slint-ui/slint/issues/348
// TODO: add background blur (may require image generation in Rust, possibly using Slint's window capture)
export component ComboBoxSelectionBox inherits FocusDomain {
    in-out property <string> current-value: ComboBoxState.current-value;

    private property <bool> i-has-domain: ComboBoxState.visible;
    private property <int> i-init-selection-box-focus;

    width: 100%;
    height: 100%;
    force-exit-strategy: false;
    background: black.transparentize(7.5%);

    function open() {
        if i-has-domain {
            root.focus();
        }
    }

    changed i-has-domain => open();

    nav-front-forward => FocusState.force-focus(ComboBoxState.first-model-focus-id);
    nav-end-backward => FocusState.force-focus(ComboBoxState.last-model-focus-id);
    init => open();

    forward-focus: init-focus-hack;

    HorizontalLayout {
        padding: 5px;
        alignment: center;

        i-layout := VerticalLayout {
            spacing: 5px;
            alignment: center;

            Text {
                height: self.font-size + 20px;
                color: white;
                text: ComboBoxState.title;
                font-size: 25px;
                horizontal-alignment: left;
                vertical-alignment: center;
            }

            for model[i] in ComboBoxState.model: HorizontalLayout {
                alignment: center;

                ComboBoxSelectionBoxButton {
                    text: model;
                    has-selection: root.current-value == model;

                    init-ready => {
                        if i == 0 {
                            ComboBoxState.first-model-focus-id = self.focus-id;
                        }
                        if i == (ComboBoxState.model.length - 1) {
                            ComboBoxState.last-model-focus-id = self.focus-id;
                        }
                        if self.has-selection {
                            root.i-init-selection-box-focus = self.focus-id;
                        }
                    }

                    activated => {
                        ComboBoxState.domain-id = root.domain-id;
                        ComboBoxState.make-selection(model, i);
                    }
                }
            }

            init-focus-hack := FocusScope {
                //! appears to be the only reliable way to focus conditional elements on init
                width: 0;
                focus-gained(reason) => {
                    self.enabled = false;
                    FocusState.force-focus(root.i-init-selection-box-focus);
                }
            }
        }
    }
}

export component ComboBox inherits Button {
    in property <[string]> model;
    in property <string> title;

    in-out property <int> current-index: 0;
    in-out property <string> current-value: model[current-index];
    out property <bool> open;

    private property <bool> selection-state-made: ComboBoxState.selection-made;
    private property <int> domain-state-real-last;

    text: current-value;
    text-alignment: left;

    i-arrow := Rectangle {
        y: root.height / 2 - self.height / 2;
        x: root.width - self.width - (root.height - self.height) / 2;
        width: 12px;
        height: self.width;

        Path {
            fill: grey;
            viewbox-height: parent.height / 1px;
            viewbox-width: parent.width / 1px;

            MoveTo {
                x: 0;
                y: 0;
            }

            LineTo {
                x: parent.viewbox-width / 2;
                y: parent.viewbox-height;
            }

            LineTo {
                x: parent.viewbox-width;
                y: 0;
            }
        }
    }

    changed selection-state-made => {
        if open {
            root.current-index = ComboBoxState.selection-index;
            root.current-value = ComboBoxState.selection-value;
            ComboBoxState.complete-selection();
            DomainState.set-last-domain-id(root.domain-state-real-last);
            root.open = false;
        }
    }

    function activate-open() {
        root.domain-state-real-last = DomainState.last-domain-id;
        ComboBoxState.title = root.title;
        ComboBoxState.current-value = root.current-value;
        ComboBoxState.set-focus-coords(self.absolute-position.x, self.absolute-position.y, self.width, self.height);
        ComboBoxState.set-model(self.model);
        ComboBoxState.show-selection-box();
        root.open = true;
    }

    activated => activate-open();
}

component ToggleBoxInner inherits Rectangle {
    in property <brush> i-background: self.background;
    in property <length> i-x <=> i-switch.x;
    in property <bool> var;
    in property <bool> accessible-mode: true;

    private property <length> switch-padding: 4px;

    background: (accessible-mode || !var) ? grey.darker(80%) : green;
    border-radius: self.height / 2;
    clip: true;

    i-switch := Rectangle {
        border-radius: self.height / 1.5;
        background: lightgray;
        width: root.width * 65% - root.switch-padding - root.border-width;
        x: var ? root.width - root.border-width - root.switch-padding - self.width : root.border-width + root.switch-padding;
        y: root.height / 2 - self.height / 2;
        height: root.height - root.switch-padding * 2 - root.border-width * 2;

        if accessible-mode: Rectangle {
            off-indicator := Rectangle {
                x: parent.width - self.width - on-indicator.x;
                width: on-indicator.width;
                height: self.width;
                border-radius: self.height / 2;
                background: red;
            }

            on-indicator := Rectangle {
                visible: true;
                x: -(root.width - parent.width) / 2 - root.switch-padding / 2;
                width: 10px;
                height: self.width;
                border-radius: self.height / 2;
                background: limegreen;
            }
        }
    }
}

component AnimatedToggleBoxInner inherits ToggleBoxInner {
    animate i-x, i-background { duration: 60ms; }
}

export component ToggleBox inherits Button {
    in property <bool> var;
    in property <bool> force-accessible-enaled: false;

    private property <bool> accessible-mode: force-accessible-enaled || AccessibilitySettings.accessible-switches;

    callback toggled(bool);
    activated => toggled(!var);

    background: transparent;
    border-radius: self.height / 2;
    width: self.height * 1.8;

    if !AccessibilitySettings.animations-enabled: ToggleBoxInner {
        var: root.var;
        border-radius: root.border-radius;
        accessible-mode: root.accessible-mode;
    }
    if AccessibilitySettings.animations-enabled: AnimatedToggleBoxInner {
        var: root.var;
        border-radius: root.border-radius;
        accessible-mode: root.accessible-mode;
    }
}

// TODO: notifications
// likely requires backend logic for timing and generating the images

export struct Notification {
    id: string,
    title: string,
    body: string,
}

export global NotificationState {
    in-out property <[Notification]> notifications;
}

export component NotificationObjectCore {
    HorizontalLayout {
        i-icon := Image {
            width: 50px;
            height: 50px;
        }

        VerticalLayout {
            i-title := Text { }

            i-body := Text { }
        }
    }
}

export component NotificationObjectAnimated inherits NotificationObjectCore { }

export component NotificationObject {
    if AccessibilitySettings.animations-enabled: NotificationObjectAnimated { }
    if !AccessibilitySettings.animations-enabled: NotificationObjectCore { }
}

export component NotificationMain {
    for notification[i] in NotificationState.notifications: NotificationObject { }
}

export component ModuleDebug inherits VerticalLayout {
    Text {
        color: purple;
        text: "FocusState";
    }

    Text {
        color: white;
        text: FocusState.num-focuses;
    }

    Text {
        color: white;
        text: FocusState.current-focus-id;
    }

    Text {
        color: white;
        text: FocusState.last-focus-id;
    }

    Text {
        color: white;
        text: "{" + FocusState.focus-box.x / 1px + ", " + FocusState.focus-box.y / 1px + "}";
    }

    Text {
        color: white;
        text: "{" + FocusState.focus-box.width / 1px + ", " + FocusState.focus-box.height / 1px + "}";
    }

    Text {
        color: white;
        text: FocusState.force-focus-id + ": " + (FocusState.attempting-force-focus ? "true" : "false");
    }

    Text {
        color: orange;
        text: FocusState.failed-forces;
    }

    Text {
        color: purple;
        text: "DomainState";
    }

    Text {
        color: white;
        text: DomainState.num-domains;
    }

    Text {
        color: white;
        text: DomainState.current-domain-id;
    }

    Text {
        color: white;
        text: DomainState.last-domain-id;
    }

    Text {
        color: white;
        text: "{" + DomainState.focus-box.x / 1px + ", " + DomainState.focus-box.y / 1px + "}";
    }

    Text {
        color: white;
        text: "{" + DomainState.focus-box.width / 1px + ", " + DomainState.focus-box.height / 1px + "}";
    }

    Text {
        color: red;
        text: DomainState.navigation-errors;
    }

    Text {
        color: purple;
        text: "ComboBoxState";
    }

    Text {
        color: white;
        text: ComboBoxState.visible ? "visible" : "hidden";
    }

    Text {
        color: white;
        text: ComboBoxState.first-model-focus-id + ", " + ComboBoxState.last-model-focus-id;
    }

    Text {
        color: white;
        text: ComboBoxState.domain-id;
    }
}
