import { ModuleDebug as FocusDebug, Button, ComboBox, Slider, ToggleBox, TestComponentSuite } from "@lib";
import { SCarData } from "../data/car_data.slint";
import { GridBox } from "std-widgets.slint";
import { ModuleDebug as ApplicationStateDebug, BackendDebugModule } from "../data/application_state.slint";
import { DebugSettings, ApplicationState } from "../data/application_state.slint";

export global DebugMenuState {
    callback debug-suspend();
    callback can-write-test();
}

export component DebugMenuWidget {
    forward-focus: suspend-button;

    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        GridLayout {
            spacing: 10px;

            suspend-button := Button {
                text: "Suspend";

                activated => {
                    DebugMenuState.debug-suspend();
                }
            }

            write-test-button := Button {
                text: "CAN Write Test";

                activated => {
                    DebugMenuState.can-write-test();
                }
            }
        }

        TestComponentSuite { }
    }
}

export component DebugOverlay {
    x: 0;
    y: 20px;

    HorizontalLayout {
        alignment: start;
        spacing: 20px;

        VerticalLayout {
            alignment: start;

            Text {
                color: purple;
                text: "UI DEBUG";
            }

            ApplicationStateDebug { }

            FocusDebug { }
        }

        VerticalLayout {
            alignment: start;

            Text {
                color: darkviolet;
                text: "BACKEND DEBUG";
            }

            BackendDebugModule { }
        }
    }
}
