import { ScrollView } from "std-widgets.slint";

import { Button, ControlledFocusScope, FocusDomain, FocusState } from "@lib";
import { DebugMenuWidget, DebugMenuState } from "debug.slint";
import {
    RoadIndicatorWidget,
} from "../themes/default/components/road_indicators.slint";
import {
    ApplicationState,
    DebugSettings,
    AccessibilitySettings,
} from "../data/application_state.slint";
import { CanDisplayWidget } from "can_display.slint";

export global WidgetContainerState {
    in-out property <int> current-page: 0;
    in property <int> num-pages: 0;
    in-out property <int> focused-page: -1; // -1 if not entered

    public function change-page(to-page: int) {
        if to-page != current-page {
            current-page = to-page;
            self.exit-page();
        }
    }

    public function focus-page(to-page: int) {
        self.change-page(to-page);
        self.focused-page = self.current-page;
    }

    public function exit-page() {
        self.focused-page = -1;
    }
}

component Widget inherits FocusDomain {
    in-out property <bool> focusable: false;
    out property <int> page-number;
    out property <bool> has-focus: WidgetContainerState.focused-page == self.page-number;

    force-exit-strategy: focusable && true;
    force-focus: false;

    changed has-focus => {
        if focusable && has-focus {
            self.no-graceful-return = true;
            self.enter-domain();
        } else {
            WidgetContainerState.focused-page = -1;
        }
    }

    init => {
        self.page-number = WidgetContainerState.num-pages;
        WidgetContainerState.num-pages += 1;
    }

    exited => WidgetContainerState.exit-page();
}

component FocusableWidget inherits Widget {
    focusable: true;
}

component InternalContainerLayoutCore {
    in-out property <length> i-x;
    in-out property <length> follower: root.i-x;

    changed follower => {
        self.i-x = self.follower;
    }
}

component InternalContainerLayoutAnimated inherits InternalContainerLayoutCore {
    animate i-x {
        duration: 125ms;
        easing: ease-in-out;
    }
}

component InternalContainerLayout {
    in-out property <length> i-x: (-WidgetContainerState.current-page * self.width) - (self.spacing * WidgetContainerState.current-page);
    in-out property <length> spacing <=> i-layout.spacing;

    property <length> i-x-out;

    width: 100%;
    height: 100%;

    if AccessibilitySettings.animations-enabled: InternalContainerLayoutAnimated {
        follower: root.i-x;

        // spaceship causes weird jumps
        changed i-x => {
            root.i-x-out = self.i-x;
        }
    }
    if !AccessibilitySettings.animations-enabled: InternalContainerLayoutCore {
        i-x <=> root.i-x-out;
        follower: root.i-x;
    }

    i-layout := HorizontalLayout {
        spacing: 10px;
        x: root.i-x-out;

        @children
    }
}

export component WidgetContainer {
    width: 500px;
    height: 600px;
    forward-focus: center-widget-container-indicator;

    init => {
        WidgetContainerState.num-pages = 0;
    }

    VerticalLayout {
        // TODO: add dynamic images
        // requires backend
        center-widget-container-indicator := FocusDomain {
            property <length> indicator-width: self.height;

            height: 10%;
            force-exit-strategy: false;
            force-focus: true;

            nav-front-forward => WidgetContainerState.change-page(0);
            nav-end-backward => WidgetContainerState.change-page(WidgetContainerState.num-pages - 1);

            HorizontalLayout {
                alignment: center;
                spacing: 10px;

                for i in WidgetContainerState.num-pages: Rectangle {
                    private property <bool> has-view: WidgetContainerState.current-page == i;
                    private property <bool> domain-active: center-widget-container-indicator.domain-active;

                    width: indicator-width;
                    forward-focus: i-focus;

                    function attempt-focus() {
                        if domain-active && has-view && !i-focus.has-focus {
                            i-focus.focus();
                        }
                    }

                    changed has-view => {
                        attempt-focus();
                    }

                    changed domain-active => {
                        attempt-focus();
                    }

                    init => {
                        if i == 0 && domain-active {
                            i-focus.focus();
                        }
                    }

                    Text {
                        color: white;
                        text: i + 1;
                    }

                    i-focus := ControlledFocusScope {
                        init-focus: false;

                        focus-gained => {
                            if !has-view { // prevent dirty-ing the number and causing recursion
                                WidgetContainerState.change-page(i);
                            }
                        }

                        activated => WidgetContainerState.focus-page(i);
                    }
                }
            }
        }

        center-widget-container-inner := Rectangle {
            width: 80%;
            height: 90%;

            clip: true;

            center-widget-container-layout := InternalContainerLayout {

                road-indicator-widget := Widget {
                    RoadIndicatorWidget {
                        height: 100%;
                        width: 100%;
                    }
                }

                settings-menu-widget := FocusableWidget {
                    nav-front-forward => {
                        settings-button.focus()
                    }

                    HorizontalLayout {
                        alignment: center;
                        padding: 20px;

                        VerticalLayout {
                            alignment: center;

                            Rectangle {
                                settings-button := Button {
                                    text: "Settings";

                                    activated => {
                                        ApplicationState.settings-menu-visible = !ApplicationState.settings-menu-visible;
                                    }
                                }
                            }
                        }
                    }
                }

                FocusableWidget {
                    nav-front-forward => FocusState.force-focus(can-display-widget.first-focus-id);
                    nav-end-backward => FocusState.force-focus(can-display-widget.last-focus-id);

                    can-display-widget := CanDisplayWidget {
                        running: WidgetContainerState.current-page == parent.page-number;
                        height: 100%;
                        width: 100%;
                    }
                }

                if DebugSettings.debug-mode: FocusableWidget {
                    nav-front-forward => {
                        debug-menu-widget.focus()
                    }

                    debug-menu-widget := DebugMenuWidget {
                        height: 100%;
                        width: 100%;
                    }
                }
            }
        }
    }
}
