use crate::slint_generatedApp::{App, BackendLib, ClusterTheme};

use slint::{ComponentHandle, Model, Weak};
use strum::VariantArray;

pub fn bridge(handle_weak: Weak<App>) {
    if let Some(handle) = handle_weak.upgrade() {
        let lib = handle.global::<BackendLib>();

        lib.on_string_list_contains(|model, val| model.iter().find(|x| x == &val).is_some());
    }
}

impl std::fmt::Display for ClusterTheme {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

/// Because this enum is generated by `Slint`, it adds "r#" to every variant.
/// The `strum` functions use `stringify!`, so they only accept the literal value, but Rust does not display the "r#".
/// We want to remove the "r#" while still accepting the variant.
impl std::str::FromStr for ClusterTheme {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if let Some(val) = Self::VARIANTS.iter().find(|x| format!("{x}") == s) {
            Ok(*val)
        } else {
            Err(())
        }
    }
}
