import { SUnitSystem } from "../data/units.slint";

export global ApplicationState {
    in-out property <bool> debug-mode: true;

    in property <bool> virtual-cluster: true;

    in-out property <bool> simulation-running;
    callback update-simulation-running(bool);

    in-out property <SUnitSystem> user-unit;
    callback update-user-unit(SUnitSystem);

    in-out property <bool> settings-menu-visible: false;
}

export global GeneralSettings {
    in-out property <bool> disable-hill-assist;
    callback update-disable-hill-assist(bool);
}

export global AccessibilitySettings {
    in-out property <bool> animations-enabled;
    callback update-animations-enabled(bool);

    in-out property <bool> accessible-switches;
    callback update-accessible-switches(bool);
}

export global DebugSettings {
    in-out property <bool> debug-highlights;
    callback update-debug-highlights(bool);

    in-out property <bool> debug-overlay-enabled;
    callback update-debug-overlay-enabled(bool);
}

export component ModuleDebug inherits VerticalLayout {
    Text {
        color: purple;
        text: "ApplicationState";
    }

    Text {
        color: white;
        text: ApplicationState.virtual-cluster ? "virtual" : "normal";
    }

    if ApplicationState.virtual-cluster: Text {
        color: white;
        text: "Simulation: " + (ApplicationState.simulation-running ? "running" : "stopped");
    }

    Text {
        color: white;
        text: "Units: " + (ApplicationState.user-unit == SUnitSystem.USCS ? "USCS" : "SI");
    }

    Text {
        color: white;
        text: "Settings visible: " + (ApplicationState.settings-menu-visible ? "true" : "false");
    }

    Text {
        color: purple;
        text: "AccessibilitySettings";
    }

    Text {
        color: white;
        text: "Animations: " + (AccessibilitySettings.animations-enabled ? "true" : "false");
    }

    Text {
        color: purple;
        text: "DebugSettings";
    }

    Text {
        color: white;
        text: "Highlights: " + (DebugSettings.debug-highlights ? "true" : "false");
    }
}
