import { SUnitSystem } from "../data/units.slint";

export global ApplicationState {
    in-out property <bool> debug-mode: true;

    in property <bool> virtual-cluster: true;
    callback toggle_simulation();

    in-out property <SUnitSystem> user-unit;
    callback update_user_unit(SUnitSystem);

    in-out property <bool> settings-menu-visible: false;
}

export global AccessibilitySettings {
    in-out property <bool> animations-enabled;
    callback update-animations-enabled(bool);
}

export component ModuleDebug inherits VerticalLayout {
    Text {
        color: purple;
        text: "ApplicationState";
    }

    Text {
        color: white;
        text: ApplicationState.virtual-cluster ? "virtual" : "normal";
    }

    Text {
        color: white;
        text: "Units: " + (ApplicationState.user-unit == SUnitSystem.USCS ? "USCS" : "SI");
    }

    Text {
        color: white;
        text: "Settings visible: " + (ApplicationState.settings-menu-visible ? "true" : "false");
    }

    Text {
        color: purple;
        text: "AccessibilitySettings";
    }

    Text {
        color: white;
        text: "Animations: " + (AccessibilitySettings.animations-enabled ? "true" : "false");
    }
}
