export struct SFDataParameter {
    unit_str: string,
    min: float,
    max: float,
    value: float,
}

export struct SIDataParameter {
    unit_str: string,
    min: int,
    max: int,
    value: int,
}

export struct SBDataParameter {
    value: bool,
}

export struct SStrDataParameter {
    value: string,
}

@rust-attr(derive(serde::Serialize, serde::Deserialize))
export struct SBoundInt {
    value: int,
    step: int,
    start: int,
    end: int,
}
