import { Button, VerticalBox } from "std-widgets.slint";
import { InstrumentGauge, GaugeArc, RadialRect } from "components/instrument_gauge.slint";
import { RoadIndicatorWidget } from "components/road_indicators.slint";
import { SFDataParameter, SIDataParameter, SBDataParameter, SStrDataParameter } from "data/data_parameter.slint";
import { SymbolProperties } from "themes/main_symbol_properties.slint";
import { SCarData } from "data/car_data.slint";
import { SUnitSystem } from "data/units.slint";

import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Black.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Bold.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-ExtraLight.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Light.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Medium.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Regular.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-SemiBold.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Thin.ttf";

// Export types
export { SFDataParameter, SIDataParameter, SBDataParameter, SStrDataParameter, SUnitSystem }
// Export globals
export { SCarData }

export global ApplicationState {
    in property <bool> virtual_cluster: true;
    callback toggle_simulation();

    in-out property <SUnitSystem> user_unit;
    callback update_user_unit(SUnitSystem);
}

component PrimarySection inherits Rectangle {
    background: transparent;
}

component SymbolLight inherits Image {
    in property <float> scale: 1;
    width: SymbolProperties.size * scale;
    height: SymbolProperties.size * scale;
    padding: SymbolProperties.padding;
    image-fit: ImageFit.contain;
    colorize: Colors.blueviolet;
}

component GaugeAttachedSymbol inherits SymbolLight {
    in property <angle> angle: 0deg;
    in property <length> radius-offset: 25px;
    in property <length> radius: max(self.width, self.height) / 2;

    in property <length> center-x: 0px;
    in property <length> center-y: 0px;
    in property <length> center-radius: 1px;

    x: center-x - self.width / 2 + ((center-radius + radius + radius-offset) * cos(angle));
    y: center-y - self.height / 2 - ((center-radius + radius + radius-offset) * sin(angle));
}

export component AppWindow inherits Window {
    default-font-family: "Montserrat";
    default-font-weight: 400;

    title: "WRX Digital Instrument Cluster";

    preferred-height: 720px;
    preferred-width: 1920px;

    background: black;

    VerticalLayout {
        top-span := PrimarySection {
            background: transparent;
            height: max(SymbolProperties.size, root.height * 1 / 20);
        }

        mid-span := HorizontalLayout {
            left-tri := PrimarySection {
                width: parent.width * 38%;

                tachometer := InstrumentGauge {
                    property <angle> redline: self.angle-range / 8 * 6.6;
                    // property <angle> symbol-buffer: cos()

                    width: self.height;
                    height: min(parent.height, parent.width * 75%);

                    y: parent.height / 2 - self.height / 2 + parent.height * 8%;

                    start: 180deg + 45deg;
                    end: -45deg;

                    progress: SCarData.engine_rpm.value / (SCarData.engine_rpm.max != 0 ? SCarData.engine_rpm.max : (SCarData.engine_rpm.value * 2));

                    needle-sweep-color: self.progress >= (redline / self.angle-range) ? red : white;

                    regions: [
                        {
                            start: self.start - 0.75deg,
                            end: self.end,
                            major-ticks: 9,
                            major-tick-inner-radius: self.width / 2 - 40px,
                            major-tick-outer-radius: self.width / 2,
                            major-tick-fill: Colors.white,
                            major-tick-size: 0.75deg,
                            label-major-ticks: true,
                            major-tick-label-scale: 1,
                            major-tick-label-fill: Colors.white,
                            minor-ticks: 3,
                            minor-tick-inner-radius: self.width / 2 - 30px,
                            minor-tick-outer-radius: self.width / 2,
                            minor-tick-fill: Colors.white,
                            minor-tick-size: 0.3deg,
                            fill-final-tick: true,
                        }
                    ];

                    GaugeArc {
                        width: 100%;
                        height: 100%;

                        fill: red.darker(30%);
                        z: -1;

                        inner-radius: parent.regions[0].major-tick-inner-radius + 27.5px;
                        outer-radius: parent.regions[0].major-tick-outer-radius - 5px;

                        start: parent.start + parent.redline;
                        end: parent.end;
                    }

                    tachometer-unit-label := Text {
                        text: "×1000";
                        color: tachometer.background-fill.transparentize(85%);
                        font-size: 25px;
                        horizontal-alignment: TextHorizontalAlignment.center;
                        y: parent.height * 27.5%;
                    }
                }

                mt-gear-label := Text {
                    text: SCarData.reverse_sw.value ? "R" : SCarData.mt_gear.value;
                    color: white;
                    font-size: 50px;

                    x: tachometer.x + tachometer.width / 2 - self.width / 2;
                    y: tachometer.y + tachometer.height / 2 - self.height / 2;

                    vertical-alignment: TextVerticalAlignment.center;
                    horizontal-alignment: TextHorizontalAlignment.center;
                }

                parking-brake-warning := SymbolLight {
                    scale: 1.2;

                    y: tachometer.y + tachometer.height * 65%;

                    source: @image-url("../../resources/images/brake-warning-indicator-light-letters-only.png");
                    colorize: SymbolProperties.symbol_color_red;

                    visible: SCarData.handbrake_sw.value;
                }

                left-turn-signal := GaugeAttachedSymbol {
                    height: SymbolProperties.size * 0.8;
                    width: SymbolProperties.size;

                    center-radius: tachometer.width / 2;
                    center-x: tachometer.x + tachometer.width / 2;
                    center-y: tachometer.y + tachometer.height / 2;

                    angle: 40deg;

                    source: @image-url("../../resources/images/turn-signal-arrow.png");
                    colorize: SymbolProperties.symbol_color_green;

                    visible: SCarData.left_turn_signal_enabled.value;
                    rotation-angle: 180deg;
                }

                highbeam-indicator := GaugeAttachedSymbol {
                    source: @image-url("../../resources/images/highbeam-indicator-light.png");
                    colorize: SymbolProperties.symbol_color_blue;

                    property <length> test: left-turn-signal.x - self.width;

                    angle: left-turn-signal.angle + SymbolProperties.symbol_angle_padding;

                    center-radius: tachometer.width / 2;
                    center-x: tachometer.x + tachometer.width / 2;
                    center-y: tachometer.y + tachometer.height / 2;

                    visible: SCarData.highbeams_enabled.value;
                }

                foglight-indicator := GaugeAttachedSymbol {
                    scale: 0.8;
                    source: @image-url("../../resources/images/front-fog-indicator-light.png");
                    colorize: SymbolProperties.symbol_color_green;

                    angle: highbeam-indicator.angle + SymbolProperties.symbol_angle_padding;

                    center-radius: tachometer.width / 2;
                    center-x: tachometer.x + tachometer.width / 2;
                    center-y: tachometer.y + tachometer.height / 2;

                    visible: SCarData.fog_lights_enabled.value;
                }

                check-engine-light := GaugeAttachedSymbol {
                    center-radius: tachometer.width / 2;
                    center-x: tachometer.x + tachometer.width / 2;
                    center-y: tachometer.y + tachometer.height / 2;

                    angle: 360deg - 40deg;

                    source: @image-url("../../resources/images/check-engine-warning-light-icon.png");
                    colorize: SymbolProperties.symbol-color-yellow;

                    visible: SCarData.check_engine_light_enabled.value;
                }

                oil-pressure-warning-light := GaugeAttachedSymbol {
                    center-radius: tachometer.width / 2;
                    center-x: tachometer.x + tachometer.width / 2;
                    center-y: tachometer.y + tachometer.height / 2;

                    angle: check-engine-light.angle + SymbolProperties.symbol_angle_padding;

                    source: @image-url("../../resources/images/oil-pressure-warning-light.png");
                    colorize: SymbolProperties.symbol-color-red;

                    visible: SCarData.oil_pressure_warning_light_enabled.value;
                }
            }

            mid-tri := PrimarySection {
                padding: 10px;

                Rectangle {
                    background: purple;
                    border-radius: 5px;

                    property <length> buffer: 2.5px;

                    center-widget-container := Rectangle {
                        background: black;
                        border-radius: parent.border-radius;
                        clip: true;

                        x: parent.buffer / 2;
                        y: parent.buffer / 2;

                        width: parent.width - parent.buffer;
                        height: parent.height - parent.buffer;

                        RoadIndicatorWidget { }
                    }
                }
            }

            right-tri := PrimarySection {
                width: left-tri.width;

                speedometer := InstrumentGauge {
                    width: self.height;
                    height: tachometer.height;

                    y: tachometer.y;

                    start: tachometer.start;
                    end: tachometer.end;

                    property <int> max: SCarData.vehicle_speed.max != 0 ? SCarData.vehicle_speed.max : 1000;
                    progress: SCarData.vehicle_speed.value / max;

                    property <int> speed_delim: ApplicationState.user_unit == SUnitSystem.USCS ? 20 : 20;
                    property <int> final_speed_delim: (max / speed_delim) + 1;

                    property <int> minor_ticks: ApplicationState.user_unit == SUnitSystem.USCS ? 1 : 1;
                    property <color> tick_color: #ffffff;
                    property <float> tick_size: 0.175%;

                    regions: [
                        {
                            start: self.start - 1deg,
                            end: self.end,
                            major-ticks: final_speed_delim,
                            major-tick-inner-radius: self.width / 2 - 40px,
                            major-tick-outer-radius: self.width / 2,
                            major-tick-fill: Colors.white,
                            major-tick-size: 0.7deg,
                            label-major-ticks: true,
                            major-tick-label-scale: speed_delim,
                            major-tick-label-fill: Colors.white,
                            minor-ticks: minor_ticks,
                            minor-tick-inner-radius: self.width / 2 - 30px,
                            minor-tick-outer-radius: self.width / 2,
                            minor-tick-fill: Colors.white,
                            minor-tick-size: 0.3deg,
                            fill-final-tick: true,
                        }
                    ];

                    speedometer-label := Text {
                        text: round(SCarData.vehicle_speed.value);
                        color: white;
                        font-size: 45px;

                        vertical-alignment: TextVerticalAlignment.center;
                        horizontal-alignment: TextHorizontalAlignment.center;
                    }

                    speedometer-unit-label := Text {
                        text: SCarData.vehicle_speed.unit-str;
                        color: speedometer-label.color.transparentize(75%);
                        font-size: speedometer-label.font-size * 70%;
                        horizontal-alignment: TextHorizontalAlignment.center;
                        y: speedometer-label.y + speedometer-label.height;
                    }
                }

                right-turn-signal := GaugeAttachedSymbol {
                    height <=> left-turn-signal.height;
                    width <=> left-turn-signal.width;

                    center-radius: speedometer.width / 2;
                    center-x: speedometer.x + speedometer.width / 2;
                    center-y: speedometer.y + speedometer.height / 2;

                    angle: 180deg - left-turn-signal.angle;

                    source: @image-url("../../resources/images/turn-signal-arrow.png");
                    colorize: SymbolProperties.symbol_color_green;

                    visible: SCarData.right_turn_signal_enabled.value;
                }

                headlight-indicator := GaugeAttachedSymbol {
                    scale: 1.1;
                    center-radius: speedometer.width / 2;
                    center-x: speedometer.x + speedometer.width / 2;
                    center-y: speedometer.y + speedometer.height / 2;

                    angle: 180deg - highbeam-indicator.angle;

                    source: @image-url("../../resources/images/headlight-indicator-light.png");
                    colorize: SymbolProperties.symbol-color-green;

                    visible: SCarData.lowbeams_enabled.value;

                    // TODO: check if headlight_dimmer is on during the day when running lights are on

                    // the factory cluster does not distinguish between the parking lights and the lowbeams
                    // I believe this to be a safety issue
                    // visible: SCarData.lowbeams_enabled.value || SCarData.parking_lights_enabled.value;
                }

                driver-seatbelt-indicator := GaugeAttachedSymbol {
                    scale: 0.9;
                    center-radius: speedometer.width / 2;
                    center-x: speedometer.x + speedometer.width / 2;
                    center-y: speedometer.y + speedometer.height / 2;

                    angle: 180deg - foglight-indicator.angle;

                    source: @image-url("../../resources/images/seatbelt-warning-light.png");
                    colorize: SymbolProperties.symbol-color-red;

                    visible: SCarData.driver_seatbelt_warning_enabled.value;
                }

                hill-assist-enabled-indicator := GaugeAttachedSymbol {
                    scale: 0.8;
                    center-radius: speedometer.width / 2;
                    center-x: speedometer.x + speedometer.width / 2;
                    center-y: speedometer.y + speedometer.height / 2;

                    angle: 360deg - 40deg;

                    source: @image-url("../../resources/images/hillstartassist-warning-light.png");
                    colorize: SymbolProperties.symbol-color-yellow;

                    visible: SCarData.hill_assist_enabled.value;
                }

                vdc-off-warning-indicator := GaugeAttachedSymbol {
                    center-radius: speedometer.width / 2;
                    center-x: speedometer.x + speedometer.width / 2;
                    center-y: speedometer.y + speedometer.height / 2;

                    angle: 180deg + 40deg;

                    source: @image-url("../../resources/images/vehicle-dynamics-control-off-indicator-light.png");
                    colorize: SymbolProperties.symbol-color-yellow;

                    visible: SCarData.traction_control_disabled.value;
                }

                tq-vectoring-enabled-indicator := GaugeAttachedSymbol {
                    center-radius: speedometer.width / 2;
                    center-x: speedometer.x + speedometer.width / 2;
                    center-y: speedometer.y + speedometer.height / 2;

                    angle: vdc-off-warning-indicator.angle - SymbolProperties.symbol_angle_padding;

                    source: @image-url("../../resources/images/traction-mode-indicator-light.png");
                    colorize: SymbolProperties.symbol-color-green;

                    visible: SCarData.active_tq_vectoring_enabled.value;
                }
            }
        }

        bottom-span := PrimarySection {
            height: odometer-text.font-size * 150%;

            odometer-text-section := Rectangle {
                background: transparent;
                x: parent.x + parent.width / 2 - self.width / 2;

                odometer-text := Text {
                    color: white;
                    text: floor(SCarData.odometer.value);
                    font-size: 30px;
                    vertical-alignment: TextVerticalAlignment.center;
                    horizontal-alignment: TextHorizontalAlignment.center;
                    x: parent.x + parent.width / 2 - self.width / 2;
                }

                odometer-dec-text := Text {
                    color: odometer-text.color.transparentize(60%);
                    text: "." + (floor(SCarData.odometer.value * 10) / 10 - floor(SCarData.odometer.value)) * 10;
                    font-size: odometer-text.font-size;
                    horizontal-alignment: TextHorizontalAlignment.left;
                    vertical-alignment: odometer-text.vertical-alignment;
                    x: odometer-text.x + odometer-text.width;
                }

                odometer-unit-text := Text {
                    color: odometer-text.color.transparentize(70%);
                    text: SCarData.odometer.unit_str;
                    font-size: odometer-text.font-size * 70%;
                    x: odometer-dec-text.x + odometer-dec-text.width;
                    y: odometer-dec-text.y + odometer-dec-text.height / 2 - self.height / 2;
                }
            }

            unit-toggle-button := Button {
                text: "Toggle Unit System";
                x: 0;

                clicked => {
                    ApplicationState.update_user_unit(ApplicationState.user_unit == SUnitSystem.USCS ? SUnitSystem.SI : SUnitSystem.USCS);
                }
            }

            Text {
                text: ApplicationState.user_unit == SUnitSystem.USCS ? "USCS" : "SI";
                x: unit-toggle-button.x + unit-toggle-button.width + 10px;
            }

            if ApplicationState.virtual_cluster: simulation-toggle-button := Button {
                text: "Toggle Simulation";
                x: parent.width - self.width;

                clicked => {
                    ApplicationState.toggle_simulation();
                }
            }
        }
    }
}
