import { Button, VerticalBox } from "std-widgets.slint";
import { InstrumentGauge, GaugeArc } from "components/instrument_gauge.slint";
import { SFDataParameter, SIDataParameter, SBDataParameter, SStrDataParameter } from "data/data_parameter.slint";
import { SCarData } from "data/car_data.slint";
import { SUnitSystem, SUserUnit } from "data/units.slint";

import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Black.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Bold.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-ExtraLight.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Light.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Medium.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Regular.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-SemiBold.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Thin.ttf";

// Export types
export { SFDataParameter, SIDataParameter, SBDataParameter, SStrDataParameter, SUnitSystem }
// Export globals
export { SCarData, SUserUnit }

export global SymbolColors {
    out property <color> symbol_color_blue: #0000ff;
    out property <color> symbol_color_dark_grey: #4b4b4b;
    out property <color> symbol_color_green: #00e600;
    out property <color> symbol_color_grey: #7d7d7d;
    out property <color> symbol_color_red: #ff0000;
    out property <color> symbol_color_white: #ffffff;
    out property <color> symbol_color_yellow: #ffb300;
}

component PrimarySection inherits Rectangle {
    background: transparent;
}

export component AppWindow inherits Window {
    callback toggle_simulation();

    property <length> icon_size: 75px;

    default-font-family: "Montserrat";
    default-font-weight: 400;

    title: "WRX Digital Instrument Cluster";

    preferred-height: 720px;
    preferred-width: 1920px;

    background: black;

    VerticalLayout {
        top-span := PrimarySection {
            background: transparent;
            height: max(icon_size, root.height * 1 / 20);

            unit-toggle-button := Button {
                text: "Toggle Unit System";
                x: 0;

                clicked => {
                    SUserUnit.update_user_unit(SUserUnit.user_unit == SUnitSystem.USCS ? SUnitSystem.SI : SUnitSystem.USCS);
                }
            }

            simulation-toggle-button := Button {
                text: "Toggle Simulation";
                x: parent.width - self.width;

                clicked => {
                    toggle_simulation();
                }
            }

            Text {
                text: SUserUnit.user_unit == SUnitSystem.USCS ? "USCS" : "SI";
                x: unit-toggle-button.x + unit-toggle-button.width + 10px;
            }

            lowbeam-indicator := Image {
                height: icon_size;
                width <=> self.height;

                source: @image-url("../../resources/images/headlight-indicator-light.png");
                colorize: SymbolColors.symbol_color_green;

                visible: SCarData.lowbeams_enabled.value;
            }
        }

        HorizontalLayout {
            left-tri := PrimarySection {
                width: parent.width * 38%;

                tachometer := InstrumentGauge {

                    width: self.height;
                    height: min(parent.height, parent.width * 70%);
                    range: 75%;
                    start: -50% + 25% / 2;

                    inner_radius: self.width / 2px - self.width / 6px;
                    background_inner_radius: self.width / 2px - 2;

                    progress: SCarData.engine_rpm.value / (SCarData.engine_rpm.max != 0 ? SCarData.engine_rpm.max : (SCarData.engine_rpm.value * 2));

                    property <int> ticks: ceil(SCarData.engine_rpm.max / 1000);
                    property <int> minor_ticks: 3;
                    property <color> tick_color: #ffffff;
                    property <float> tick_size: 0.175%;
                    property <float> tick_step: self.range / self.ticks;
                    property <float> minor_tick_step: tick_step / (self.minor_ticks + 1);

                    rpm-first-tick := GaugeArc {
                        viewbox-width: parent.width / 1px;
                        viewbox-height: parent.height / 1px;

                        fill: tachometer.tick_color;
                        fill-rule: FillRule.nonzero;
                        inner-radius: tachometer.inner_radius + tachometer.width / 15px;
                        progress: tachometer.tick_size;
                        start: parent.start;
                        range: parent.range;
                    }

                    for tick in ticks: Rectangle {
                        property <int> display_tick: tick + 1;
                        property <float> start: parent.start - display_tick * parent.tick_step;
                        property <length> label_radius: parent.inner_radius * 1px + 30px - rpm-tick-label.font-size;

                        width: parent.width;
                        height: parent.height;

                        rpm-tick-line := GaugeArc {
                            viewbox-width: parent.width / 1px;
                            viewbox-height: parent.height / 1px;

                            fill: tachometer.tick_color;
                            inner_radius: rpm-first-tick.inner_radius;
                            progress: tachometer.tick_size;
                            start: parent.start - 0.25 + (75% / tachometer.ticks);
                            range: tachometer.range;
                        }

                        rpm-tick-label := Text {
                            text: display_tick;
                            color: white;
                            font-size: 25px;
                            x: parent.width / 2 + label_radius * cos(-parent.start * 360deg) - self.width / 2;
                            y: parent.height / 2 + label_radius * sin(-parent.start * 360deg) - self.height / 2;
                        }

                        for minor_tick in minor_ticks: Rectangle {
                            property <float> start: parent.start - (minor_tick + 1) * tachometer.minor_tick_step;
                            width: parent.width;
                            height: parent.height;

                            rpm-minor-tick-line := GaugeArc {
                                viewbox-width: parent.width / 1px;
                                viewbox-height: parent.height / 1px;

                                fill: tachometer.tick_color;
                                inner_radius: tachometer.inner_radius + tachometer.width / ((minor-tick + 1) == (tachometer.minor_ticks + 1) / 2 ? 9.5px : 8px);
                                progress: tachometer.tick_size;
                                start: parent.start - 0.25 + (tachometer.range / tachometer.ticks);
                                range: tachometer.range;
                            }
                        }
                    }

                    mt-gear-label := Text {
                        text: SCarData.mt_gear.value;
                        color: white;
                        font-size: 50px;
                    }

                    rpm-unit-label := Text {
                        text: "×1000";
                        color: tachometer.tick_color.transparentize(85%);
                        font-size: 25px;
                        horizontal-alignment: TextHorizontalAlignment.center;
                        y: parent.height * 27.5%;
                    }

                    parking-brake-warning := Image {
                        height: icon_size;
                        width: icon_size * 1.1;

                        y: min(parent.height - self.height, parent.height * 65%);

                        source: @image-url("../../resources/images/brake-warning-indicator-light-letters-only.png");
                        colorize: SymbolColors.symbol_color_red;

                        visible: SCarData.handbrake_sw.value;
                    }
                }

                left-turn-signal := Image {
                    height <=> right-turn-signal.height;
                    width <=> right-turn-signal.width;

                    x: tachometer.x + tachometer.width / 2 - self.width / 2 + tachometer.width / 1.5 * cos(45deg);
                    y: tachometer.y + tachometer.height / 2 - self.height / 2 - tachometer.height / 1.5 * sin(45deg);

                    image-fit: ImageFit.contain;
                    source: right-turn-signal.source;
                    colorize: SymbolColors.symbol_color_green;

                    visible: SCarData.left_turn_signal_enabled.value;
                    rotation-angle: 180deg;
                }
            }

            mid-tri := PrimarySection { }

            right-tri := PrimarySection {
                width: left-tri.width;

                speedometer := InstrumentGauge {
                    width: self.height;
                    height: tachometer.height;
                    range: 75%;
                    start: -50% + 25% / 2;

                    inner_radius: tachometer.inner_radius;
                    background_inner_radius: tachometer.background_inner_radius;

                    progress: SCarData.vehicle_speed.value / (SCarData.vehicle_speed.max != 0 ? SCarData.vehicle_speed.max : (SCarData.vehicle_speed.value * 2));

                    property <int> speed_delim: SUserUnit.user_unit == SUnitSystem.USCS ? 20 : 25;
                    property <int> final_speed_delim: SCarData.vehicle_speed.max / speed_delim;

                    property <int> ticks: final_speed_delim;
                    property <int> minor_ticks: 1;
                    property <color> tick_color: #ffffff;
                    property <float> tick_size: 0.175%;
                    property <float> tick_step: self.range / self.ticks;
                    property <float> minor_tick_step: tick_step / (self.minor_ticks + 1);

                    speed-first-tick := GaugeArc {
                        viewbox-width: parent.width / 1px;
                        viewbox-height: parent.height / 1px;

                        fill: speedometer.tick_color;
                        inner_radius: speedometer.inner_radius + speedometer.width / 10px;
                        progress: speedometer.tick_size;
                        start: parent.start;
                        range: 75%;
                    }

                    for tick in ticks: Rectangle {
                        property <int> display_tick: tick + 1;
                        property <float> start: parent.start - display_tick * parent.tick_step;
                        property <length> label_radius: parent.inner_radius * 1px + 33px - speed-tick-label.font-size;

                        width: parent.width;
                        height: parent.height;

                        speed-tick-line := GaugeArc {
                            viewbox-width: parent.width / 1px;
                            viewbox-height: parent.height / 1px;

                            fill: speedometer.tick_color;
                            inner_radius: speed-first-tick.inner_radius;
                            progress: speedometer.tick_size;
                            start: parent.start - 0.25 + (75% / speedometer.ticks);
                            range: 75%;
                        }

                        speed-tick-label := Text {
                            text: display_tick * speed_delim;
                            color: white;
                            font-size: 15px;
                            x: parent.width / 2 + label_radius * cos(-parent.start * 360deg) - self.width / 2;
                            y: parent.height / 2 + label_radius * sin(-parent.start * 360deg) - self.height / 2;
                        }

                        for minor_tick in minor_ticks: Rectangle {
                            property <float> start: parent.start - (minor_tick + 1) * speedometer.minor_tick_step;
                            width: parent.width;
                            height: parent.height;

                            speed-minor-tick-line := GaugeArc {
                                viewbox-width: parent.width / 1px;
                                viewbox-height: parent.height / 1px;

                                fill: speedometer.tick_color;
                                inner_radius: speedometer.inner_radius + speedometer.width / ((minor-tick + 1) == (speedometer.minor_ticks + 1) / 2 ? 7.5px : 9px);
                                progress: speedometer.tick_size;
                                start: parent.start - 0.25 + (speedometer.range / speedometer.ticks);
                                range: 75%;
                            }
                        }
                    }

                    speedometer-label := Text {
                        text: round(SCarData.vehicle_speed.value);
                        color: white;
                        font-size: 45px;

                        vertical-alignment: TextVerticalAlignment.center;
                        horizontal-alignment: TextHorizontalAlignment.center;
                    }

                    speedometer-unit-label := Text {
                        text: SCarData.vehicle_speed.unit-str;
                        color: speedometer-label.color.transparentize(75%);
                        font-size: speedometer-label.font-size * 70%;
                        horizontal-alignment: TextHorizontalAlignment.center;
                        y: speedometer-label.y + speedometer-label.height;
                    }
                }

                right-turn-signal := Image {
                    height: icon_size * 0.8;
                    width <=> self.height;

                    x: speedometer.x + speedometer.width / 2 - self.width / 2 - speedometer.width / 1.5 * cos(45deg);
                    y: speedometer.y + speedometer.height / 2 - self.height / 2 - speedometer.height / 1.5 * sin(45deg);

                    source: @image-url("../../resources/images/turn-signal-arrow.png");
                    colorize: SymbolColors.symbol_color_green;

                    visible: SCarData.right_turn_signal_enabled.value;
                }
            }
        }

        bottom-span := PrimarySection {
            height: odometer-text.height * 110%;

            odometer-text := Text {
                color: white;
                text: round(SCarData.odometer.value);
                font-size: 30px;
                vertical-alignment: TextVerticalAlignment.center;
                horizontal-alignment: TextHorizontalAlignment.center;
            }

            odometer-unit-text := Text {
                color: gray;
                text: SCarData.odometer.unit_str;
                font-size: odometer-text.font-size * 70%;
                x: odometer-text.x + odometer-text.width;
                y: odometer-text.y + odometer-text.height / 2 - self.height / 2;
            }
        }
    }
}
