// Generated code from build.rs::generate_slint_car_data()!
import {SFDataParameter, SIDataParameter, SBDataParameter, SStrDataParameter} from "data_parameter.slint";
export global SCarData {
// GSensor
	in property <SFDataParameter> g_sensor_lateral;
	in property <SFDataParameter> g_sensor_longitudinal;
// XxxMsg209
	in property <SFDataParameter> brake_pedal_pressure;
	in property <SFDataParameter> vehicle_speed;
// DriverRoadAssists
	in property <SBDataParameter> hill_assist_enabled;
	in property <SBDataParameter> tq_vectoring_enabled;
	in property <SBDataParameter> traction_control_enabled;
// WheelSpeeds
	in property <SFDataParameter> left_front_wheel_speed;
	in property <SFDataParameter> left_rear_wheel_speed;
	in property <SFDataParameter> right_front_wheel_speed;
	in property <SFDataParameter> right_rear_wheel_speed;
// Steering
	in property <SFDataParameter> steering_angle;
// MotorControl
	in property <SFDataParameter> accelerator_pedal_position;
	in property <SBDataParameter> clutch_sw;
	in property <SFDataParameter> combined_accelerator;
	in property <SBDataParameter> n_accelerator_pedal_max_sw;
	in property <SFDataParameter> throttle_plate_position;
// EngineStatus
	in property <SIDataParameter> engine_rpm;
	in property <SBDataParameter> engine_stop;
	in property <SIDataParameter> engine_torque;
	in property <SStrDataParameter> mt_gear;
	in property <SIDataParameter> wheel_torque;
// Transmission
	in property <SIDataParameter> mt_gear_verify;
// StatusSwitches
	in property <SBDataParameter> brake_sw;
	in property <SBDataParameter> handbrake_sw;
	in property <SBDataParameter> highbeams_enabled;
	in property <SBDataParameter> lowbeams_enabled;
	in property <SBDataParameter> parking_lights_enabled;
	in property <SBDataParameter> reverse_sw;
	in property <SBDataParameter> running_lights_enabled;
	in property <SBDataParameter> wiper_moving_sw;
// XxxMsg340
	in property <SBDataParameter> any_door_open;
// BsdRcta
	in property <SBDataParameter> rcta_enabled;
	in property <SBDataParameter> rcta_left;
	in property <SBDataParameter> rcta_right;
	in property <SBDataParameter> rtca_left_adjacent;
	in property <SBDataParameter> rtca_left_approaching;
	in property <SBDataParameter> rtca_right_adjacent;
	in property <SBDataParameter> rtca_right_approaching;
// XxxMsg640
	in property <SBDataParameter> passenger_seatbelt_warning_enabled;
	in property <SBDataParameter> driver_seatbelt_warning_enabled;
	in property <SFDataParameter> fuel_level;
	in property <SBDataParameter> left_turn_signal_enabled;
	in property <SIDataParameter> raw_fuel;
	in property <SBDataParameter> right_turn_signal_enabled;
// Ignition
	in property <SBDataParameter> access_key_detected;
	in property <SBDataParameter> ignition_acc;
	in property <SBDataParameter> ignition_on;
// EngineStatus2
	in property <SBDataParameter> cruise_control_enabled;
	in property <SBDataParameter> cruise_control_set_enabled;
	in property <SIDataParameter> cruise_control_speed;
	in property <SFDataParameter> engine_boost_pressure;
	in property <SIDataParameter> engine_coolant_temp;
	in property <SIDataParameter> engine_fuel_flow;
	in property <SIDataParameter> engine_oil_temp;
// EngineWarningLights
	in property <SBDataParameter> check_engine_light_enabled;
	in property <SBDataParameter> oil_pressure_warning_light_enabled;
// SrsStatus
	in property <SBDataParameter> srs_system_warning_light_enabled;
// XxxMsg884
	in property <SBDataParameter> fog_lights_enabled;
	in property <SBDataParameter> tpms_warning_light_enabled;
// XxxMsg885
	in property <SBDataParameter> dimmer_max_brightness_enable;
	in property <SBDataParameter> headlight_dimmer_enabled;
	in property <SBDataParameter> left_front_door_open;
	in property <SBDataParameter> left_rear_door_open;
	in property <SBDataParameter> right_front_door_open;
	in property <SBDataParameter> right_rear_door_open;
	in property <SBDataParameter> trunk_open;
// DimmerAndHood
	in property <SStrDataParameter> dimmer_dial_value;
	in property <SBDataParameter> hood_closed;
// DashState2Verify
	in property <SBDataParameter> units;
// Odometer
	in property <SFDataParameter> odometer;
// Tpms
	in property <SIDataParameter> left_front_tire_pressure;
	in property <SIDataParameter> left_rear_tire_pressure;
	in property <SIDataParameter> right_front_tire_pressure;
	in property <SIDataParameter> right_rear_tire_pressure;
}