export struct SFDataParameter {
	name: string,
	unit_str: string,

	min: float,
	max: float,

	observed_min: float,
	observed_max: float,

	value: float,
}

export struct SIDataParameter {
	name: string,
	unit_str: string,

	min: int,
	max: int,

	observed_min: int,
	observed_max: int,

	value: int,
}

export struct SBDataParameter {
	name: string,

	value: bool,
}

export struct SStrDataParameter {
	name: string,

	value: string,
}

