import { LineEdit } from "std-widgets.slint";
export component GaugeArc inherits Path {
    in property <float> inner_radius: 0;
    in property <float> progress: 0;
    in property <float> start: 0;
    in property <float> range: 1;

    property <float> scaled_progress: root.progress * root.range;

    viewbox-width: 100;
    viewbox-height: 100;

    MoveTo {
        y: root.viewbox-width / 2 - root.viewbox-width / 2 * cos(-root.start * 360deg);
        x: root.viewbox-height / 2 - root.viewbox-height / 2 * sin(-root.start * 360deg);
    }

    LineTo {
        y: root.viewbox-width / 2 - root.inner_radius * cos(-root.start * 360deg);
        x: root.viewbox-height / 2 - root.inner_radius * sin(-root.start * 360deg);
    }

    ArcTo {
        radius-x: root.inner_radius;
        radius-y: root.inner_radius;
        y: root.viewbox-width / 2 - root.inner_radius * cos(-(root.start + scaled_progress) * 360deg);
        x: root.viewbox-height / 2 - root.inner_radius * sin(-(root.start + scaled_progress) * 360deg);
        sweep: scaled_progress > 0;
        large-arc: scaled_progress > 0.5;
    }

    LineTo {
        y: root.viewbox-width / 2 - root.viewbox-width / 2 * cos(-(root.start + scaled_progress) * 360deg);
        x: root.viewbox-height / 2 - root.viewbox-height / 2 * sin(-(root.start + scaled_progress) * 360deg);
    }

    ArcTo {
        radius-x: root.viewbox-width / 2;
        radius-y: root.viewbox-height / 2;
        y: root.viewbox-width / 2 - root.viewbox-width / 2 * cos(-root.start * 360deg);
        x: root.viewbox-height / 2 - root.viewbox-height / 2 * sin(-root.start * 360deg);
        sweep: scaled_progress < 0;
        large-arc: scaled_progress > 0.5;
    }

    LineTo {
        y: root.viewbox-width / 2 - root.viewbox-width / 2 * cos(-root.start * 360deg);
        x: root.viewbox-width / 2 - root.viewbox-width / 2 * sin(-root.start * 360deg);
    }
}

component GaugeDisplay inherits Rectangle {
    in property <brush> fill_brush <=> gauge-sweep.fill;
    in property <brush> background_brush: #aaaaaa1f;
    in property <float> background_inner_radius <=> gauge-background.inner_radius;
    in property <float> inner_radius <=> gauge-sweep.inner_radius;
    in property <float> progress: 0;
    in property <float> start: 0;
    in property <float> range: 0;

    gauge-sweep := GaugeArc {
        width: 100%;
        height: 100%;
        range: root.range;
        progress: root.progress;
        start: root.start;

        viewbox-width: parent.width / 1px;
        viewbox-height: parent.height / 1px;
    }

    gauge-background := GaugeArc {
        fill: root.background_brush;
        width: 100%;
        height: 100%;
        start: root.start;
        range: root.range;
        progress: 100%;

        viewbox-width: parent.width / 1px;
        viewbox-height: parent.height / 1px;
    }
}

export component InstrumentGauge inherits Rectangle {
    in property <float> start <=> gauge-display.start;
    in property <float> range <=> gauge-display.range;
    in property <float> background_inner_radius: 100;
    in property <float> inner_radius: 100;
    in property <float> progress: 0;

    in property <brush> fill_brush <=> gauge-display.fill_brush;
    in property <brush> needle_brush <=> needle.fill;

    in property <float> needle_inner_radius <=> needle.inner-radius;
    in property <float> needle_thickness <=> needle.thickness;

    gauge-display := GaugeDisplay {
        background_brush: #ffffff;
        fill_brush: @radial-gradient(circle, #00000090 65%, #ffffff85 95%, #ffffff90 100%);
        background_inner_radius: root.background_inner_radius;
        inner_radius: root.inner_radius;
        progress: root.progress;
    }

    needle := Path {
        property <angle> rotation: (root.start * 1deg) + (parent.range * 360deg * -parent.progress) + 180deg + 45deg;
        property <float> inner-radius: 25;
        property <float> thickness: 1.25;

        viewbox-width: 100;
        viewbox-height: 100;

        fill: white;
        MoveTo {
            x: (parent.viewbox-width / 2) + cos(rotation) * (parent.viewbox-width / 2);
            y: (parent.viewbox-height / 2) - sin(rotation) * (parent.viewbox-height / 2);
        }

        LineTo {
            x: (parent.viewbox-width / 2) + cos(rotation + thickness * 1deg) * (inner-radius);
            y: (parent.viewbox-height / 2) - sin(rotation + thickness * 1deg) * (inner-radius);
        }

        LineTo {
            x: (parent.viewbox-width / 2) + cos(rotation) * (inner-radius - 0.75);
            y: (parent.viewbox-height / 2) - sin(rotation) * (inner-radius - 0.75);
        }

        LineTo {
            x: (parent.viewbox-width / 2) + cos(rotation - thickness * 1deg) * (inner-radius);
            y: (parent.viewbox-height / 2) - sin(rotation - thickness * 1deg) * (inner-radius);
        }
    }
}
