//!
//! This file exists as a preparation for a component like Qt's Loader
//! where we can dynamically load slint files. Tracked here: https://github.com/slint-ui/slint/issues/2390
//!

import { ComboBox } from "@lib";

export global GlobalThemeData {
    in-out property <[string]> themes; //* set by theme_loader_gen
    in-out property <string> current-theme: "Default";
    callback update_current_theme(string);
}

export struct ThemeParams {
    font-family: string,
    font-weight: int,
}
