import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Black.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Bold.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-ExtraLight.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Light.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Medium.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Regular.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-SemiBold.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Thin.ttf";

import { SFDataParameter, SIDataParameter } from "../../data/data_parameter.slint";

import { Tachometer } from "components/tachometer.slint";
import { PillGauge } from "components/generic-gauge.slint";
import { DebugMenuWidget, DebugMenuState } from "../../components/debug.slint";
import { SymbolLight } from "../default/theme_main.slint";
import { SymbolProperties } from "../default/symbol_properties.slint";
import { SCarData } from "../../data/car_data.slint";
import { SUnitSystem } from "../../data/units.slint";
import { ApplicationState } from "../../application/application_state.slint";
import { ThemeSelectorWidget } from "../themes.slint";
import { WidgetContainer } from "../../components/widget_container.slint";

global DefaultThemeParams {
    property <string> default-font-family:  "JetBrainsMono";
    property <int> default-font-weight: 400;
}

enum SideAlignment {
    right,
    left
}

component PillGaugeContainer inherits Rectangle {
    in property <image> image <=> symbol.source;
    in property <float> image-scale <=> symbol.scale;
    in property <SFDataParameter> data_parameter <=> gauge.data_parameter;
    in property <SideAlignment> symbol-alignment: SideAlignment.right;

    height: 18px;

    symbol := SymbolLight {
        scale: 30%;
        colorize: SymbolProperties.symbol_color_white;

        x: symbol-alignment == SideAlignment.right ? root.width - self.width : 0;
    }

    gauge := PillGauge {
        private property <color> needle-sweep-color:  SymbolProperties.symbol_color_white;

        width: root.width - symbol.width;
        height: 100%;

        x: symbol-alignment == SideAlignment.right ? 0 : root.width - self.width;
    }
}

export component TrackTheme inherits Rectangle {
    background: transparent;

    width: self.height * (1920 / 720);
    height: 500px;

    VerticalLayout {
        Rectangle {
            height: 33%;

            tachometer := Tachometer {
                y: parent.height - self.height;
                height: 65%;
                width: 90%;

                Text {
                    font-size: 25px;
                    y: -self.height;
                    x: parent.width - self.width;
                    color: white.transparentize(85%);

                    text: "×1000";
                }
            }
        }

        HorizontalLayout {
            height: 55%;

            private property <length> biglabel-x-offset: 25px;

            Rectangle {
                width: 30%;

                gear-indicator := Text {
                    y: 65px;
                    x: parent.width - self.width - biglabel-x-offset;
                    color: white;
                    text: SCarData.mt_gear.value;
                    font-size: 75px;

                    vertical-alignment: TextVerticalAlignment.center;
                    horizontal-alignment: TextHorizontalAlignment.center;
                }

                boost-test := Text {
                    y: gear-indicator.y + gear-indicator.height + 5px;
                    color: white;

                    text: SCarData.engine_boost_pressure.value;
                }

                boost-test-unit := Text {
                    y: boost-test.y + boost-test.height + 5px;
                    color: white;

                    text: SCarData.engine_boost_pressure.unit-str;
                }
            }

            HorizontalLayout {
                alignment: center;
                padding: 10px;

                WidgetContainer { }
            }

            Rectangle {
                width: 30%;

                speedometer-label := Text {
                    y: gear-indicator.y;
                    x: biglabel-x-offset;

                    text: round(SCarData.vehicle_speed.value);
                    color: white;
                    font-size: 60px;

                    vertical-alignment: TextVerticalAlignment.center;
                    horizontal-alignment: TextHorizontalAlignment.center;
                }

                speedometer-unit-label := Text {
                    y: speedometer-label.y + speedometer-label.height - speedometer-label.font-size / 2 + self.font-size * 20%;
                    x: biglabel-x-offset;

                    text: SCarData.vehicle_speed.unit-str;
                    color: speedometer-label.color.transparentize(75%);
                    font-size: speedometer-label.font-size * 70%;
                    horizontal-alignment: TextHorizontalAlignment.center;
                }
            }
        }

        HorizontalLayout {
            height: 12%;

            left-gauges := VerticalLayout {
                width: 30%;

                spacing: 6px;
                padding-left: 100px;
                padding-right: 20px;
                padding-bottom: 15px;
                alignment: end;

                PillGaugeContainer {
                    symbol-alignment: left;
                    image: @image-url("../../../../resources/images/coolant-temp-low-high-indicator-light.png");
                    data_parameter: SCarData.engine_coolant_temp;
                }

                PillGaugeContainer {
                    symbol-alignment: left;
                    image: @image-url("../../../../resources/images/oil-pressure-warning-light.png");
                    data_parameter: SCarData.engine_oil_temp;
                }
            }

            odometer-layout := VerticalLayout {
                alignment: LayoutAlignment.end;

                odometer-section := Rectangle {
                    odometer-label := Text {
                        color: white;
                        text: floor(SCarData.odometer.value);
                        font-size: 40px;
                        vertical-alignment: center;
                        horizontal-alignment: center;
                    }

                    odometer-dec-label := Text {
                        color: odometer-label.color.transparentize(60%);
                        text: "." + (floor(SCarData.odometer.value * 10) / 10 - floor(SCarData.odometer.value)) * 10;
                        font-size: odometer-label.font-size;
                        horizontal-alignment: TextHorizontalAlignment.left;
                        vertical-alignment: odometer-label.vertical-alignment;
                        x: odometer-label.x + odometer-label.width;
                    }

                    odometer-unit-label := Text {
                        vertical-alignment: center;
                        color: odometer-label.color.transparentize(70%);
                        text: SCarData.odometer.unit_str;
                        font-size: odometer-label.font-size * 70%;
                        x: odometer-dec-label.x + odometer-dec-label.width + 5px;
                    }
                }
            }

            VerticalLayout {
                width: 30%;

                spacing: left-gauges.spacing;
                padding-right: left-gauges.padding-left;
                padding-left: left-gauges.padding-right;
                padding-bottom: left-gauges.padding-bottom;
                alignment: left-gauges.alignment;

                PillGaugeContainer {
                    image: @image-url("../../../../resources/images/lowfuel-warning-light.png");
                    data_parameter: SCarData.fuel_level;
                }
            }
        }
    }
}
