export global SymbolProperties {
    out property <color> symbol_color_blue: #0000ff;
    out property <color> symbol_color_dark_grey: #4b4b4b;
    out property <color> symbol_color_green: #00e600;
    out property <color> symbol_color_grey: #7d7d7d;
    out property <color> symbol_color_red: #ff0000;
    out property <color> symbol_color_white: #ffffff;
    out property <color> symbol_color_yellow: #ffb300;
    out property <length> size: 80px;
    out property <length> padding: 5px;
    out property <angle> symbol_angle_padding: 14deg;
}
