//!
//! This file exists as a preparation for a component like Qt's Loader
//! where we can dynamically load slint files. Tracked here: https://github.com/slint-ui/slint/issues/2390
//!

import { ComboBox } from "../components/core.slint";

export global GlobalThemeData {
    in-out property <[string]> themes; //* set by theme_loader_gen
    in-out property <string> current-theme: "Default";
    callback update_current_theme(string);
}

export struct ThemeParams {
    font-family: string,
    font-weight: int,
}

export component ThemeSelectorWidget {
    forward-focus: theme-selection-box;

    HorizontalLayout {
        alignment: center;
        padding: 2px;

        theme-text := Text {
            vertical-alignment: center;
            color: white;
            text: "Theme: ";
        }

        theme-selection-box := ComboBox {
            width: 125px;

            model: GlobalThemeData.themes;

            current-value <=> GlobalThemeData.current-theme;

            changed current-value => {
                GlobalThemeData.update_current_theme(self.current-value);
            }
        }
    }
}
