//!
//! This file exists as a preparation for a component like Qt's Loader
//! where we can dynamically load slint files. Tracked here: https://github.com/slint-ui/slint/issues/2390
//!

import { ComboBox } from "std-widgets.slint";

export global Themes {
    in-out property <[string]> themes; //* set by theme_loader_gen
    in-out property <string> current-theme: "Default";
    callback theme-changed(string);
}

export component ThemeSelectorWidget {
    HorizontalLayout {
        alignment: center;
        padding: 2px;

        theme-text := Text {
            vertical-alignment: center;
            color: white;
            text: "Theme: ";
        }

        theme-selection-box := ComboBox {
            width: 125px;

            model: Themes.themes;
            current-value: Themes.current-theme;

            enabled: Themes.themes.length > 1;

            selected(current-value) => {
                Themes.theme-changed(current-value);
                Themes.current-theme = current-value;
            }
        }
    }
}
