//!
//! This file exists as a preparation for a component like Qt's Loader
//! where we can dynamically load slint files. Tracked here: https://github.com/slint-ui/slint/issues/2390
//!

import { ComboBox } from "std-widgets.slint";

export global Themes {
    out property <[string]> themes: ["Default", "Debug"];
    in-out property <string> current-theme: "Default";
    callback theme-changed(string);
}

export component ThemeSelectorWidget {
    theme-text := Text {
        text: "Theme: ";
    }

    theme-selection-box := ComboBox {
        y: theme-text.y + theme-text.height + 2px;
        model: Themes.themes;
        current-value: Themes.current-theme;

        enabled: Themes.themes.length > 1;

        selected(current-value) => {
            Themes.theme-changed(current-value);
            Themes.current-theme = current-value;
        }
    }
}
