import {
    ApplicationState,
    AccessibilitySettings,
    DebugSettings,
} from "@lib/state.slint";

export global LangResolver {
    pure callback translate(string) -> string;
}

export global BackendLib {
    pure callback string_list_contains([string], string) -> bool;
}

export global GlobalSizing {
    out property <length> button-height: 50px;
    out property <length> button-width: button-height * 2.5;
    out property <length> button-text-padding: 10px;
    //
    out property <length> combobox-width: button-height * 3.0;
    out property <length> combobox-arrow: 12px;
    out property <length> combobox-selection-indicator: 5px;
    //
    out property <length> slider-width: button-height * 1.25;
    out property <length> slider-selection-button: 20px;
    //
    out property <length> focus-box-border: AccessibilitySettings.selection-box-thickness * 1px;
}

export global GlobalAnimation {
    out property <duration> standard-duration: AccessibilitySettings.animations-enabled ? 70ms : 0s;
    out property <duration> toggle-box-switch-duration: AccessibilitySettings.animations-enabled ? 50ms : 0s;
    out property <duration> page-duration: AccessibilitySettings.animations-enabled ? 110ms : 0s;
    out property <duration> notification-duration: AccessibilitySettings.animations-enabled ? 250ms : 0s;
}

export struct ItemBox {
    x: length,
    y: length,
    width: length,
    height: length,
    border-radius: length,
}

export enum ForceFailedReason {
    FocusDisabled,
    Stolen
}

export global FocusState {
    in property <length> focus-highlight-size: GlobalSizing.focus-box-border;

    out property <int> num-focuses: 1;
    out property <int> current-focus-id: 0;
    out property <int> force-focus-id;
    out property <bool> attempting-force-focus;
    out property <int> last-focus-id;
    out property <ItemBox> focus-box: { x: 4px, y: 4px, width: 100px, height: 75px, border-radius: 75px / 3 };
    out property <int> failed-forces: 0;

    private property <bool> i-force-complete;

    public function create-focus-id() -> int {
        self.num-focuses += 1;
        self.num-focuses - 1
    }

    public function force-focus(id: int) {
        self.force-focus-id = id;
        self.attempting-force-focus = true;
    }

    pure public function has-focus(id: int) -> bool {
        self.current-focus-id == id
    }

    public function set-focus-id(id: int) {
        self.current-focus-id = id;
    }

    public function force-complete(id: int) {
        if id == self.force-focus-id {
            self.attempting-force-focus = false;
        }
    }

    public function force-failed(id: int, reason: ForceFailedReason) {
        self.attempting-force-focus = false;
    }

    public function set-focus-box(focus-box: ItemBox) {
        self.focus-box = focus-box;
    }

    public function set-last-focus-id(id: int) {
        self.last-focus-id = id;
    }
}

export global DomainState {
    out property <int> num-domains: 1;
    out property <int> current-domain-id: 0;
    out property <int> last-domain-id: 0;
    out property <int> navigation-errors: 0;

    in-out property <ItemBox> focus-box: { x: 0, y: 0, width: 0, height: 0 };

    public function create-domain-id() -> int {
        num-domains += 1;
        num-domains - 1
    }

    public function enter-domain(domain-id: int) {
        self.last-domain-id = self.current-domain-id;
        self.current-domain-id = domain-id;
    }

    public function domain-exit(domain-id: int) -> bool {
        if domain-id == self.current-domain-id {
            enter-domain(self.last-domain-id);
            true
        }
        false
    }

    public function set-focus-coords(x: length, y: length, width: length, height: length) {
        if self.focus-box.x != x {
            self.focus-box.x = x;
        }
        if self.focus-box.y != y {
            self.focus-box.y = y;
        }
        if self.focus-box.width != width {
            self.focus-box.width = width;
        }
        if self.focus-box.height != height {
            self.focus-box.height = height;
        }
    }

    public function set-last-domain-id(id: int) {
        self.last-domain-id = id;
    }

    public function navigation-error-occured(id: int) {
        self.navigation-errors += 1;
    }
}

export component DebugHighlight {
    in property <brush> background <=> i-rect.border-color;

    width: 100%;
    height: 100%;
    visible: DebugSettings.debug-mode && DebugSettings.debug-highlights;

    i-rect := Rectangle {
        background: transparent;
        border-width: 2px;
        border-color: purple;
    }
}

export component Arc inherits Path {
    in property <angle> start: 90deg;
    in property <angle> end: 180deg;
    in property <length> inner-radius: self.width / 3;
    in property <length> outer-radius: self.width / 2;

    property <angle> angle-range: end - start;

    fill: white;
    viewbox-width: self.width / 1px;
    viewbox-height: self.height / 1px;

    MoveTo {
        x: (parent.viewbox-width / 2) + cos(start) * (outer-radius / 1px);
        y: (parent.viewbox-height / 2) - sin(start) * (outer-radius / 1px);
    }

    LineTo {
        x: (parent.viewbox-width / 2) + cos(start) * (inner-radius / 1px);
        y: (parent.viewbox-height / 2) - sin(start) * (inner-radius / 1px);
    }

    ArcTo {
        x: (parent.viewbox-width / 2) + cos(end) * (inner-radius / 1px);
        y: (parent.viewbox-height / 2) - sin(end) * (inner-radius / 1px);
        radius-x: inner-radius / 1px;
        radius-y: inner-radius / 1px;
        sweep: angle-range < 0deg;
        large-arc: abs(angle-range) > 180deg;
    }

    LineTo {
        x: (parent.viewbox-width / 2) + cos(end) * (outer-radius / 1px);
        y: (parent.viewbox-height / 2) - sin(end) * (outer-radius / 1px);
    }

    ArcTo {
        x: (parent.viewbox-width / 2) + cos(start) * (outer-radius / 1px);
        y: (parent.viewbox-height / 2) - sin(start) * (outer-radius / 1px);
        radius-x: outer-radius / 1px;
        radius-y: outer-radius / 1px;
        sweep: angle-range > 0deg;
        large-arc: abs(angle-range) > 180deg;
    }

    LineTo {
        x: (parent.viewbox-width / 2) + cos(start) * (outer-radius / 1px);
        y: (parent.viewbox-height / 2) - sin(start) * (outer-radius / 1px);
    }
}

export component FocusHoverRect inherits Rectangle {
    private property <brush> hover-color: white;
    private property <length> size-offset: FocusState.focus-highlight-size;
    private property <length> new-height: FocusState.focus-box.height + size-offset * 2; // seperare property to allow height and border radius to animate simultaneously

    x: FocusState.focus-box.x - size-offset;
    y: FocusState.focus-box.y - size-offset;
    width: FocusState.focus-box.width + size-offset * 2;
    height: new-height;
    border-radius: FocusState.focus-box.border-radius * (new-height / FocusState.focus-box.height);
    background: transparent;
    border-width: size-offset;
    border-color: hover-color;
    z: 999999;

    animate x, y, width, height, border-radius { duration: GlobalAnimation.standard-duration; }
}

export component ControlledFocusScope inherits Rectangle {
    in-out property <bool> locked: false;

    in property <bool> init-focus: true;
    in property <bool> enabled <=> i-focus.enabled;

    out property <bool> has-focus <=> i-focus.has-focus;
    out property <bool> has-hover <=> i-touch.has-hover;
    out property <int> focus-id;

    private property <bool> state-attempting-force-focus: FocusState.attempting-force-focus;
    private property <bool> i-forcing-focus: FocusState.attempting-force-focus && (FocusState.force-focus-id == root.focus-id);
    private property <bool> i-last-locked: locked;

    forward-focus: i-focus;

    callback key-pressed(KeyEvent) -> EventResult;
    callback key-released(KeyEvent) -> EventResult;
    callback focus-gained(FocusReason);
    callback focus-lost(FocusReason);
    callback activated();
    callback init-ready();

    function __activated() {
        if !root.locked {
            root.activated()
        }
    }

    function update-coords() {
        // TODO: tie to changes in geometry;
        // TRACKING: https://github.com/slint-ui/slint/issues/7849
        FocusState.set-focus-box({
            x: root.absolute-position.x,
            y: root.absolute-position.y,
            width: root.width,
            height: root.height,
            border-radius: root.border-radius
        })
    }

    changed i-forcing-focus => {
        if i-forcing-focus {
            if root.enabled {
                root.focus();
            } else {
                FocusState.force-failed(root.focus-id, ForceFailedReason.FocusDisabled);
            }
        }
    }

    changed enabled => {
        if !self.enabled {
            self.i-last-locked = self.locked;
            self.locked = false;
        } else {
            self.locked = self.i-last-locked;
        }
    }

    i-touch := TouchArea {
        enabled: root.enabled;

        clicked => root.focus();
        double-clicked => root.__activated();
    }

    i-focus := FocusScope {
        width: 0;

        init => {
            root.focus-id = FocusState.create-focus-id();
            if init-focus || i-forcing-focus {
                self.focus();
            }
            root.init-ready();
        }

        key-pressed(event) => {
            if (event.text == Key.Return) || (event.text == Key.Space) {
                root.__activated();
                accept
            } else {
                root.key-pressed(event)
            }
        }

        key-released(event) => root.key-released(event);

        focus-lost(reason) => {
            // TODO: potentially check that the domain did not change unexpectedly and take back focus if it did
            FocusState.set-last-focus-id(root.focus-id);
            root.focus-lost(reason);
        }

        focus-gained(reason) => {
            if !FocusState.has-focus(root.focus-id) {
                update-coords();
                FocusState.set-focus-id(root.focus-id);
                root.focus-gained(reason);
            }
            if root.state-attempting-force-focus {
                if (reason == FocusReason.programmatic) && root.i-forcing-focus {
                    FocusState.force-complete(root.focus-id);
                } else {
                    FocusState.force-failed(root.focus-id, ForceFailedReason.Stolen);
                }
            }
        }
    }

    DebugHighlight {
        background: orange;
    }
}

export component Label {
    in property <TextHorizontalAlignment> horizontal-alignment <=> i-text.horizontal-alignment;
    in property <TextVerticalAlignment> vertical-alignment <=> i-text.vertical-alignment;
    in property <length> letter-spacing <=> i-text.letter-spacing;
    in property <TextOverflow> overflow <=> i-text.overflow;
    in property <TextWrap> wrap <=> i-text.wrap;
    in property <length> font-size <=> i-text.font-size;
    in property <brush> color <=> i-text.color;
    in property <string> text;
    in property <bool> translate: true;

    // TODO: make font stuff use theme font config

    i-text := Text {
        font-size: 16px;
        width: 100%;
        height: 100%;
        horizontal-alignment: TextHorizontalAlignment.center;
        vertical-alignment: TextVerticalAlignment.center;
        text: root.translate ? LangResolver.translate(root.text) : root.text;
        color: white;
    }

    DebugHighlight {
        background: purple;
    }
}

export component Button inherits ControlledFocusScope {
    in property <string> text <=> i-text.text;
    in property <TextHorizontalAlignment> horizontal-alignment <=> i-text.horizontal-alignment;
    in property <TextVerticalAlignment> vertical-alignment <=> i-text.vertical-alignment;
    in property <length> text-padding: GlobalSizing.button-text-padding;

    border-radius: 3px;
    background: self.locked ? gray.darker(95%).mix(black, 40%) : gray.darker(95%);
    height: GlobalSizing.button-height;
    width: GlobalSizing.button-width;
    init-focus: false;

    i-text := Label {
        x: root.text-padding;
        y: root.text-padding;
        width: root.width - root.text-padding * 2;
        height: root.height - root.text-padding * 2;
    }
}

export component FocusDomain inherits Rectangle {
    in property <bool> force-focus: true;
    in property <bool> force-exit-strategy: true;
    in property <length> exit-button-width <=> exit.width;

    out property <int> domain-id;
    out property <bool> domain-active: DomainState.current-domain-id == self.domain-id;

    in-out property <bool> no-graceful-return: false;

    private property <int> last-domain-id: DomainState.last-domain-id;
    private property <int> current-focus-id: FocusState.current-focus-id;
    private property <int> last-focus-id;
    private property <int> domain-last-focus-id;
    private property <bool> was-last: false;
    private property <bool> safe-return: false;

    callback nav-front-forward();
    callback nav-end-backward();
    callback exited();
    callback domain-returned();

    function i-domain-returned() {
        FocusState.force-focus(domain-last-focus-id);
        root.safe-return = true;
        root.domain-returned();
    }

    public function enter-domain() {
        DomainState.enter-domain(self.domain-id);
    }

    public function exit-domain() {
        DomainState.domain-exit(self.domain-id);
    }

    forward-focus: pre-nav-focus;

    changed domain-active => {
        if domain-active {
            DomainState.set-focus-coords(root.absolute-position.x, root.absolute-position.y, root.width, root.height);
            if was-last {
                was-last = false;
                i-domain-returned();
            }
            if !safe-return || no-graceful-return {
                pre-nav-focus.focus();
            }
            safe-return = false;
            no-graceful-return = false;
        } else {
            self.exited();
        }
    }

    changed last-domain-id => {
        if last-domain-id == domain-id {
            was-last = true;
        }
    }

    changed current-focus-id => {
        if domain-active {
            root.last-focus-id = current-focus-id;
        }
        if was-last {
            root.domain-last-focus-id = root.last-focus-id;
        }
    }

    init => {
        self.domain-id = DomainState.create-domain-id();

        if force-focus {
            enter-domain();
        }
    }

    pre-nav-lock := FocusScope {
        width: 0;

        focus-gained(reason) => {
            DomainState.navigation-error-occured(root.domain-id);
            pre-nav-focus.focus();
        }
    }

    pre-nav-focus := FocusScope {
        enabled: root.domain-active;
        width: 0;

        focus-gained(reason) => {
            if reason == FocusReason.tab-navigation {
                post-nav-focus.focus();
            } else {
                nav-front-forward();
            }
        }
    }

    DebugHighlight {
        background: domain-active ? red : lime;
    }

    container := Rectangle {
        y: 0;
        clip: true;
        height: (root.domain-active && force-exit-strategy) ? root.height - exit.height : root.height;

        @children
    }

    touch-lockout := TouchArea {
        enabled: !root.domain-active;
        width: 100%;
        height: 100%;
    }

    HorizontalLayout {
        alignment: center;
        y: root.height - exit.height;

        exit := Button {
            visible: root.domain-active && root.force-exit-strategy;
            text: "Back";

            activated => exit-domain();
        }
    }

    post-nav-focus := FocusScope {
        enabled: root.domain-active;
        width: 0;

        focus-gained(reason) => {
            if reason == FocusReason.tab-navigation {
                pre-nav-focus.focus();
            } else if force-exit-strategy {
                exit.focus();
            } else {
                nav-end-backward();
            }
        }
    }

    post-nav-lock := FocusScope {
        width: 0;

        focus-gained(reason) => {
            DomainState.navigation-error-occured(root.domain-id);
            post-nav-focus.focus();
        }
    }
}

export global ComboBoxState {
    in property <string> current-value;
    in property <string> title: "Combobox.Title";
    in property <int> domain-id;

    out property <[string]> model;
    out property <bool> visible: false;
    out property <ItemBox> focus-box;
    out property <bool> selection-made;
    out property <string> selection-value;
    out property <int> selection-index;

    public function make-selection(value: string, index: int) {
        self.selection-made = true;
        self.selection-value = value;
        self.selection-index = index;
    }

    public function complete-selection() {
        DomainState.domain-exit(self.domain-id);
        self.selection-made = false;
        self.visible = false;
    }

    public function set-model(model: [string]) {
        self.model = model;
    }

    public function show-selection-box() {
        self.visible = true;
    }

    public function set-focus-coords(x: length, y: length, width: length, height: length) {
        if self.focus-box.x != x {
            self.focus-box.x = x;
        }
        if self.focus-box.y != y {
            self.focus-box.y = y;
        }
        if self.focus-box.width != width {
            self.focus-box.width = width;
        }
        if self.focus-box.height != height {
            self.focus-box.height = height;
        }
    }
}

export global SliderState {
    in property <float> current-value: self.range-start;
    in property <string> title: "Slider.Title";
    in property <int> domain-id;

    out property <float> range-start: 0;
    out property <float> range-end: 10;
    out property <float> step: 1;
    out property <bool> visible: false;
    out property <ItemBox> focus-box;
    out property <bool> selection-made;
    out property <float> selection-value;

    public function make-selection(value: float, index: int) {
        self.selection-made = true;
        self.selection-value = value;
    }

    public function complete-selection() {
        DomainState.domain-exit(self.domain-id);
        self.selection-made = false;
        self.visible = false;
    }

    public function show-selection-box() {
        self.visible = true;
    }

    public function set-focus-coords(x: length, y: length, width: length, height: length) {
        if self.focus-box.x != x {
            self.focus-box.x = x;
        }
        if self.focus-box.y != y {
            self.focus-box.y = y;
        }
        if self.focus-box.width != width {
            self.focus-box.width = width;
        }
        if self.focus-box.height != height {
            self.focus-box.height = height;
        }
    }

    public function set-value-range(start: float, end: float, step: int) {
        self.range-start = start;
        self.range-end = end;
        self.step = step;
    }
}

// TODO: make this into a popup or our own derivative
component SelectionDomain inherits FocusDomain {
    in property <int> i-init-selection-box-focus;
    in property <bool> i-has-domain;
    in property <string> title;
    in property <int> first-model-focus-id;
    in property <int> last-model-focus-id;

    force-exit-strategy: false;
    background: black.transparentize(5%);

    function open() {
        if i-has-domain {
            root.focus();
            FocusState.force-focus(root.i-init-selection-box-focus);
        }
    }

    nav-front-forward => FocusState.force-focus(root.first-model-focus-id);
    nav-end-backward => FocusState.force-focus(root.last-model-focus-id);
    init => open();

    changed i-has-domain => open();
    changed i-init-selection-box-focus => open();

    HorizontalLayout {
        padding: 5px;
        alignment: center;

        i-layout := VerticalLayout {
            spacing: 15px;
            alignment: center;

            i-title := Label {
                height: self.font-size + 20px;
                text: root.title;
                font-size: 25px;
                horizontal-alignment: left;
                vertical-alignment: center;
            }

            @children
        }
    }
}

component ComboBoxSelectionBoxButton inherits Button {
    in property <bool> has-selection;

    width: self.height * 4;
    text-padding: GlobalSizing.button-text-padding + i-layout.padding;
    horizontal-alignment: TextHorizontalAlignment.left;

    i-layout := HorizontalLayout {
        padding: 6px;
        alignment: start;

        VerticalLayout {
            alignment: center;

            i-indicator := Rectangle {
                width: GlobalSizing.combobox-selection-indicator;
                height: 90%;
                background: white;
                visible: has-selection;
                border-radius: 2px;
            }
        }
    }
}

export component ComboBoxSelectionBox inherits SelectionDomain {
    i-has-domain: ComboBoxState.visible;
    force-exit-strategy: ComboBoxState.model.length == 0 ? true : false;
    title: ComboBoxState.title;

    for model[i] in ComboBoxState.model: HorizontalLayout {
        alignment: center;

        ComboBoxSelectionBoxButton {
            text: model;
            has-selection: ComboBoxState.current-value == model;

            init-ready => {
                if i == 0 {
                    root.first-model-focus-id = self.focus-id;
                } else if i == (ComboBoxState.model.length - 1) {
                    root.last-model-focus-id = self.focus-id;
                }
                if self.has-selection {
                    root.i-init-selection-box-focus = self.focus-id;
                }
            }

            activated => {
                ComboBoxState.domain-id = root.domain-id;
                ComboBoxState.make-selection(model, i);
            }
        }
    }
}

export component ComboBox inherits Button {
    in-out property <int> current-index: 0;
    in-out property <string> current-value: model[current-index];

    in property <[string]> model;
    in property <string> title;

    out property <bool> open;

    private property <bool> selection-state-made: ComboBoxState.selection-made;
    private property <int> domain-state-real-last;

    text: current-value;
    width: GlobalSizing.combobox-width;
    horizontal-alignment: TextHorizontalAlignment.left;

    callback selection-made();

    activated => activate-open();

    changed selection-state-made => {
        if open {
            root.current-index = ComboBoxState.selection-index;
            root.current-value = ComboBoxState.selection-value;
            ComboBoxState.complete-selection();
            DomainState.set-last-domain-id(root.domain-state-real-last);
            root.open = false;
            selection-made();
        }
    }

    function activate-open() {
        self.domain-state-real-last = DomainState.last-domain-id;
        ComboBoxState.title = self.title;
        ComboBoxState.current-value = BackendLib.string_list_contains(self.model, self.current-value) ? root.current-value : self.model[0];
        ComboBoxState.set-focus-coords(self.absolute-position.x, self.absolute-position.y, self.width, self.height);
        ComboBoxState.set-model(self.model);
        ComboBoxState.show-selection-box();
        self.open = true;
    }

    i-arrow := Rectangle {
        y: root.height / 2 - self.height / 2;
        x: root.width - self.width - (root.height - self.height) / 2;
        width: GlobalSizing.combobox-arrow;
        height: self.width;

        Path {
            fill: grey.brighter(25%);
            viewbox-height: parent.height / 1px;
            viewbox-width: parent.width / 1px;

            MoveTo {
                x: 0;
                y: 0;
            }

            LineTo {
                x: parent.viewbox-width / 2;
                y: parent.viewbox-height;
            }

            LineTo {
                x: parent.viewbox-width;
                y: 0;
            }
        }
    }
}

export component SliderSelectionBox inherits SelectionDomain {
    private property <float> range: abs(SliderState.range-end - SliderState.range-start);
    private property <int> int-range: ceil(range / SliderState.step);

    i-has-domain: SliderState.visible;
    force-exit-strategy: range == 0 ? true : false;
    title: SliderState.title;

    pure function get-range-index(i: int) -> float {
        SliderState.range-start + i * sign(SliderState.range-end - SliderState.range-start) * SliderState.step
    }

    i-background-bar := Rectangle {
        width: 900px;
        height: 8px;
        background: gray.darker(95%);
        border-radius: 3px;

        i-filler-bar := Rectangle {
            background: teal.darker(50%);
            border-radius: i-background-bar.border-radius;

            Rectangle {
                x: parent.width - self.width / 2;
                height: i-background-bar.height + abs(i-selector-layout.padding-top) * 2;
                width: self.height;
                background: i-filler-bar.background.brighter(85%);
                border-radius: i-background-bar.border-radius;
            }
        }

        i-selector-layout := HorizontalLayout {
            width: 100%;
            padding-top: -5px;
            padding-bottom: self.padding-top;
            alignment: LayoutAlignment.space-between;

            for _[i] in int-range: VerticalLayout {
                property <length> selection-x: self.x;

                alignment: center;

                Rectangle {
                    height: 0;
                    width: 0;

                    Button {
                        private property <float> value: get-range-index(i);

                        height: i-background-bar.height + abs(i-selector-layout.padding-top) * 2;
                        width: self.height;
                        background: transparent;

                        Text {
                            y: parent.height + 10px + (parent.has-focus ? 3px + FocusState.focus-highlight-size : 0px);
                            color: parent.has-focus ? white : i-background-bar.background;
                            text: value;
                            font-size: parent.has-focus ? 22px : 17.5px;

                            animate y, color, font-size { duration: GlobalAnimation.standard-duration; }
                        }

                        init-ready => {
                            if i == 0 {
                                root.first-model-focus-id = self.focus-id;
                            }
                            if i == (int-range - 1) {
                                root.last-model-focus-id = self.focus-id;
                            }
                            if SliderState.current-value == self.value {
                                root.i-init-selection-box-focus = self.focus-id;
                                i-filler-bar.width = selection-x;
                            }
                        }

                        activated => {
                            SliderState.domain-id = root.domain-id;
                            SliderState.make-selection(self.value, i);
                        }
                    }
                }
            }
        }
    }
}

export component Slider inherits Button {
    in-out property <float> current-value;

    in property <string> title;
    in property <float> range-end: 100;
    in property <float> range-start: 0;
    in property <int> step: 1;

    out property <bool> open;

    private property <bool> selection-state-made: SliderState.selection-made;
    private property <int> domain-state-real-last;

    width: GlobalSizing.slider-width;
    text: current-value;
    horizontal-alignment: left;

    changed selection-state-made => {
        if open {
            root.current-value = SliderState.selection-value;
            SliderState.complete-selection();
            DomainState.set-last-domain-id(root.domain-state-real-last);
            root.open = false;
        }
    }

    function activate-open() {
        root.domain-state-real-last = DomainState.last-domain-id;
        SliderState.title = root.title;
        SliderState.current-value = root.current-value;
        SliderState.set-focus-coords(self.absolute-position.x, self.absolute-position.y, self.width, self.height);
        SliderState.set-value-range(self.range-start, self.range-end, self.step);
        SliderState.show-selection-box();
        root.open = true;
    }

    activated => activate-open();
}

component NotificationCore {
    in property <duration> stay-duration: 2s;
    in property <bool> notify-on-init: true;
    in property <bool> interruptible: true;
    in property <bool> persistent: false;

    out property <bool> showing: persistent || i-timer.running;

    callback __i-show();
    callback __i-hide();

    function update() {
        if self.showing {
            __i-show();
        } else {
            __i-hide();
        }
    }

    changed showing => {
        self.update();
    }

    public function restart() {
        i-timer.start();
        i-timer.restart();
    }

    public function interrupt() {
        if interruptible {
            i-timer.stop();
        }
    }

    init => {
        if self.notify-on-init {
            self.restart();
        }
        self.update();
    }

    i-timer := Timer {
        interval: root.stay-duration;
        running: false;

        triggered => {
            self.stop();
        }
    }

    @children
}

export component ToggleBox inherits Button {
    in property <bool> var;
    in property <bool> force-accessible-enaled: false;

    private property <bool> accessible-mode: force-accessible-enaled || AccessibilitySettings.accessible-switches;
    private property <length> switch-padding: 2px;
    private property <length> i-x <=> i-switch.x;

    background: (accessible-mode || !var) ? grey.darker(80%) : (self.locked ? green.mix(black, 75%) : green);
    width: self.height * 2;
    clip: true;

    animate i-x, background { duration: GlobalAnimation.toggle-box-switch-duration; }

    callback toggled(bool);

    activated => toggled(!var);

    i-switch := Rectangle {
        border-radius: 3px;
        background: root.locked ? lightgray.mix(black, 70%) : lightgray;
        x: var ? root.width - root.border-width - root.switch-padding - self.width : root.border-width + root.switch-padding;
        y: root.height / 2 - self.height / 2;
        height: root.height - root.switch-padding * 2 - root.border-width * 2;
        width: self.height;

        if accessible-mode: Rectangle {
            off-indicator := Rectangle {
                x: parent.width - self.width - on-indicator.x;
                width: on-indicator.width;
                height: self.width;
                background: transparent;

                Rectangle {
                    width: 150%;
                    height: 150%;
                    border-radius: self.height / 2;
                    border-width: 2px;
                    border-color: root.locked ? red.mix(black, 75%) : red;
                }
            }

            on-indicator := Rectangle {
                visible: true;
                x: -(root.width - parent.width) / 2 - root.switch-padding / 2;
                width: 10px;
                height: root.height * 40%;

                Rectangle {
                    height: 100%;
                    width: 3px;
                    background: root.locked ? limegreen.mix(black, 75%) : limegreen;
                }

                background: transparent;
            }
        }
    }
}

export component Notification inherits NotificationCore {
    i-container := Button {
        width: 100%;
        height: 100%;
        clip: true;
        opacity: root.showing ? 1 : 0;

        changed opacity => {
            if self.opacity == 0 {
                self.visible = false;
            } else {
                self.visible = true;
            }
        }

        animate opacity {
            duration: GlobalAnimation.notification-duration;
            easing: Easing.ease-in-out-quad;
        }

        activated => root.interrupt();

        @children
    }
}

export component NotificationPopup inherits NotificationCore {
    __i-show => {
        i-popup.show();
    }

    i-popup := PopupWindow {
        width <=> root.width;
        height <=> root.height;
        close-policy: no-auto-close;

        i-container := Rectangle {
            width: 100%;
            height: 100%;
            clip: true;
            background: darkkhaki;
            opacity: root.showing ? 1 : 0;

            changed opacity => {
                if self.opacity == 0 {
                    i-popup.close();
                }
            }

            animate opacity {
                duration: GlobalAnimation.notification-duration;
                easing: Easing.ease-in-out-quad;
            }

            @children
        }
    }
}

export component TestComponentSuite inherits VerticalLayout {
    spacing: 10px;

    HorizontalLayout {
        Text {
            text: "Testing ComboBox";
        }

        ComboBox {
            title: "Testing ComboBox";
            current-index: 0;
            model: ["test1", "test2", "test3"];
        }
    }

    HorizontalLayout {
        Text {
            text: "Testing Button";
        }

        Button {
            property <int> var: 0;
            text: "Button " + var;
            activated => {
                var += 1;
            }
        }
    }

    HorizontalLayout {
        Text {
            text: "Testing ToggleBox";
        }

        ToggleBox {
            var: false;
            toggled => {
                self.var = !self.var;
            }
        }
    }

    HorizontalLayout {
        Text {
            text: "Testing Accessible ToggleBox";
        }

        ToggleBox {
            var: false;
            force-accessible-enaled: true;
            toggled => {
                self.var = !self.var;
            }
        }
    }

    HorizontalLayout {
        Text {
            text: "Testing Slider";
        }

        Slider {
            title: "Testing Slider";
        }
    }

    HorizontalLayout {
        Text {
            text: "Testing Label";
        }

        Label {
            text: "lang.test";
        }
    }
}

export component ModuleDebug inherits VerticalLayout {
    Text {
        color: purple;
        text: "FocusState";
    }

    Text {
        color: white;
        text: FocusState.num-focuses;
    }

    Text {
        color: white;
        text: FocusState.current-focus-id;
    }

    Text {
        color: white;
        text: FocusState.last-focus-id;
    }

    Text {
        color: white;
        text: "pos {" + FocusState.focus-box.x / 1px + ", " + FocusState.focus-box.y / 1px + "}";
    }

    Text {
        color: white;
        text: "size {" + FocusState.focus-box.width / 1px + ", " + FocusState.focus-box.height / 1px + "}";
    }

    Text {
        color: white;
        text: FocusState.force-focus-id + ": " + (FocusState.attempting-force-focus ? "true" : "false");
    }

    Text {
        color: orange;
        text: FocusState.failed-forces;
    }

    Text {
        color: purple;
        text: "DomainState";
    }

    Text {
        color: white;
        text: DomainState.num-domains;
    }

    Text {
        color: white;
        text: DomainState.current-domain-id;
    }

    Text {
        color: white;
        text: DomainState.last-domain-id;
    }

    Text {
        color: white;
        text: "pos {" + DomainState.focus-box.x / 1px + ", " + DomainState.focus-box.y / 1px + "}";
    }

    Text {
        color: white;
        text: "size {" + DomainState.focus-box.width / 1px + ", " + DomainState.focus-box.height / 1px + "}";
    }

    Text {
        color: red;
        text: DomainState.navigation-errors;
    }

    Text {
        color: purple;
        text: "ComboBoxState";
    }

    Text {
        color: white;
        text: ComboBoxState.visible ? "visible" : "hidden";
    }

    Text {
        color: white;
        text: ComboBoxState.domain-id;
    }

    Text {
        color: purple;
        text: "SliderState";
    }

    Text {
        color: white;
        text: SliderState.visible ? "visible" : "hidden";
    }

    Text {
        color: white;
        text: SliderState.domain-id;
    }
}
