export global BevyTextureGlobal {
    in property <image> texture;
    in-out property <length> requested-texture-width;
    in-out property <length> requested-texture-height;
}

export component BevyTextureWidget inherits Rectangle {

    i-texture := Image {
        source: BevyTextureGlobal.texture;
        image-fit: fill;
        width: 100%;
        height: 100%;
        preferred-width: self.source.width * 1px;
        preferred-height: self.source.height * 1px;

        changed width => {
            BevyTextureGlobal.requested-texture-width = self.width
        }
        changed height => {
            BevyTextureGlobal.requested-texture-height = self.height
        }
    }
}
