import {
    Button,
    FocusDomain,
    ComboBox,
    ToggleBox,
    DebugHighlight,
    FocusState,
} from "@lib/core.slint";
import {
    ApplicationState,
    AccessibilitySettings,
    DebugSettings,
    GeneralSettings,
} from "@lib/state.slint";
import { SUnitSystem } from "@lib/units.slint";
import { GlobalThemeData } from "@themes/themes.slint";

export enum SettingsMenuItemType {
    Parameter,
    ReadOnlyParameter,
    Page,
    PageEnd,
}

export struct SettingsMenuItem {
    name: string,
    param-path: string,
    param-type: string,
    item-type: SettingsMenuItemType,
}

export global SettingsLayout {
    // TODO: can be changed to not be a flat array by just returning page contents from the callback
    in property <[SettingsMenuItem]> layout;

    callback get-page-layout();
    callback set-by-path(path: string, val: string);
    callback get-by-path(path: string) -> string;
}

component DecorationBar inherits Rectangle {
    height: 2px;
    background: white;
    width: 100%;
}

component SettingBarLabelTextBase inherits Text {
    font-size: 20px;
    color: white;
    horizontal-alignment: left;
    vertical-alignment: center;
}

component SettingBarLabelTextAnimated inherits SettingBarLabelTextBase {
    animate x { duration: 50ms; }
}

component SettingBarLabelText {
    in property <length> i-x;
    in property <string> text;
    if AccessibilitySettings.animations-enabled: SettingBarLabelTextAnimated {
        x: root.i-x;
        text: root.text;
    }
    if !AccessibilitySettings.animations-enabled: SettingBarLabelTextBase {
        x: root.i-x;
        text: root.text;
    }
}

component SettingsBarLabelBase {
    in property <string> text <=> i-label.text;
    in property <bool> has-focus: false;
    in-out property <length> selector-x: has-focus ? 6px : 0;

    i-selection-indicator := Rectangle {
        x: 0;
        width: root.selector-x;
        height: 6px;
        border-radius: 2px;
        background: white;
    }

    i-label := SettingBarLabelText {
        x: 0;
        i-x: root.has-focus ? 15px : 0;
    }
}

component SettingsBarLabelBaseAnimated inherits SettingsBarLabelBase {
    animate selector-x { duration: 50ms; }
}

component SettingBarLabel inherits Rectangle {
    in property <string> text;
    in property <bool> has-focus: false;

    if AccessibilitySettings.animations-enabled: SettingsBarLabelBaseAnimated {
        x: 0;
        text: root.text;
        has-focus: root.has-focus;
    }
    if !AccessibilitySettings.animations-enabled: SettingsBarLabelBase {
        x: 0;
        text: root.text;
        has-focus: root.has-focus;
    }

    DebugHighlight { }
}

component SettingBarBackgroundBase inherits Rectangle {
    in property <bool> has-focus;

    border-radius: 6px;
    background: has-focus ? white.transparentize(90%) : transparent;
}

component SettingBarBackgroundBaseAnimated inherits SettingBarBackgroundBase {
    animate background { duration: 50ms; }
}

component SettingBarBackground inherits Rectangle {
    in property <bool> has-focus;

    if !AccessibilitySettings.animations-enabled: SettingBarBackgroundBase {
        has-focus: root.has-focus;
    }
    if AccessibilitySettings.animations-enabled: SettingBarBackgroundBaseAnimated {
        has-focus: root.has-focus;
    }
}

component SettingBar inherits Rectangle {
    in property <string> label <=> i-label.text;
    in property <bool> has-focus: FocusState.current-focus-id == self.focus-id;
    in property <int> focus-id;

    property <length> i-padding: 15px;

    width: 550px;

    SettingBarBackground {
        has-focus: root.has-focus;
    }

    VerticalLayout {
        alignment: center;
        padding: i-padding;

        HorizontalLayout {
            i-label := SettingBarLabel {
                has-focus: root.has-focus;
            }

            i-container := Rectangle {
                DebugHighlight {
                    background: blue;
                }

                HorizontalLayout {
                    spacing: 5px;
                    alignment: end;

                    @children
                }
            }
        }
    }

    DebugHighlight {
        background: yellow;
    }
}

component TypedSettingBar inherits SettingBar {
    in property <string> param-type;
    in property <string> param-path;

    if DebugSettings.debug-mode && DebugSettings.extra-debug-info: VerticalLayout {
        Text {
            text: param-type;
            horizontal-alignment: TextHorizontalAlignment.right;
        }

        Text {
            text: param-path;
            horizontal-alignment: TextHorizontalAlignment.right;
        }
    }

    if param-type == "bool": ToggleBox {
        var: false;

        init => {
            // TODO: make lib function to get string value of Rust types instead of hard-coding
            root.focus-id = self.focus-id;
            self.var = SettingsLayout.get-by-path(param-path) == "true" ? true : false;
        }

        toggled => {
            self.var = !self.var;
            SettingsLayout.set-by-path(param-path, self.var ? "true" : "false");
        }
    }

    if param-type == "UnitSystem": ComboBox {
        title: root.label;
        // TODO: make lib function to get all enum options from Rust
        model: ["USCS", "SI"];

        init => {
            root.focus-id = self.focus-id;
            self.current-value = SettingsLayout.get-by-path(param-path);
        }

        changed current-value => {
            SettingsLayout.set-by-path(param-path, self.current-value);
        }
    }
}

component SettingsMenuLayoutComponent inherits VerticalLayout {
    alignment: center;
    spacing: 2px;

    out property <int> first-focus-id: -1;
    out property <int> last-focus-id;

    init => {
        SettingsLayout.get-page-layout();
    }

    for item[i] in SettingsLayout.layout: HorizontalLayout {
        alignment: center;

        function update-focus-ids(id: int) {
            if i == 0 {
                root.first-focus-id = id;
            } else if i == (SettingsLayout.layout.length - 1) {
                root.last-focus-id = id;
            }
        }

        if (item.item-type == SettingsMenuItemType.Parameter) || (item.item-type == SettingsMenuItemType.ReadOnlyParameter): TypedSettingBar {
            label: item.name;
            param-path: item.param-path;
            param-type: item.param-type;

            init => update-focus-ids(self.focus-id);
        }
        // TODO: add pages
        // if item.item-type == SettingsMenuItemType.Page: SettingBar {
        //     label: item.name;

        //     init => update-focus-ids(self.focus-id);
        // }
        if item.item-type == SettingsMenuItemType.Page: DecorationBar { }
        // if item.item-type == SettingsMenuItemType.PageEnd: DecorationBar { }
    }
}

export component SettingsMenu inherits FocusDomain {
    force-exit-strategy: false;
    width: 2400px;
    height: 900px;

    nav-front-forward => FocusState.force-focus(layout.first-focus-id);
    nav-end-backward => exit-button.focus();

    HorizontalLayout {
        alignment: center;

        VerticalLayout {
            alignment: center;
            spacing: 10px;

            layout := SettingsMenuLayoutComponent { }

            HorizontalLayout {
                alignment: parent.alignment;

                exit-button := Button {
                    text: "Exit";

                    activated => {
                        ApplicationState.settings-menu-visible = false;
                    }
                }
            }
        }
    }
}
