import {
    Button,
    FocusDomain,
    ComboBox,
    ToggleBox,
    DebugHighlight,
    FocusState,
} from "@lib/core.slint";
import { RSTypeResolver } from "@lib/rs.slint";
import { SBoundInt } from "@data/data_parameter.slint";
import {
    ApplicationState,
    AccessibilitySettings,
    DebugSettings,
    GeneralSettings,
} from "@lib/state.slint";
import { SUnitSystem } from "@lib/units.slint";
import { GlobalThemeData } from "@themes/theme_loader_gen.slint";
import {
    ControlledFocusScope,
    Label,
    GlobalAnimation,
    Slider,
} from "../lib/core.slint";

export enum SettingsMenuItemType {
    Parameter,
    ReadOnlyParameter,
    Page,
    PageBack,
    PageTitle,
}

export enum DerivedParamType {
    Enum,
    BoundInt,
    Number,
    String,
    Bool,
    Page,
    Trigger,
}

@rust-attr(derive(strum::VariantArray, serde::Serialize, serde::Deserialize))
export enum SettingsSpecialPages {
    Attributions,
}

export struct SettingsMenuItem {
    name: string,
    param-path: string,
    param-type: string,
    param-type-derived: DerivedParamType,
    item-type: SettingsMenuItemType,
}

export global SettingsLayout {
    pure callback get-page-layout(path: string) -> [SettingsMenuItem];
    pure callback get-page-parent(path: string) -> string;
    pure callback get-by-path(path: string) -> string;
    pure callback stringify-derived-param-type(ty: DerivedParamType) -> string;
    pure callback get-bound-int(path: string) -> SBoundInt;

    callback set-by-path(path: string, val: string);
}

component DecorationBar inherits Rectangle {
    height: 2px;
    background: white;
    width: 100%;
}

component SettingBarLabel inherits Rectangle {
    in property <string> text <=> i-label.text;
    in property <bool> has-focus: false;

    private property <length> selector-x: self.has-focus ? 6px : 0;
    private property <length> label-x: self.has-focus ? 15px : 0;

    animate selector-x, label-x { duration: GlobalAnimation.standard-duration; }

    i-selection-indicator := Rectangle {
        x: 0;
        width: root.selector-x;
        height: 6px;
        border-radius: 3px;
        background: white;
    }

    i-label := Label {
        x: label-x;
        font-size: 20px;
        horizontal-alignment: left;
        vertical-alignment: center;
    }

    DebugHighlight { }
}

component SettingBar inherits Rectangle {
    in-out property <int> focus-id;

    in property <string> label <=> i-label.text;
    in property <bool> has-focus: FocusState.current-focus-id == self.focus-id;

    private property <length> i-padding: 15px;

    background: root.has-focus ? white.transparentize(90%) : transparent;
    border-radius: 6px;
    width: 600px;

    animate background { duration: GlobalAnimation.standard-duration; }

    VerticalLayout {
        alignment: center;
        padding: i-padding;

        HorizontalLayout {
            i-label := SettingBarLabel {
                has-focus: root.has-focus;
            }

            i-container := Rectangle {
                DebugHighlight {
                    background: blue;
                }

                HorizontalLayout {
                    spacing: 5px;
                    alignment: end;

                    @children
                }
            }
        }
    }

    DebugHighlight {
        background: yellow;
    }
}

component TypedSettingBar inherits SettingBar {
    in property <SettingsMenuItem> item;

    private property <bool> update-displayed-value: false;
    private property <bool> readonly: item.item-type == SettingsMenuItemType.ReadOnlyParameter;

    label: item.param-path;

    callback activated();

    if item.item-type == SettingsMenuItemType.ReadOnlyParameter: Rectangle {
        width: 0;
        height: 0;
        visible: false;

        Timer {
            interval: 25ms;
            running: true;
            triggered => {
                update-displayed-value = !update-displayed-value
            }
        }
    }

    if DebugSettings.debug-mode && DebugSettings.extra-debug-info: VerticalLayout {
        Text {
            color: tan;
            text: (readonly ? "readonly " : "") + SettingsLayout.stringify-derived-param-type(item.param-type-derived);
            horizontal-alignment: TextHorizontalAlignment.right;
        }

        Text {
            color: tan;
            text: item.param-type;
            horizontal-alignment: TextHorizontalAlignment.right;
        }

        Text {
            color: tan;
            text: item.param-path;
            horizontal-alignment: TextHorizontalAlignment.right;
        }
    }

    if item.param-type-derived == DerivedParamType.Bool: ToggleBox {
        locked: root.readonly;
        var: RSTypeResolver.rs-string-bool(SettingsLayout.get-by-path(item.param-path));

        private property <bool> update: root.update-displayed-value;

        init-ready => {
            root.focus-id = self.focus-id;
        }

        toggled => {
            self.var = !self.var;
            SettingsLayout.set-by-path(item.param-path, RSTypeResolver.sl-bool-string(self.var));
            root.activated();
        }

        changed update => {
            self.var = RSTypeResolver.rs-string-bool(SettingsLayout.get-by-path(item.param-path));
        }
    }

    if item.param-type-derived == DerivedParamType.Enum: ComboBox {
        locked: root.readonly;
        title: root.label;
        model: RSTypeResolver.get-enum-variants(item.param-type);
        current-value: SettingsLayout.get-by-path(item.param-path);

        private property <bool> update: root.update-displayed-value;

        init-ready => {
            root.focus-id = self.focus-id;
        }

        selection-made => {
            SettingsLayout.set-by-path(item.param-path, self.current-value);
            root.activated();
        }

        changed update => {
            self.current-value = SettingsLayout.get-by-path(item.param-path);
        }
    }

    if item.param-type-derived == DerivedParamType.BoundInt: Slider {
        locked: root.readonly;
        title: root.label;
        current-value: bound.value;
        range-end: bound.end + 1;
        range-start: bound.start;
        step: 1; // TODO: add step to ranges

        private property <SBoundInt> bound: SettingsLayout.get-bound-int(item.param-path);
        private property <bool> update: root.update-displayed-value;

        init-ready => {
            self.bound = SettingsLayout.get-bound-int(item.param-path);
            root.focus-id = self.focus-id;
        }

        changed current-value => {
            self.bound.value = self.current-value;
            SettingsLayout.set-by-path(item.param-path, RSTypeResolver.sboundint-to-string(self.bound));
            self.update = !update;
        }

        changed update => {
            self.bound = SettingsLayout.get-bound-int(item.param-path);
        }
    }

    if (item.param-type-derived == DerivedParamType.Trigger) && (item.param-type == "PageTrigger"): Button {
        width: self.height;
        text: ">";

        init-ready => {
            root.focus-id = self.focus-id;
        }

        activated => {
            // TODO: page trigger
            debug("TODO: page trigger")
        }
    }

    // TODO: currently setting numbers & strings is not implemented
    if (item.param-type-derived == DerivedParamType.Number) || (item.param-type-derived == DerivedParamType.String): Button {
        width: 150px;
        locked: root.readonly;
        text: SettingsLayout.get-by-path(item.param-path);
        horizontal-alignment: TextHorizontalAlignment.right;

        private property <bool> update: root.update-displayed-value;

        init-ready => {
            root.focus-id = self.focus-id;
        }

        changed update => {
            self.text = SettingsLayout.get-by-path(item.param-path);
        }
    }

    if (item.item-type == SettingsMenuItemType.Page) || (item.item-type == SettingsMenuItemType.PageBack): Button {
        width: self.height;
        text: (item.item-type == SettingsMenuItemType.Page) ? ">" : "<";

        init-ready => {
            root.focus-id = self.focus-id;
        }

        activated => root.activated();
    }
}

component SettingsMenuLayoutComponent inherits VerticalLayout {
    alignment: center;
    spacing: 2px;

    out property <int> first-focus-id: -1;
    out property <int> last-focus-id;

    property <[SettingsMenuItem]> items;
    property <string> path: "Config";
    property <string> parent-path: "Config";

    function update-layout() {
        self.items = SettingsLayout.get-page-layout(self.path);
        self.parent-path = SettingsLayout.get-page-parent(self.path);
        FocusState.force-focus(self.first-focus-id);
    }

    init => update-layout();

    HorizontalLayout {
        VerticalLayout {
            spacing: 12px;

            page-title := TypedSettingBar {
                label: path;
                item: {
                    name: path,
                    param-path: root.path,
                    item-type: SettingsMenuItemType.PageTitle,
                    param-type-derived: DerivedParamType.Page,
                };
            }

            DecorationBar { }
        }
    }

    for item[i] in root.items: HorizontalLayout {
        alignment: center;

        function update-focus-ids(id: int) {
            if i == 0 {
                root.first-focus-id = id;
            }
        }

        if (item.item-type == SettingsMenuItemType.Parameter) || (item.item-type == SettingsMenuItemType.ReadOnlyParameter): TypedSettingBar {
            item: item;

            changed focus-id => update-focus-ids(self.focus-id);
        }
        if item.item-type == SettingsMenuItemType.Page: TypedSettingBar {
            item: item;

            changed focus-id => update-focus-ids(self.focus-id);

            activated => {
                root.path = item.param-path;
                root.update-layout();
            }
        }
    }

    page-back := TypedSettingBar {
        label: "Back";

        item: {
            name: "Back",
            param-path: root.path,
            item-type: SettingsMenuItemType.PageBack,
            param-type-derived: DerivedParamType.Page,
        };

        changed focus-id => {
            root.last-focus-id = self.focus-id;
        }

        activated => {
            if (path == "") || (path == "Config") {
                ApplicationState.settings-menu-visible = false;
            } else {
                root.path = root.parent-path;
            }

            root.update-layout();
        }
    }
}

export component SettingsMenu inherits FocusDomain {
    force-exit-strategy: false;
    width: 2400px;
    height: 900px;

    nav-front-forward => FocusState.force-focus(layout.first-focus-id);
    nav-end-backward => FocusState.force-focus(layout.last-focus-id);

    if DebugSettings.debug-mode && DebugSettings.extra-debug-info: VerticalLayout {
        x: root.width - self.width;
        y: root.height - self.height;
        alignment: end;

        Text {
            color: white;
            text: layout.first-focus-id;
        }

        Text {
            color: white;
            text: layout.last-focus-id;
        }
    }

    HorizontalLayout {
        alignment: center;

        layout := SettingsMenuLayoutComponent {
            changed first-focus-id => {
                root.focus();
            }
        }
    }
}
