import {
    Button,
    FocusDomain,
    ComboBox,
    ToggleBox,
    DebugHighlight,
    FocusState,
} from "@lib/core.slint";
import { RSTypeResolver } from "@lib/rs.slint";
import {
    ApplicationState,
    AccessibilitySettings,
    DebugSettings,
    GeneralSettings,
} from "@lib/state.slint";
import { SUnitSystem } from "@lib/units.slint";
import { GlobalThemeData } from "@themes/theme_loader_gen.slint";
import { ControlledFocusScope } from "../lib/core.slint";

export enum SettingsMenuItemType {
    Parameter,
    ReadOnlyParameter,
    Page,
    PageBack,
    PageTitle,
}

export enum DerivedParamType {
    Enum,
    BoundNumber,
    Number,
    String,
    Bool,
    Page,
}

export struct SettingsMenuItem {
    name: string,
    param-path: string,
    param-type: string,
    param-type-derived: DerivedParamType,
    item-type: SettingsMenuItemType,
}

export global SettingsLayout {
    // TODO: can be changed to not be a flat array by just returning page contents from the callback
    in property <[SettingsMenuItem]> layout;

    callback get-page-layout(path: string) -> [SettingsMenuItem];
    callback get-page-parent(path: string) -> string;
    callback set-by-path(path: string, val: string);
    pure callback get-by-path(path: string) -> string;

    public pure function stringify-derived-param-type(ty: DerivedParamType) -> string {
        if ty == DerivedParamType.Enum {
            "enum"
        } else if ty == DerivedParamType.BoundNumber {
            "boundNumber"
        } else if ty == DerivedParamType.Number {
            "number"
        } else if ty == DerivedParamType.String {
            "string"
        } else if ty == DerivedParamType.Bool {
            "bool"
        } else if ty == DerivedParamType.Page {
            "page"
        } else {
            "unknown"
        }
    }
}

component DecorationBar inherits Rectangle {
    height: 2px;
    background: white;
    width: 100%;
}

component SettingBarLabelTextBase inherits Text {
    font-size: 20px;
    color: white;
    horizontal-alignment: left;
    vertical-alignment: center;
}

component SettingBarLabelTextAnimated inherits SettingBarLabelTextBase {
    animate x { duration: 50ms; }
}

component SettingBarLabelText {
    in property <length> i-x;
    in property <string> text;
    if AccessibilitySettings.animations-enabled: SettingBarLabelTextAnimated {
        x: root.i-x;
        text: root.text;
    }
    if !AccessibilitySettings.animations-enabled: SettingBarLabelTextBase {
        x: root.i-x;
        text: root.text;
    }
}

component SettingsBarLabelBase {
    in property <string> text <=> i-label.text;
    in property <bool> has-focus: false;
    in-out property <length> selector-x: has-focus ? 6px : 0;

    i-selection-indicator := Rectangle {
        x: 0;
        width: root.selector-x;
        height: 6px;
        border-radius: 2px;
        background: white;
    }

    i-label := SettingBarLabelText {
        x: 0;
        i-x: root.has-focus ? 15px : 0;
    }
}

component SettingsBarLabelBaseAnimated inherits SettingsBarLabelBase {
    animate selector-x { duration: 50ms; }
}

component SettingBarLabel inherits Rectangle {
    in property <string> text;
    in property <bool> has-focus: false;

    if AccessibilitySettings.animations-enabled: SettingsBarLabelBaseAnimated {
        x: 0;
        text: root.text;
        has-focus: root.has-focus;
    }
    if !AccessibilitySettings.animations-enabled: SettingsBarLabelBase {
        x: 0;
        text: root.text;
        has-focus: root.has-focus;
    }

    DebugHighlight { }
}

component SettingBarBackgroundBase inherits Rectangle {
    in property <bool> has-focus;

    border-radius: 6px;
    background: has-focus ? white.transparentize(90%) : transparent;
}

component SettingBarBackgroundBaseAnimated inherits SettingBarBackgroundBase {
    animate background { duration: 50ms; }
}

component SettingBarBackground inherits Rectangle {
    in property <bool> has-focus;

    if !AccessibilitySettings.animations-enabled: SettingBarBackgroundBase {
        has-focus: root.has-focus;
    }
    if AccessibilitySettings.animations-enabled: SettingBarBackgroundBaseAnimated {
        has-focus: root.has-focus;
    }
}

component SettingBar inherits Rectangle {
    in property <string> label <=> i-label.text;
    in property <bool> has-focus: FocusState.current-focus-id == self.focus-id;
    in-out property <int> focus-id;

    property <length> i-padding: 15px;

    width: 600px;

    SettingBarBackground {
        has-focus: root.has-focus;
    }

    VerticalLayout {
        alignment: center;
        padding: i-padding;

        HorizontalLayout {
            i-label := SettingBarLabel {
                has-focus: root.has-focus;
            }

            i-container := Rectangle {
                DebugHighlight {
                    background: blue;
                }

                HorizontalLayout {
                    spacing: 5px;
                    alignment: end;

                    @children
                }
            }
        }
    }

    DebugHighlight {
        background: yellow;
    }
}

component TypedSettingBar inherits SettingBar {
    in property <SettingsMenuItem> item;
    private property <bool> update-displayed-value: false;
    private property <bool> readonly: item.item-type == SettingsMenuItemType.ReadOnlyParameter;

    callback activated();

    if item.item-type == SettingsMenuItemType.ReadOnlyParameter: Rectangle {
        width: 0;
        height: 0;
        visible: false;

        Timer {
            interval: 25ms;
            running: true;
            triggered => {
                update-displayed-value = !update-displayed-value
            }
        }
    }

    if DebugSettings.debug-mode && DebugSettings.extra-debug-info: VerticalLayout {
        Text {
            color: tan;
            text: (readonly ? "readonly " : "") + SettingsLayout.stringify-derived-param-type(item.param-type-derived);
            horizontal-alignment: TextHorizontalAlignment.right;
        }

        Text {
            color: tan;
            text: item.param-type;
            horizontal-alignment: TextHorizontalAlignment.right;
        }

        Text {
            color: tan;
            text: item.param-path;
            horizontal-alignment: TextHorizontalAlignment.right;
        }
    }

    if item.param-type-derived == DerivedParamType.Bool: ToggleBox {
        locked: root.readonly;
        var: RSTypeResolver.rs-string-bool(SettingsLayout.get-by-path(item.param-path));

        private property <bool> update: root.update-displayed-value;

        init-ready => {
            root.focus-id = self.focus-id;
        }

        toggled => {
            self.var = !self.var;
            SettingsLayout.set-by-path(item.param-path, RSTypeResolver.sl-bool-string(self.var));
            root.activated();
        }

        changed update => {
            self.var = RSTypeResolver.rs-string-bool(SettingsLayout.get-by-path(item.param-path));
        }
    }

    if item.param-type-derived == DerivedParamType.Enum: ComboBox {
        locked: root.readonly;
        title: root.label;
        model: RSTypeResolver.get-enum-variants(item.param-type);
        current-value: SettingsLayout.get-by-path(item.param-path);

        private property <bool> update: root.update-displayed-value;

        init-ready => {
            root.focus-id = self.focus-id;
        }

        selection-made => {
            SettingsLayout.set-by-path(item.param-path, self.current-value);
            root.activated();
        }

        changed update => {
            self.current-value = SettingsLayout.get-by-path(item.param-path);
        }
    }

    // TODO: currently setting numbers & strings is not implemented
    if (item.param-type-derived == DerivedParamType.Number) || (item.param-type-derived == DerivedParamType.String): Button {
        locked: root.readonly;
        text: SettingsLayout.get-by-path(item.param-path);
        text-alignment: TextHorizontalAlignment.right;

        private property <bool> update: root.update-displayed-value;

        init-ready => {
            root.focus-id = self.focus-id;
        }

        changed update => {
            self.text = SettingsLayout.get-by-path(item.param-path);
        }
    }

    // TODO: bound numbers

    if (item.item-type == SettingsMenuItemType.Page) || (item.item-type == SettingsMenuItemType.PageBack): Button {
        width: self.height;
        text: (item.item-type == SettingsMenuItemType.Page) ? ">" : "<";

        init-ready => {
            root.focus-id = self.focus-id;
        }

        activated => root.activated();
    }
}

component SettingsMenuLayoutComponent inherits VerticalLayout {
    alignment: center;
    spacing: 2px;

    out property <int> first-focus-id: -1;
    out property <int> last-focus-id;

    property <[SettingsMenuItem]> items;
    property <string> path: "Config";
    property <string> parent-path: "Config";

    function update-layout() {
        self.items = SettingsLayout.get-page-layout(self.path);
        self.parent-path = SettingsLayout.get-page-parent(self.path);
        FocusState.force-focus(self.first-focus-id);
    }

    init => update-layout();

    HorizontalLayout {
        VerticalLayout {
            page-title := TypedSettingBar {
                label: path;
                item: {
                    name: path,
                    param-path: root.path,
                    item-type: SettingsMenuItemType.PageTitle,
                    param-type-derived: DerivedParamType.Page,
                };
            }

            DecorationBar { }
        }
    }

    for item[i] in root.items: HorizontalLayout {
        alignment: center;

        function update-focus-ids(id: int) {
            if i == 0 {
                root.first-focus-id = id;
            }
        }

        if (item.item-type == SettingsMenuItemType.Parameter) || (item.item-type == SettingsMenuItemType.ReadOnlyParameter): TypedSettingBar {
            label: item.name;
            item: item;

            changed focus-id => update-focus-ids(self.focus-id);
        }
        if item.item-type == SettingsMenuItemType.Page: TypedSettingBar {
            label: item.name;
            item: item;

            changed focus-id => update-focus-ids(self.focus-id);

            activated => {
                root.path = item.param-path;
                root.update-layout();
            }
        }
    }

    page-back := TypedSettingBar {
        label: "Back";

        item: {
            name: "Back",
            param-path: root.path,
            item-type: SettingsMenuItemType.PageBack,
            param-type-derived: DerivedParamType.Page,
        };

        changed focus-id => {
            root.last-focus-id = self.focus-id;
        }

        activated => {
            if (path == "") || (path == "Config") {
                ApplicationState.settings-menu-visible = false;
            } else {
                root.path = root.parent-path;
            }

            root.update-layout();
        }
    }
}

export component SettingsMenu inherits FocusDomain {
    force-exit-strategy: false;
    width: 2400px;
    height: 900px;

    nav-front-forward => FocusState.force-focus(layout.first-focus-id);
    nav-end-backward => FocusState.force-focus(layout.last-focus-id);

    if DebugSettings.debug-mode && DebugSettings.extra-debug-info: VerticalLayout {
        x: root.width - self.width;
        y: root.height - self.height;
        alignment: end;

        Text {
            color: white;
            text: layout.first-focus-id;
        }

        Text {
            color: white;
            text: layout.last-focus-id;
        }
    }

    HorizontalLayout {
        alignment: center;

        layout := SettingsMenuLayoutComponent {
            changed first-focus-id => {
                root.focus();
            }
        }
    }
}
