import { ScrollView } from "std-widgets.slint";

import {
    Button,
    ControlledFocusScope,
    FocusDomain,
    FocusState,
    Label,
} from "@lib/core.slint";
import { DebugMenuWidget, DebugMenuState } from "debug.slint";
import {
    RoadIndicatorWidget,
} from "@themes/default/components/road_indicators.slint";
import {
    ApplicationState,
    DebugSettings,
    GeneralSettings,
    AccessibilitySettings,
} from "@lib/state.slint";
import { CanDisplayWidget } from "@widgets/can_display.slint";
import { CarDisplayWidget } from "@widgets/car_display.slint";
import { BevyCarDisplayWidget } from "@widgets/bevy_car_display.slint";
import { GlobalAnimation, DebugHighlight } from "@lib/core.slint";

export global WidgetContainerState {
    in-out property <int> current-page: 0;
    in-out property <int> focused-page: -1; // -1 if not entered
    in-out property <int> num-pages: 0;
    in-out property <int> num-visible-pages: 0;

    public function change-page(to-page: int) {
        if to-page != current-page {
            current-page = to-page;
            self.exit-page();
        }
    }

    public function focus-page(to-page: int) {
        self.change-page(to-page);
        self.focused-page = self.current-page;
    }

    public function exit-page() {
        self.focused-page = -1;
    }

    callback reset();
    pure callback create-widget() -> int;
    pure callback get-page-number-of-id(id: int) -> int;
    pure callback set-widget-visible(id: int, bool);
    pure callback get-widget-visible(id: int) -> bool;
}

component Widget inherits FocusDomain {
    in-out property <bool> focusable: false;
    in property <image> icon: @image-url("@svg/abs-warning-light.svg");
    out property <int> page-number: WidgetContainerState.get-page-number-of-id(self.widget-id);
    out property <int> widget-id: WidgetContainerState.create-widget();
    out property <bool> has-target: WidgetContainerState.current-page == self.widget-id; // this widget is currently visible to the user
    out property <bool> has-focus: WidgetContainerState.focused-page == self.widget-id; // the user is currently interacting with this widget

    force-exit-strategy: self.focusable;
    force-focus: false;
    height: 100%;
    width: 100%;

    changed has-focus => {
        if focusable && has-focus {
            self.no-graceful-return = true;
            self.enter-domain();
        } else {
            WidgetContainerState.focused-page = -1;
        }
    }

    changed visible => WidgetContainerState.set-widget-visible(self.widget_id, self.visible);

    init => WidgetContainerState.set-widget-visible(self.widget_id, self.visible);
    exited => WidgetContainerState.exit-page();
}

component FocusableWidget inherits Widget {
    focusable: true;
}

export component WidgetContainer {
    width: 500px;
    height: 600px;
    forward-focus: center-widget-container-indicator;

    init => WidgetContainerState.reset();

    VerticalLayout {
        // TODO: add dynamic images
        center-widget-container-indicator := FocusDomain {
            property <length> indicator-width: self.height;

            height: 10%;
            force-exit-strategy: false;
            force-focus: true;

            nav-front-forward => WidgetContainerState.change-page(0);
            nav-end-backward => WidgetContainerState.change-page(WidgetContainerState.num-pages - 1);

            for i in WidgetContainerState.num-pages: Rectangle {
                private property <int> page-number: WidgetContainerState.get-page-number-of-id(i);
                private property <bool> has-view: WidgetContainerState.current-page == i;
                private property <bool> domain-active: center-widget-container-indicator.domain-active;
                private property <length> item-size: parent.height;
                private property <length> spacing: FocusState.focus-highlight-size;
                private property <length> total-width: WidgetContainerState.num-visible-pages * (item-size + spacing) - spacing;

                height: 100%;
                width: self.height;
                forward-focus: i-focus;
                visible: WidgetContainerState.get-widget-visible(i);
                x: (parent.width - total-width) / 2 + page-number * (item-size + spacing);

                function attempt-focus() {
                    if domain-active && has-view && !i-focus.has-focus {
                        i-focus.focus();
                    }
                }

                changed has-view => attempt-focus();
                changed domain-active => attempt-focus();

                init => {
                    if i == 0 && domain-active {
                        i-focus.focus();
                    }
                }

                Text {
                    color: white;
                    text: parent.page-number + 1;
                }

                i-focus := ControlledFocusScope {
                    init-focus: false;

                    focus-gained => {
                        if !has-view { // prevent dirty-ing the number and causing recursion
                            WidgetContainerState.change-page(i);
                        }
                    }

                    activated => WidgetContainerState.focus-page(i);
                }
            }
        }

        center-widget-container-inner := Rectangle {
            width: 100%;
            height: 90%;

            clip: true;

            center-widget-container-layout := HorizontalLayout {
                x: (-WidgetContainerState.current-page * self.width) - (self.spacing * WidgetContainerState.current-page);

                animate x {
                    duration: GlobalAnimation.page-duration;
                    easing: ease-in-out;
                }

                car-display-widget := Widget {
                    if !GeneralSettings.use-bevy-car-display: CarDisplayWidget {
                        height: 100%;
                        width: 100%;
                    }

                    if GeneralSettings.use-bevy-car-display: BevyCarDisplayWidget {
                        has-focus: parent.has-target;
                        height: 100%;
                        width: 100%;
                    }
                }

                road-indicator-widget := Widget {
                    visible: !GeneralSettings.use-bevy-car-display;

                    RoadIndicatorWidget {
                        height: 100%;
                        width: 100%;
                    }
                }

                settings-menu-widget := FocusableWidget {
                    nav-front-forward => settings-button.focus();

                    HorizontalLayout {
                        alignment: center;
                        padding: 20px;

                        VerticalLayout {
                            alignment: center;

                            Rectangle {
                                settings-button := Button {
                                    text: "Settings";

                                    activated => {
                                        ApplicationState.settings-menu-visible = !ApplicationState.settings-menu-visible;
                                    }
                                }
                            }
                        }
                    }
                }

                FocusableWidget {
                    nav-front-forward => FocusState.force-focus(can-display-widget.first-focus-id);
                    nav-end-backward => FocusState.force-focus(can-display-widget.last-focus-id);

                    can-display-widget := CanDisplayWidget {
                        running: parent.has-focus;
                        height: 100%;
                        width: 100%;
                    }

                    if !self.has-focus: Rectangle {
                        height: 80%;
                        width: 80%;

                        background: black.transparentize(5%);
                        Text {
                            text: "Enter to run";
                            font-size: 25px;
                        }
                    }
                }

                if DebugSettings.debug-mode: FocusableWidget {
                    nav-front-forward => debug-menu-widget.focus();

                    VerticalLayout {
                        debug-menu-widget := DebugMenuWidget {
                            height: 100%;
                            width: 100%;
                        }
                    }
                }
            }
        }
    }
}
