import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Black.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Bold.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-ExtraLight.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Light.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Medium.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Regular.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-SemiBold.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Thin.ttf";

import { VerticalBox, ComboBox } from "std-widgets.slint";

import { Arc } from "@lib/core.slint";
import { ThemeParams } from "../themes.slint";
import { InstrumentGauge } from "components/instrument_gauge.slint";
import { SymbolProperties } from "symbol_properties.slint";
import { SCarData } from "@data/car_data.slint";
import { SUnitSystem } from "@lib/units.slint";
import {
    ApplicationState,
    GeneralSettings,
} from "@lib/state.slint";
import { WidgetContainer } from "../../components/widget_container.slint";

global DefaultThemeParams {
    out property <ThemeParams> default-theme-params: { font-family: "Montserrat", font-weight: 400 };
}

component PrimarySection inherits Rectangle {
    background: transparent;
}

export component SymbolLight inherits Image {
    in property <float> scale: 1;
    width: SymbolProperties.size * scale;
    height: SymbolProperties.size * scale;
    image-fit: ImageFit.contain;
    colorize: Colors.blueviolet;
}

component GaugeAttachedSymbol inherits SymbolLight {
    in property <angle> angle: 0deg;
    in property <length> radius-offset: 25px;
    in property <length> radius: max(self.width, self.height) / 2;

    in property <length> center-x: 0px;
    in property <length> center-y: 0px;
    in property <length> center-radius: 1px;

    x: center-x - self.width / 2 + ((center-radius + radius + radius-offset) * cos(angle));
    y: center-y - self.height / 2 - ((center-radius + radius + radius-offset) * sin(angle));
}

export component DefaultTheme inherits Rectangle {
    background: transparent;

    width: self.height * (1920 / 720);
    height: 720px;

    VerticalLayout {
        top-span := PrimarySection {
            height: SymbolProperties.size;
        }

        mid-span := HorizontalLayout {
            left-tri := PrimarySection {
                width: parent.width * 38%;

                tachometer := InstrumentGauge {
                    property <int> max: SCarData.engine_rpm.max != 0 ? SCarData.engine_rpm.max : 8100;
                    property <angle> redline: self.angle-range / 8 * 6.6;

                    width: self.height;
                    height: min(parent.height, parent.width * 75%);

                    y: parent.height / 2 - self.height / 2 + parent.height * 2%;

                    start: 180deg + 45deg;
                    end: -45deg;

                    progress: SCarData.engine_rpm.value / (SCarData.engine_rpm.max != 0 ? SCarData.engine_rpm.max : (SCarData.engine_rpm.value * 2));

                    needle-sweep-color: self.progress >= (redline / self.angle-range) ? red : white;

                    regions: [
                        {
                            start: self.start - 0.75deg,
                            end: self.end,
                            major-ticks: ceil((max + 1) / 1000),
                            major-tick-inner-radius: self.width / 2 - 40px,
                            major-tick-outer-radius: self.width / 2,
                            major-tick-fill: Colors.white,
                            major-tick-size: 0.75deg,
                            label-major-ticks: true,
                            major-tick-label-scale: 1,
                            major-tick-label-fill: Colors.white,
                            minor-ticks: 3,
                            minor-tick-inner-radius: self.width / 2 - 30px,
                            minor-tick-outer-radius: self.width / 2,
                            minor-tick-fill: Colors.white,
                            minor-tick-size: 0.3deg,
                            fill-final-tick: true,
                        }
                    ];

                    tachometer-redline := Arc {
                        width: 100%;
                        height: 100%;

                        fill: red.darker(30%);
                        z: -1;

                        inner-radius: parent.regions[0].major-tick-inner-radius + 27.5px;
                        outer-radius: parent.regions[0].major-tick-outer-radius - 5px;

                        start: parent.start + parent.redline;
                        end: parent.end;
                    }

                    tachometer-unit-label := Text {
                        text: "×1000";
                        color: tachometer.background-fill.transparentize(85%);
                        font-size: 30px;
                        horizontal-alignment: TextHorizontalAlignment.center;
                        y: parent.height * 27.5%;
                    }
                }

                coolant-temp-gauge := InstrumentGauge {
                    width: tachometer.width;
                    height: tachometer.height;

                    y: tachometer.y;
                    x: tachometer.x;

                    property <angle> angle_offset: 57.5deg;
                    property <angle> blueline: self.angle-range / 4;
                    property <angle> redline: self.angle-range / 4;

                    start: 0deg - angle_offset;
                    end: -180deg + angle_offset;

                    needle-inner-radius: self.width / 2.45;
                    needle-thickness: 1.75deg;

                    progress: SCarData.engine_coolant_temp.value / (SCarData.engine_coolant_temp.max != 0 ? SCarData.engine_coolant_temp.max : (SCarData.engine_coolant_temp.value * 2));
                    needle-sweep-color: self.progress >= ((self.angle_range - redline) / self.angle-range) ? red : (self.progress <= (blueline / self.angle-range) ? blue : SymbolProperties.symbol_color_white);

                    regions: [
                        {
                            start: self.start - 0.4deg,
                            end: self.start + blueline,
                            major-ticks: 2,
                            major-tick-inner-radius: self.width / 2 - 20px,
                            major-tick-outer-radius: self.width / 2,
                            major-tick-fill: Colors.white,
                            major-tick-size: 0.4deg,
                            label-major-ticks: false,
                            minor-ticks: 0,
                            fill-final-tick: true,
                        },
                        {
                            start: self.end - self.redline,
                            end: self.end,
                            major-ticks: 2,
                            major-tick-inner-radius: self.width / 2 - 20px,
                            major-tick-outer-radius: self.width / 2,
                            major-tick-fill: Colors.white,
                            major-tick-size: 0.4deg,
                            label-major-ticks: false,
                            minor-ticks: 0,
                            fill-final-tick: true,
                        },
                    ];

                    coolant-temp-gauge-redline := Arc {
                        width: 100%;
                        height: 100%;

                        fill: red.darker(30%);
                        z: -1;

                        inner-radius: parent.regions[0].major-tick-inner-radius + 9px;
                        outer-radius: parent.regions[0].major-tick-outer-radius - 5px;

                        start: parent.end - parent.redline;
                        end: parent.end;
                    }

                    coolant-temp-gauge-blueline := Arc {
                        width: 100%;
                        height: 100%;

                        fill: blue;
                        z: -1;

                        inner-radius: parent.regions[0].major-tick-inner-radius + 9px;
                        outer-radius: parent.regions[0].major-tick-outer-radius - 5px;

                        start: parent.start;
                        end: parent.start + parent.blueline;
                    }

                    coolant-temp-light := SymbolLight {
                        scale: 60%;
                        source: @image-url("../../../../resources/images/coolant-temp-low-high-indicator-light.png");
                        y: coolant-temp-gauge.height - self.height - 60px;
                        colorize: coolant-temp-gauge.needle-sweep-color == SymbolProperties.symbol_color_white ? SymbolProperties.symbol_color_white.transparentize(75%) : coolant-temp-gauge.needle-sweep-color;
                    }
                }

                mt-gear-label := Text {
                    text: SCarData.reverse_sw.value ? "R" : SCarData.mt_gear.value;
                    color: SCarData.mt_clutch_sw.value ? white.transparentize(70%) : white;
                    font-size: 85px;

                    x: tachometer.x + tachometer.width / 2 - self.width / 2;
                    y: tachometer.y + tachometer.height / 2 - self.height / 2;

                    vertical-alignment: TextVerticalAlignment.center;
                    horizontal-alignment: TextHorizontalAlignment.center;
                }

                parking-brake-warning := Text {
                    text: "BRAKE";
                    font-size: 42px;
                    letter-spacing: -2px;
                    font-weight: 500;

                    y: tachometer.y + tachometer.height * 62.5%;

                    vertical-alignment: TextVerticalAlignment.center;
                    horizontal-alignment: TextHorizontalAlignment.center;

                    color: SymbolProperties.symbol_color_red;
                    visible: SCarData.handbrake_sw.value;
                }

                left-turn-signal := GaugeAttachedSymbol {
                    center-radius: tachometer.width / 2;
                    center-x: tachometer.x + tachometer.width / 2;
                    center-y: tachometer.y + tachometer.height / 2;

                    angle: 40deg;

                    source: @image-url("../../../../resources/images-svg/turn-signal-arrow.svg");
                    colorize: SymbolProperties.symbol_color_green;

                    visible: SCarData.left_turn_signal_enabled.value;
                    rotation-angle: 180deg;
                }

                highbeam-indicator := GaugeAttachedSymbol {
                    source: @image-url("../../../../resources/images/highbeam-indicator-light.png");
                    colorize: SymbolProperties.symbol_color_blue;

                    angle: left-turn-signal.angle + SymbolProperties.symbol_angle_padding;

                    center-radius: tachometer.width / 2;
                    center-x: tachometer.x + tachometer.width / 2;
                    center-y: tachometer.y + tachometer.height / 2;

                    visible: SCarData.highbeams_enabled.value;
                }

                foglight-indicator := GaugeAttachedSymbol {
                    scale: 0.8;
                    source: @image-url("../../../../resources/images/front-fog-indicator-light.png");
                    colorize: SymbolProperties.symbol_color_green;

                    angle: highbeam-indicator.angle + SymbolProperties.symbol_angle_padding;

                    center-radius: tachometer.width / 2;
                    center-x: tachometer.x + tachometer.width / 2;
                    center-y: tachometer.y + tachometer.height / 2;

                    visible: SCarData.fog_lights_enabled.value;
                }

                check-engine-light := GaugeAttachedSymbol {
                    center-radius: tachometer.width / 2;
                    center-x: tachometer.x + tachometer.width / 2;
                    center-y: tachometer.y + tachometer.height / 2;

                    angle: 360deg - 40deg;

                    source: @image-url("../../../../resources/images/check-engine-warning-light-icon.png");
                    colorize: SymbolProperties.symbol-color-yellow;

                    visible: SCarData.check_engine_light_enabled.value;
                }

                oil-pressure-warning-light := GaugeAttachedSymbol {
                    center-radius: tachometer.width / 2;
                    center-x: tachometer.x + tachometer.width / 2;
                    center-y: tachometer.y + tachometer.height / 2;

                    angle: check-engine-light.angle + SymbolProperties.symbol_angle_padding;

                    source: @image-url("../../../../resources/images-svg/oil-pressure-warning-light.svg");
                    colorize: SymbolProperties.symbol-color-red;

                    visible: SCarData.oil_pressure_warning_light_enabled.value;
                }

                hood-open-warning-light := GaugeAttachedSymbol {
                    center-radius: tachometer.width / 2;
                    center-x: tachometer.x + tachometer.width / 2;
                    center-y: tachometer.y + tachometer.height / 2;

                    angle: left-turn-signal.angle - SymbolProperties.symbol_angle_padding;

                    source: @image-url("../../../../resources/images/engine-hood-open-warning-light.png");
                    colorize: SymbolProperties.symbol-color-red;

                    visible: SCarData.hood_open.value;
                }

                door-open-warning-light := GaugeAttachedSymbol {
                    center-radius: tachometer.width / 2;
                    center-x: tachometer.x + tachometer.width / 2;
                    center-y: tachometer.y + tachometer.height / 2;

                    angle: oil-pressure-warning-light.angle + SymbolProperties.symbol_angle_padding;

                    source: @image-url("../../../../resources/images/dooropen-warning-light.png");
                    colorize: SymbolProperties.symbol-color-red;

                    visible: SCarData.any_door_open.value;
                }

                rcta-disabled-warning-light := GaugeAttachedSymbol {
                    center-radius: tachometer.width / 2;
                    center-x: tachometer.x + tachometer.width / 2;
                    center-y: tachometer.y + tachometer.height / 2;

                    angle: 180deg + 40deg;

                    source: @image-url("../../../../resources/images-svg/rcta-warning-light-off.svg");
                    colorize: SymbolProperties.symbol-color-yellow;

                    visible: SCarData.rcta_disabled.value;
                }

                srs-airbag-system-warning-light := GaugeAttachedSymbol {
                    scale: 0.9;
                    center-radius: tachometer.width / 2;
                    center-x: tachometer.x + tachometer.width / 2;
                    center-y: tachometer.y + tachometer.height / 2;

                    angle: rcta-disabled-warning-light.angle - SymbolProperties.symbol_angle_padding;

                    source: @image-url("../../../../resources/images/srs-airbag-system-warning-light.png");
                    colorize: SymbolProperties.symbol-color-yellow;

                    visible: SCarData.srs_warning_light_enabled.value;
                }
            }

            mid-tri := PrimarySection {
                WidgetContainer {
                    width: 100%;
                    height: 100%;
                }
            }

            right-tri := PrimarySection {
                width: left-tri.width;

                speedometer := InstrumentGauge {
                    width: self.height;
                    height: tachometer.height;

                    y: tachometer.y;

                    start: tachometer.start;
                    end: tachometer.end;

                    property <int> max: SCarData.vehicle_speed.max != 0 ? SCarData.vehicle_speed.max : 1000;
                    progress: SCarData.vehicle_speed.value / max;

                    property <int> speed_delim: ApplicationState.user_unit == SUnitSystem.USCS ? 20 : 20;
                    property <int> final_speed_delim: (max / speed_delim) + 1;

                    property <int> minor_ticks: ApplicationState.user_unit == SUnitSystem.USCS ? 1 : 1;
                    property <color> tick_color: #ffffff;
                    property <float> tick_size: 0.175%;

                    regions: [
                        {
                            start: self.start - 1deg,
                            end: self.end,
                            major-ticks: final_speed_delim,
                            major-tick-inner-radius: self.width / 2 - 40px,
                            major-tick-outer-radius: self.width / 2,
                            major-tick-fill: Colors.white,
                            major-tick-size: 0.7deg,
                            label-major-ticks: true,
                            major-tick-label-scale: speed_delim,
                            major-tick-label-fill: Colors.white,
                            minor-ticks: minor_ticks,
                            minor-tick-inner-radius: self.width / 2 - 30px,
                            minor-tick-outer-radius: self.width / 2,
                            minor-tick-fill: Colors.white,
                            minor-tick-size: 0.3deg,
                            fill-final-tick: true,
                        }
                    ];

                    speedometer-label := Text {
                        text: round(SCarData.vehicle_speed.value);
                        width: parent.width;
                        color: white;
                        font-size: 85px;

                        vertical-alignment: TextVerticalAlignment.center;
                        horizontal-alignment: TextHorizontalAlignment.center;
                    }

                    speedometer-unit-label := Text {
                        text: SCarData.vehicle_speed.unit-str;
                        color: speedometer-label.color.transparentize(75%);
                        font-size: speedometer-label.font-size * 70%;
                        horizontal-alignment: TextHorizontalAlignment.center;
                        y: speedometer-label.y + speedometer-label.height;
                    }
                }

                cruise-control-frame := Rectangle {
                    background: transparent;

                    x: speedometer.x;
                    y: speedometer.y;
                    height: speedometer.height;
                    width: speedometer.width;

                    cruise-control-image := SymbolLight {
                        colorize: SCarData.cruise_control_set_enabled.value ? SymbolProperties.symbol_color_green : SymbolProperties.symbol_color_white;
                        source: @image-url("../../../../resources/images-svg/cruise-control-indicator-light.svg");

                        y: speedometer-label.y - self.height;

                        cruise-control-speed-label := Text {
                            text: round(SCarData.cruise_control_speed.value);
                            color: cruise-control-image.colorize;
                            font-size: 35px;
                            font-weight: 500;

                            x: parent.width + 3px;
                            y: parent.height / 2 - self.height / 2;

                            vertical-alignment: TextVerticalAlignment.center;
                            horizontal-alignment: TextHorizontalAlignment.left;
                        }

                        visible: SCarData.cruise_control_enabled.value;
                    }
                }

                fuel-level-gauge := InstrumentGauge {
                    width: speedometer.width;
                    height: speedometer.height;

                    y: speedometer.y;
                    x: speedometer.x;

                    property <angle> blueline: self.angle-range / 10;

                    start: coolant-temp-gauge.start;
                    end: coolant-temp-gauge.end;

                    needle-inner-radius: coolant-temp-gauge.needle-inner-radius;
                    needle-thickness: coolant-temp-gauge.needle-thickness;

                    progress: SCarData.fuel_level.value / (SCarData.fuel_level.max != 0 ? SCarData.fuel_level.max : (SCarData.fuel_level.value * 3));
                    needle-sweep-color: self.progress <= (blueline / self.angle-range) ? SymbolProperties.symbol_color_yellow : SymbolProperties.symbol_color_white;

                    regions: [
                        {
                            start: self.start - coolant-temp-gauge.regions[0].major-tick-size,
                            end: self.end,
                            major-ticks: 2,
                            major-tick-inner-radius: coolant-temp-gauge.regions[0].major-tick-inner-radius,
                            major-tick-outer-radius: coolant-temp-gauge.regions[0].major-tick-outer-radius,
                            major-tick-fill: Colors.white,
                            major-tick-size: coolant-temp-gauge.regions[0].major-tick-size,
                            minor-ticks: 1,
                            minor-tick-inner-radius: self.width / 2 - 15px,
                            minor-tick-outer-radius: self.width / 2,
                            minor-tick-fill: Colors.white,
                            minor-tick-size: 0.3deg,
                            label-major-ticks: false,
                            fill-final-tick: true,
                        },
                        {
                            start: self.start - coolant-temp-gauge.regions[0].major-tick-size,
                            end: self.start + self.blueline,
                            major-ticks: 2,
                            major-tick-inner-radius: coolant-temp-gauge.regions[0].major-tick-inner-radius,
                            major-tick-outer-radius: coolant-temp-gauge.regions[0].major-tick-outer-radius,
                            major-tick-fill: Colors.white,
                            major-tick-size: coolant-temp-gauge.regions[0].major-tick-size,
                            minor-ticks: 0,
                            label-major-ticks: false,
                            fill-final-tick: true,
                        },
                    ];

                    fuel-level-gauge-yellowline := Arc {
                        width: 100%;
                        height: 100%;

                        fill: SymbolProperties.symbol_color_yellow;
                        z: -1;

                        inner-radius: parent.regions[0].major-tick-inner-radius + 9px;
                        outer-radius: parent.regions[0].major-tick-outer-radius - 5px;

                        start: parent.start;
                        end: parent.start + parent.blueline;
                    }

                    fuel-level-light := SymbolLight {
                        scale: 60%;
                        source: @image-url("../../../../resources/images/lowfuel-warning-light.png");
                        y: fuel-level-gauge.height - self.height - 60px;
                        colorize: fuel-level-gauge.needle-sweep-color == SymbolProperties.symbol_color_white ? SymbolProperties.symbol_color_white.transparentize(75%) : fuel-level-gauge.needle-sweep-color;

                        Text {
                            color: parent.colorize;
                            font-size: 20px;
                            text: "►"; //TODO: "►" (original character) seems to not render on some versions of slint, and cause massive memory leaks on others
                            x: parent.width - 5px;
                            y: parent.height / 2 - self.height / 2 + 3px;
                        }
                    }
                }

                right-turn-signal := GaugeAttachedSymbol {
                    center-radius: speedometer.width / 2;
                    center-x: speedometer.x + speedometer.width / 2;
                    center-y: speedometer.y + speedometer.height / 2;

                    angle: 180deg - left-turn-signal.angle;

                    source: left-turn-signal.source;
                    colorize: SymbolProperties.symbol_color_green;

                    visible: SCarData.right_turn_signal_enabled.value;
                }

                headlight-indicator := GaugeAttachedSymbol {
                    scale: 1.1;
                    center-radius: speedometer.width / 2;
                    center-x: speedometer.x + speedometer.width / 2;
                    center-y: speedometer.y + speedometer.height / 2;

                    angle: 180deg - highbeam-indicator.angle;

                    source: @image-url("../../../../resources/images/headlight-indicator-light.png");
                    colorize: SymbolProperties.symbol-color-green;

                    visible: SCarData.lowbeams_enabled.value;

                    // TODO: check if headlight_dimmer is on during the day when running lights are on

                    // the factory cluster does not distinguish between the parking lights and the lowbeams
                    // I believe this to be a safety issue
                    // visible: SCarData.lowbeams_enabled.value || SCarData.parking_lights_enabled.value;
                }

                driver-seatbelt-indicator := GaugeAttachedSymbol {
                    scale: 0.9;
                    center-radius: speedometer.width / 2;
                    center-x: speedometer.x + speedometer.width / 2;
                    center-y: speedometer.y + speedometer.height / 2;

                    angle: 180deg - foglight-indicator.angle;

                    source: @image-url("../../../../resources/images/seatbelt-warning-light.png");
                    colorize: SymbolProperties.symbol-color-red;

                    visible: SCarData.driver_seatbelt_warning_enabled.value;
                }

                if !GeneralSettings.disable-hill-assist: hill-assist-enabled-indicator := GaugeAttachedSymbol {
                    center-radius: speedometer.width / 2;
                    center-x: speedometer.x + speedometer.width / 2;
                    center-y: speedometer.y + speedometer.height / 2;

                    angle: 360deg - 40deg;

                    source: @image-url("../../../../resources/images-svg/hillstartassist-warning-light.svg");
                    colorize: SymbolProperties.symbol-color-yellow;

                    visible: SCarData.hill_assist_enabled.value;
                }

                low-washer-fluid-indicator := GaugeAttachedSymbol {
                    center-radius: speedometer.width / 2;
                    center-x: speedometer.x + speedometer.width / 2;
                    center-y: speedometer.y + speedometer.height / 2;

                    angle: 360deg - 40deg + SymbolProperties.symbol_angle_padding;

                    source: @image-url("../../../../resources/images-svg/windshield-washer-fluid-warning.svg");
                    colorize: SymbolProperties.symbol-color-yellow;

                    // TODO: windshield-washer-fluid-indicator
                    visible: false;
                }

                vdc-off-warning-indicator := GaugeAttachedSymbol {
                    center-radius: speedometer.width / 2;
                    center-x: speedometer.x + speedometer.width / 2;
                    center-y: speedometer.y + speedometer.height / 2;

                    angle: 180deg + 40deg;

                    source: @image-url("../../../../resources/images/vehicle-dynamics-control-off-indicator-light.png");
                    colorize: SymbolProperties.symbol-color-yellow;

                    visible: SCarData.traction_control_disabled.value;
                }

                tq-vectoring-enabled-indicator := GaugeAttachedSymbol {
                    center-radius: speedometer.width / 2;
                    center-x: speedometer.x + speedometer.width / 2;
                    center-y: speedometer.y + speedometer.height / 2;

                    angle: vdc-off-warning-indicator.angle - SymbolProperties.symbol_angle_padding;

                    source: @image-url("../../../../resources/images/traction-mode-indicator-light.png");
                    colorize: SymbolProperties.symbol-color-green;

                    visible: SCarData.active_tq_vectoring_enabled.value;
                }

                tpms-warning-light-enabled-indicator := GaugeAttachedSymbol {
                    center-radius: speedometer.width / 2;
                    center-x: speedometer.x + speedometer.width / 2;
                    center-y: speedometer.y + speedometer.height / 2;

                    angle: vdc-off-warning-indicator.angle - SymbolProperties.symbol_angle_padding * 2;

                    source: @image-url("../../../../resources/images/tpms-warning-light.png");
                    colorize: SymbolProperties.symbol-color-yellow;

                    visible: SCarData.tpms_warning_light_enabled.value;
                }
            }
        }

        bottom-span := PrimarySection {
            height: 8%;
            HorizontalLayout {
                alignment: center;
                odometer-text-section := Rectangle {
                    background: transparent;

                    odometer-text := Text {
                        color: white;
                        text: floor(SCarData.odometer.value);
                        font-size: 47.5px;
                        vertical-alignment: center;
                        horizontal-alignment: center;
                    }

                    odometer-dec-text := Text {
                        color: odometer-text.color.transparentize(60%);
                        text: "." + (floor(SCarData.odometer.value * 10) / 10 - floor(SCarData.odometer.value)) * 10;
                        font-size: odometer-text.font-size;
                        horizontal-alignment: left;
                        vertical-alignment: odometer-text.vertical-alignment;
                        x: odometer-text.x + odometer-text.width;
                    }

                    odometer-unit-text := Text {
                        vertical-alignment: center;
                        color: odometer-text.color.transparentize(70%);
                        text: SCarData.odometer.unit_str;
                        font-size: odometer-text.font-size * 70%;
                        x: odometer-dec-text.x + odometer-dec-text.width;
                    }
                }
            }
        }
    }
}
