enum RadialCenter {
    Bottom,
    Top,
    Center
}

export component RadialRect inherits Rectangle {
    in property <angle> rotation: 0deg;
    in property <length> inner-radius: self.width / 1;
    in property <angle> thickness: 1deg;
    in property <angle> outer-thickness: thickness;
    in property <angle> inner-thickness: thickness;
    in property <RadialCenter> center-on: Center;

    in property <brush> fill: white;
    if center-on == RadialCenter.Bottom: Path {
        viewbox-width: self.width / 1px;
        viewbox-height: self.height / 1px;
        fill: parent.fill;

        MoveTo {
            x: (parent.viewbox-width / 2) + cos(rotation) * (parent.viewbox-width / 2);
            y: (parent.viewbox-height / 2) - sin(rotation) * (parent.viewbox-height / 2);
        }

        LineTo {
            x: (parent.viewbox-width / 2) + cos(rotation - outer-thickness) * (parent.viewbox-width / 2);
            y: (parent.viewbox-height / 2) - sin(rotation - outer-thickness) * (parent.viewbox-height / 2);
        }

        LineTo {
            x: (parent.viewbox-width / 2) + cos(rotation - inner-thickness) * (inner-radius / 1px);
            y: (parent.viewbox-height / 2) - sin(rotation - inner-thickness) * (inner-radius / 1px);
        }

        LineTo {
            x: (parent.viewbox-width / 2) + cos(rotation) * (inner-radius / 1px);
            y: (parent.viewbox-height / 2) - sin(rotation) * (inner-radius / 1px);
        }
    }
    if center-on == RadialCenter.Top: Path {
        viewbox-width: self.width / 1px;
        viewbox-height: self.height / 1px;
        fill: parent.fill;

        MoveTo {
            x: (parent.viewbox-width / 2) + cos(rotation) * (parent.viewbox-width / 2);
            y: (parent.viewbox-height / 2) - sin(rotation) * (parent.viewbox-height / 2);
        }

        LineTo {
            x: (parent.viewbox-width / 2) + cos(rotation + outer-thickness) * (parent.viewbox-width / 2);
            y: (parent.viewbox-height / 2) - sin(rotation + outer-thickness) * (parent.viewbox-height / 2);
        }

        LineTo {
            x: (parent.viewbox-width / 2) + cos(rotation + inner-thickness) * (inner-radius / 1px);
            y: (parent.viewbox-height / 2) - sin(rotation + inner-thickness) * (inner-radius / 1px);
        }

        LineTo {
            x: (parent.viewbox-width / 2) + cos(rotation) * (inner-radius / 1px);
            y: (parent.viewbox-height / 2) - sin(rotation) * (inner-radius / 1px);
        }
    }
    if center-on == RadialCenter.Center: Path {
        viewbox-width: self.width / 1px;
        viewbox-height: self.height / 1px;
        fill: parent.fill;

        MoveTo {
            x: (parent.viewbox-width / 2) + cos(rotation + outer-thickness / 2) * (parent.viewbox-width / 2);
            y: (parent.viewbox-height / 2) - sin(rotation + outer-thickness / 2) * (parent.viewbox-height / 2);
        }

        LineTo {
            x: (parent.viewbox-width / 2) + cos(rotation - outer-thickness / 2) * (parent.viewbox-width / 2);
            y: (parent.viewbox-height / 2) - sin(rotation - outer-thickness / 2) * (parent.viewbox-height / 2);
        }

        LineTo {
            x: (parent.viewbox-width / 2) + cos(rotation - inner-thickness / 2) * (inner-radius / 1px);
            y: (parent.viewbox-height / 2) - sin(rotation - inner-thickness / 2) * (inner-radius / 1px);
        }

        LineTo {
            x: (parent.viewbox-width / 2) + cos(rotation + inner-thickness / 2) * (inner-radius / 1px);
            y: (parent.viewbox-height / 2) - sin(rotation + inner-thickness / 2) * (inner-radius / 1px);
        }
    }
}

export component GaugeArc inherits Path {
    in property <angle> start;
    in property <angle> end;

    property <angle> angle-range: end - start;

    in property <length> inner-radius: self.width / 3;
    in property <length> outer-radius: self.width / 2;

    viewbox-width: self.width / 1px;
    viewbox-height: self.height / 1px;

    MoveTo {
        x: (parent.viewbox-width / 2) + cos(start) * (outer-radius / 1px);
        y: (parent.viewbox-height / 2) - sin(start) * (outer-radius / 1px);
    }

    LineTo {
        x: (parent.viewbox-width / 2) + cos(start) * (inner-radius / 1px);
        y: (parent.viewbox-height / 2) - sin(start) * (inner-radius / 1px);
    }

    ArcTo {
        x: (parent.viewbox-width / 2) + cos(end) * (inner-radius / 1px);
        y: (parent.viewbox-height / 2) - sin(end) * (inner-radius / 1px);
        radius-x: inner-radius / 1px;
        radius-y: inner-radius / 1px;
        sweep: angle-range < 0deg;
        large-arc: abs(angle-range) > 180deg;
    }

    LineTo {
        x: (parent.viewbox-width / 2) + cos(end) * (outer-radius / 1px);
        y: (parent.viewbox-height / 2) - sin(end) * (outer-radius / 1px);
    }

    ArcTo {
        x: (parent.viewbox-width / 2) + cos(start) * (outer-radius / 1px);
        y: (parent.viewbox-height / 2) - sin(start) * (outer-radius / 1px);
        radius-x: outer-radius / 1px;
        radius-y: outer-radius / 1px;
        sweep: angle-range > 0deg;
        large-arc: abs(angle-range) > 180deg;
    }

    LineTo {
        x: (parent.viewbox-width / 2) + cos(start) * (outer-radius / 1px);
        y: (parent.viewbox-height / 2) - sin(start) * (outer-radius / 1px);
    }
}

export struct InstrumentGaugeRegion {
    start: angle,
    end: angle,

    major-ticks: int,
    minor-ticks: int,

    major-tick-inner-radius: length,
    major-tick-outer-radius: length,

    minor-tick-inner-radius: length,
    minor-tick-outer-radius: length,

    label-major-ticks: bool,
    major-tick-label-inner-radius-offset: length,
    major-tick-label-scale: float,
    // label-minor-ticks: bool,

    major-tick-fill: brush,
    minor-tick-fill: brush,

    major-tick-label-fill: brush,
    minor-tick-label-fill: brush,

    major-tick-size: angle,
    minor-tick-size: angle,

    fill-final-tick: bool,
}

export component InstrumentGauge inherits Rectangle {
    in property <angle> start;
    in property <angle> end;

    in property <float> progress: 100%;

    out property <angle> angle-range: end - start;
    out property <angle> scaled-progress: progress * angle-range;

    in property <length> background-outer-radius <=> background-arc.outer-radius;
    in property <length> background-inner-radius <=> background-arc.inner-radius;

    in property <length> needle-outer-radius <=> needle.outer-radius;
    in property <length> needle-inner-radius <=> needle.inner-radius;
    in property <angle> needle-thickness <=> needle.thickness;

    in property <brush> background-fill <=> background-arc.fill;
    in property <brush> needle-fill <=> needle.fill;
    in property <brush> needle-sweep-color: needle-fill;

    property <float> gradient-start: (needle_inner_radius * 1.4) / self.width;
    property <float> gradient-pre-end: (100 - ((100 - gradient-start) / ((100 + gradient-start) / 2))) / 100;
    in property <brush> needle-sweep-fill: @radial-gradient(circle, #00000000 gradient-start, needle-sweep-color.darker(25%).transparentize(50%) gradient-pre-end);

    in property <[InstrumentGaugeRegion]> regions: [
        {
            start: root.start - 1deg,
            end: root.start + root.angle-range,
            major-ticks: 4,
            minor-ticks: 1,
            major-tick-inner-radius: root.width / 2 - 40px,
            major-tick-outer-radius: root.width / 2,
            major-tick-fill: Colors.white,
            major-tick-label-fill: Colors.white,
            major-tick-label-scale: 1,
            minor-tick-inner-radius: root.width / 2 - 30px,
            minor-tick-outer-radius: root.width / 2,
            minor-tick-fill: Colors.white,
            minor-tick-label-fill: Colors.white,
            major-tick-size: 1deg,
            minor-tick-size: 0.5deg,
            fill-final-tick: true
        }
    ];

    for region[index] in regions: Rectangle {
        // TODO: make sure to respect the tick size when placing them so as to not allow overhanging ticks
        property <angle> angle-range: (region.end - region.start);
        property <angle> major-tick-angle-step: angle-range / (region.major-ticks - 1);
        property <angle> minor-tick-angle-step: major-tick-angle-step / (region.minor-ticks + 1);
        property <int> starting-count: index == 0 ? 0 : regions[index - 1].major-ticks - 1;

        width: root.width;
        height: root.height;

        for major-tick in region.major-ticks: major-tick-arc := Rectangle {
            width: root.width;
            height: root.height;

            property <angle> start: region.start + major-tick * major-tick-angle-step;
            property <angle> end: self.start + region.major-tick-size;

            visible: (region.fill-final-tick || ((major-tick + 1) != region.major-ticks));

            GaugeArc {
                width: root.width;
                height: root.height;

                start: start;
                end: end;

                fill: region.major-tick-fill;

                inner-radius: region.major-tick-inner-radius;
                outer-radius: region.major-tick-outer-radius;
            }

            if region.label-major-ticks: Text {
                color: region.major-tick-label-fill;
                text: (starting-count + major-tick) * region.major-tick-label-scale;

                font-size: 35px;

                x: (root.width / 2) - (self.width / 2) + (region.major-tick-inner-radius - self.font-size - region.major-tick-label-inner-radius-offset) * cos(-parent.start);
                y: (root.height / 2) - (self.height / 2) + (region.major-tick-inner-radius - self.font-size - region.major-tick-label-inner-radius-offset) * sin(-parent.start);
            }

            if (major-tick + 1) != region.major-ticks: Rectangle {
                for minor-tick in region.minor-ticks: GaugeArc {
                    start: major-tick-arc.start + (minor-tick + 1) * minor-tick-angle-step;
                    end: self.start + region.minor-tick-size;

                    width: root.width;
                    height: root.height;

                    fill: region.minor-tick-fill;

                    inner-radius: region.minor-tick-inner-radius;
                    outer-radius: region.minor-tick-outer-radius;
                }
            }
        }
    }

    needle-sweep := GaugeArc {
        width: needle.width;
        height: needle.height;

        start: root.start;
        end: needle.rotation;

        fill: parent.needle-sweep-fill;

        z: -1;

        outer-radius: needle.outer-radius;
        inner-radius: needle.inner-radius;
    }

    needle := Path {
        property <angle> rotation: parent.start + parent.scaled-progress;
        property <length> outer-radius: self.width / 2;
        property <length> inner-radius: self.width / 4;
        property <angle> thickness: 2deg;
        property <float> inner-point-offset: 3;

        fill: white;

        viewbox-width: self.width / 1px;
        viewbox-height: self.height / 1px;

        MoveTo {
            x: (parent.viewbox-width / 2) + cos(rotation) * (outer-radius / 1px);
            y: (parent.viewbox-height / 2) - sin(rotation) * (outer-radius / 1px);
        }

        LineTo {
            x: (parent.viewbox-width / 2) + cos(rotation + thickness / 2) * (inner-radius / 1px);
            y: (parent.viewbox-height / 2) - sin(rotation + thickness / 2) * (inner-radius / 1px);
        }

        LineTo {
            x: (parent.viewbox-width / 2) + cos(rotation) * (inner-radius / 1px - inner-point-offset);
            y: (parent.viewbox-height / 2) - sin(rotation) * (inner-radius / 1px - inner-point-offset);
        }

        LineTo {
            x: (parent.viewbox-width / 2) + cos(rotation - thickness / 2) * (inner-radius / 1px);
            y: (parent.viewbox-height / 2) - sin(rotation - thickness / 2) * (inner-radius / 1px);
        }
    }

    background-arc := GaugeArc {
        width: 100%;
        height: 100%;

        start: root.start;
        end: root.end;

        fill: white;

        outer-radius: self.width / 2 + 3px;
        inner-radius: self.width / 2;
    }
}
