import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Black.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Bold.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-ExtraLight.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Light.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Medium.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Regular.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-SemiBold.ttf";
import "../../../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Thin.ttf";

import { Button } from "std-widgets.slint";

import { ThemeSelectorWidget } from "../themes.slint";
import { NavigationMap } from "../../components/navmap.slint";
import { SCarData } from "../../data/car_data.slint";
import { SUnitSystem } from "../../data/units.slint";
import { ApplicationState } from "../../application/application_state.slint";
import { DebugMenuWidget, DebugMenuState } from "../../components/debug.slint";

import { InstrumentGauge, GaugeArc } from "../default/components/instrument_gauge.slint";

export component Default-NavmapTheme inherits Rectangle {
    background: transparent;
    height: 100%;
    width: 100%;

    VerticalLayout {
        HorizontalLayout {
            alignment: center;

            ThemeSelectorWidget { }
        }

        HorizontalLayout {
            alignment: center;

            navmap := NavigationMap {
                width: 70%;
            }
        }

        HorizontalLayout {
            alignment: center;

            odometer-text-section := Rectangle {
                background: transparent;

                odometer-text := Text {
                    color: white;
                    text: floor(SCarData.odometer.value);
                    font-size: 40px;
                    vertical-alignment: center;
                    horizontal-alignment: center;
                }

                odometer-dec-text := Text {
                    color: odometer-text.color.transparentize(60%);
                    text: "." + (floor(SCarData.odometer.value * 10) / 10 - floor(SCarData.odometer.value)) * 10;
                    font-size: odometer-text.font-size;
                    horizontal-alignment: left;
                    vertical-alignment: odometer-text.vertical-alignment;
                    x: odometer-text.x + odometer-text.width;
                }

                odometer-unit-text := Text {
                    vertical-alignment: center;
                    color: odometer-text.color.transparentize(70%);
                    text: SCarData.odometer.unit_str;
                    font-size: odometer-text.font-size * 70%;
                    x: odometer-dec-text.x + odometer-dec-text.width;
                }
            }
        }
    }

    tachometer := InstrumentGauge {
        out property <length> map-position-offset: 15px;
        property <int> max: SCarData.engine_rpm.max != 0 ? SCarData.engine_rpm.max : 8100;
        property <angle> redline: self.angle-range / 8 * 6.6;

        width: self.height;
        height: 55%;

        x: navmap.x - self.width / 2 - map-position-offset;
        y: parent.height / 2 - self.height / 2 + parent.height * 2%;

        start: 270deg;
        end: 90deg;

        progress: SCarData.engine_rpm.value / (SCarData.engine_rpm.max != 0 ? SCarData.engine_rpm.max : (SCarData.engine_rpm.value * 2));

        needle-sweep-color: self.progress >= (redline / self.angle-range) ? red : white;

        regions: [
            {
                start: self.start - 0.75deg,
                end: self.end,
                major-ticks: ceil((max + 1) / 1000),
                major-tick-inner-radius: self.width / 2 - 40px,
                major-tick-outer-radius: self.width / 2,
                major-tick-fill: Colors.white,
                major-tick-size: 0.75deg,
                label-major-ticks: true,
                major-tick-label-scale: 1,
                major-tick-label-inner-radius-offset: -15px,
                major-tick-label-fill: Colors.white,
                minor-ticks: 3,
                minor-tick-inner-radius: self.width / 2 - 30px,
                minor-tick-outer-radius: self.width / 2,
                minor-tick-fill: Colors.white,
                minor-tick-size: 0.3deg,
                fill-final-tick: true,
            }
        ];

        tachometer-redline := GaugeArc {
            width: 100%;
            height: 100%;

            fill: red.darker(30%);
            z: -1;

            inner-radius: parent.regions[0].major-tick-inner-radius + 27.5px;
            outer-radius: parent.regions[0].major-tick-outer-radius - 5px;

            start: parent.start + parent.redline;
            end: parent.end;
        }

        tachometer-unit-label := Text {
            text: "×1000";
            color: tachometer.background-fill.transparentize(85%);
            font-size: 28px;
            horizontal-alignment: right;
            x: parent.width / 2 - self.width;
            y: parent.height * 27.5%;
        }
    }

    mt-gear-label := Text {
        text: SCarData.reverse_sw.value ? "R" : (SCarData.mt_clutch_sw.value ? " " : SCarData.mt_gear.value);
        color: white;
        font-size: 65px;

        x: tachometer.x + tachometer.width / 2 - self.width;
        y: tachometer.y + tachometer.height / 2 - self.height / 2;

        vertical-alignment: center;
        horizontal-alignment: center;
    }

    speedometer := InstrumentGauge {
        width: self.height;
        height: tachometer.height;

        x: navmap.x + navmap.width - self.width / 2 + tachometer.map-position-offset;
        y: tachometer.y;
        start: 180deg - tachometer.start;
        end: 180deg - tachometer.end;

        property <int> max: SCarData.vehicle_speed.max != 0 ? SCarData.vehicle_speed.max : 1000;
        progress: SCarData.vehicle_speed.value / max;

        property <int> speed_delim: ApplicationState.user_unit == SUnitSystem.USCS ? 20 : 20;
        property <int> final_speed_delim: (max / speed_delim) + 1;

        property <int> minor_ticks: ApplicationState.user_unit == SUnitSystem.USCS ? 1 : 1;
        property <color> tick_color: #ffffff;
        property <float> tick_size: 0.175%;

        regions: [
            {
                start: self.start - 1deg,
                end: self.end,
                major-ticks: final_speed_delim,
                major-tick-inner-radius: self.width / 2 - 40px,
                major-tick-outer-radius: self.width / 2,
                major-tick-fill: Colors.white,
                major-tick-size: 0.7deg,
                label-major-ticks: false,
                major-tick-label-scale: speed_delim,
                major-tick-label-fill: Colors.white,
                minor-ticks: minor_ticks,
                minor-tick-inner-radius: self.width / 2 - 30px,
                minor-tick-outer-radius: self.width / 2,
                minor-tick-fill: Colors.white,
                minor-tick-size: 0.3deg,
                fill-final-tick: true,
            }
        ];

        speedometer-label := Text {
            text: round(SCarData.vehicle_speed.value);
            color: white;
            font-size: 55px;

            vertical-alignment: center;
            horizontal-alignment: left;

            x: parent.width / 2;
        }

        speedometer-unit-label := Text {
            text: SCarData.vehicle_speed.unit-str;
            color: speedometer-label.color.transparentize(75%);
            font-size: speedometer-label.font-size * 70%;
            horizontal-alignment: left;
            y: speedometer-label.y + speedometer-label.height;
            x: parent.width / 2;
        }
    }
}
