import { ScrollView, Button, StandardTableView } from "std-widgets.slint";

import { ControlledFocusScope } from "../components/controlled_focus_scope.slint";

export struct SCanFrameDisplay {
    id: int,
    formatted_id: string,
    dlc: int,
    data: [string],
    bit_display: [bool],
    byte_changes: [bool]
}

export global CanDisplay {
    in-out property <bool> running: false;
    in-out property <[SCanFrameDisplay]> CanFrames: [];
    in-out property <int> highest-dlc;
}

component TableRect inherits Rectangle {
    in property <string> text <=> label.text;
    in property <TextHorizontalAlignment> text-horizontal-alignment <=> label.horizontal-alignment;
    in property <TextVerticalAlignment> text-vertical-alignment <=> label.vertical-alignment;
    in property <length> post-padding: 20px;
    in property <length> vertical-padding: 10px;
    in property <length> pre-padding: 4px;
    in property <length> font-size: 12px;

    height: 30px;

    @children

    VerticalLayout {
        Rectangle {
            height: root.vertical-padding / 2;
        }

        layout := HorizontalLayout {
            alignment: LayoutAlignment.start;

            Rectangle {
                width: root.pre-padding;
            }

            label := Text {
                font-size: root.font-size;
                font-family: "JetBrains Mono";
                color: white;
                horizontal-alignment: left;
                vertical-alignment: center;
            }

            Rectangle {
                width <=> root.post-padding;
            }
        }

        Rectangle {
            height: root.vertical-padding / 2;
        }
    }
}

component TableHeaderRect inherits TableRect {
    height: 100%;
    vertical-padding: 20px;
    font-size: 13.5px;
}

export component CanDisplayWidget inherits Rectangle {
    in-out property <bool> running <=> CanDisplay.running;

    out property <int> first-focus-id;
    out property <int> last-focus-id;

    clip: true;

    header-background := Rectangle {
        width: header-layout.width;
        height: header-layout.height;
        x: header-layout.x;
        y: header-layout.y;
        background: gray.darker(95%);
    }

    header-layout := HorizontalLayout {
        y: 0;
        height: 35px;
        alignment: LayoutAlignment.start;

        id-header-label := TableHeaderRect {
            text: "ID";
        }

        dlc-header-label := TableHeaderRect {
            text: "DLC";
        }

        data-header-label := TableHeaderRect {
            text: "Data";
        }
    }

    ScrollView {
        y: header-layout.height;
        height: root.height - header-layout.height;

        VerticalLayout {
            for frame_display[i] in CanDisplay.CanFrames: Rectangle {
                background: mod(i, 2) == 1 ? transparent : #ffffff30;
            }
        }

        layout := HorizontalLayout {
            alignment: LayoutAlignment.start;
            spacing: 0px;
            padding: 0px;

            VerticalLayout {
                width: id-header-label.width;
                for frame-display[i] in CanDisplay.CanFrames: TableRect {
                    text: frame-display.formatted_id;
                }
            }

            VerticalLayout {
                width: dlc-header-label.width;
                for frame-display[i] in CanDisplay.CanFrames: TableRect {
                    text: frame-display.dlc;
                }
            }

            for data_col[i] in CanDisplay.highest-dlc: VerticalLayout {
                for frame-display[j] in CanDisplay.CanFrames: TableRect {
                    text: i < frame-display.dlc ? frame-display.data[i] : "";
                    visible: i < frame-display.dlc;

                    function byte-clicked() {
                        frame-display.bit_display[i] = !frame-display.bit_display[i];
                    }

                    Rectangle {
                        border-color: i-focus.has-focus ? blue : turquoise;
                        border-width: 4px;
                        background: transparent;
                        visible: i-focus.has-focus || i-focus.has-hover;
                    }

                    i-focus := ControlledFocusScope {
                        force-focus: false;

                        activated => byte-clicked();
                        init => {
                            if (i == 0) && (j == 0) {
                                root.first-focus-id = self.focus-id;
                            } else if i == (CanDisplay.highest-dlc - 1) && (j == (CanDisplay.CanFrames.length - 1)) {
                                root.last-focus-id = self.focus-id;
                            }
                        }
                    }
                }
            }
        }
    }
}
