import { ScrollView, Button } from "std-widgets.slint";

export struct SCanFrameDisplay {
    id: int,
    formatted_id: string,
    dlc: int,
    data: [string],
    bit_display: [bool],
    byte_changes: [bool]
}

export global CanDisplay {
    in-out property <bool> running: false;
    in-out property <[SCanFrameDisplay]> CanFrames: [];
    in-out property <int> highest-dlc;
}

component TableRect inherits Rectangle {
    in property <string> text <=> label.text;
    in property <TextHorizontalAlignment> text-horizontal-alignment <=> label.horizontal-alignment;
    in property <TextVerticalAlignment> text-vertical-alignment <=> label.vertical-alignment;
    in property <length> post-padding: 20px;
    in property <length> vertical-padding: 10px;
    in property <length> pre-padding: 4px;
    in property <length> font-size: 12px;

    height: 30px;

    @children

    VerticalLayout {
        Rectangle {
            height: root.vertical-padding / 2;
        }

        layout := HorizontalLayout {
            alignment: LayoutAlignment.start;

            Rectangle {
                width: root.pre-padding;
            }

            label := Text {
                font-size: root.font-size;
                font-family: "JetBrains Mono";
                color: white;
                horizontal-alignment: left;
                vertical-alignment: center;
            }

            Rectangle {
                width <=> root.post-padding;
            }
        }

        Rectangle {
            height: root.vertical-padding / 2;
        }
    }
}

component TableHeaderRect inherits TableRect {
    height: 100%;
    vertical-padding: 20px;
    font-size: 13.5px;
}

export component CanDisplayWidget inherits Rectangle {
    in-out property <bool> running <=> CanDisplay.running;

    clip: true;

    header-background := Rectangle {
        width: header-layout.width;
        height: header-layout.height;
        x: header-layout.x;
        y: header-layout.y;
        background: gray.darker(95%);
    }

    header-layout := HorizontalLayout {
        y: 0;
        height: 35px;
        alignment: LayoutAlignment.start;

        id-header-label := TableHeaderRect {
            text: "ID";
        }

        dlc-header-label := TableHeaderRect {
            text: "DLC";
        }

        data-header-label := TableHeaderRect {
            text: "Data";
        }
    }

    ScrollView {
        y: header-layout.height;
        height: root.height - header-layout.height;

        VerticalLayout {
            for frame_display[i] in CanDisplay.CanFrames: TableRect {
                background: mod(i, 2) == 1 ? black : #1b1b1b;
            }
        }

        layout := HorizontalLayout {
            alignment: LayoutAlignment.start;
            spacing: 0px;
            padding: 0px;

            VerticalLayout {
                alignment: LayoutAlignment.start;

                for frame-display[i] in CanDisplay.CanFrames: HorizontalLayout {
                    alignment: LayoutAlignment.start;

                    TableRect {
                        text: frame-display.formatted_id;
                        width: id-header-label.width;
                    }

                    TableRect {
                        text: frame-display.dlc;
                        width: dlc-header-label.width;
                    }

                    for data-byte[j] in frame-display.dlc: TableRect {
                        text: frame-display.data[j];

                        function byte-clicked() {
                            frame-display.bit_display[j] = !frame-display.bit_display[j];
                        }
                        property <bool> has-focus <=> i-focus.has-focus;
                        property <bool> has-hover <=> i-touch.has-hover;
                        Rectangle {
                            border-color: has-focus ? blue : turquoise;
                            border-width: 4px;
                            background: transparent;
                            visible: has-focus || has-hover;
                        }

                        i-touch := TouchArea {
                            width: 100%;
                            height: 100%;

                            clicked => byte-clicked();

                            forward-focus: i-focus;
                        }

                        i-focus := FocusScope {
                            width: 0px;
                            key-pressed(event) => {
                                if event.text == Key.Return {
                                    byte-clicked();
                                    accept
                                }
                                reject
                            }
                        }
                    }
                }
            }
        }
    }
}
