import { Button } from "std-widgets.slint";

import { ApplicationState } from "../application/application_state.slint";

export global FocusState {
    out property <int> num-focuses: 1;
    out property <int> current-focus: 0;

    out property <length> focus-x;
    out property <length> focus-y;
    out property <length> focus-width;
    out property <length> focus-height;

    public function create-focus-id() -> int {
        num-focuses += 1;
        num-focuses - 1
    }

    public function force-focus(id: int) {
        current-focus = id;
    }

    pure public function has-focus(id: int) -> bool {
        self.current-focus == id
    }
}

export global DomainState {
    out property <int> num-domains: 1;
    out property <int> current-layer: 0;
    out property <int> last-layer: 0;

    public function create-domain-id() -> int {
        num-domains += 1;
        num-domains - 1
    }

    public function enter-domain(domain-layer: int) {
        self.last-layer = self.current-layer;
        self.current-layer = domain-layer;
    }

    public function domain-exit(domain-layer: int) -> bool {
        if domain-layer == self.current-layer {
            enter-domain(self.last-layer);
            true
        }
        false
    }
}

export component ControlledFocusScope {
    in-out property <bool> force-focus: true;
    in-out property <bool> enabled <=> i-focus.enabled;

    out property <bool> has-focus <=> i-focus.has-focus;
    out property <bool> has-hover <=> i-touch.has-hover;
    out property <int> focus-id;

    private property <bool> i-has-focus: FocusState.has-focus(self.focus-id);

    callback key-pressed(KeyEvent) -> EventResult;
    callback key-released(KeyEvent) -> EventResult;
    callback focus-gained(FocusReason);
    callback focus-lost(FocusReason);
    callback activated();

    forward-focus: i-focus;

    changed i-has-focus => {
        if root.enabled && root.i-has-focus && !root.has-focus {
            self.focus();
        }
    }

    init => {
        self.focus-id = FocusState.create-focus-id();
    }

    i-touch := TouchArea {
        enabled: root.enabled;

        clicked => root.focus();
        double-clicked => root.activated();
    }

    i-focus := FocusScope {
        width: 0;

        init => {
            if force-focus {
                self.focus();
            }
        }
        key-pressed(event) => {
            if (event.text == Key.Return) || (event.text == Key.Space) {
                root.activated();
                accept
            } else {
                root.key-pressed(event)
            }
        }
        key-released(event) => root.key-released(event);
        focus-lost(reason) => root.focus-lost(reason);
        focus-gained(reason) => root.focus-gained(reason);
    }
}

export component ControlledFocusDomain {
    in-out property <bool> force-focus: true;
    in-out property <bool> force-exit-strategy: true;

    in property <length> exit-button-width <=> exit.width;
    in property <length> exit-button-height <=> exit.height;

    out property <int> domain-layer;
    out property <bool> domain-active: DomainState.current-layer == self.domain-layer;

    private property <int> last-domain: DomainState.last-layer;
    private property <bool> was-last: false;

    callback nav-front-forward();
    callback nav-end-backward();
    callback exited();
    callback domain-returned();

    public function enter-domain() {
        DomainState.enter-domain(self.domain-layer);
    }

    public function exit-domain() {
        DomainState.domain-exit(self.domain-layer);
    }

    forward-focus: pre-nav-lock;
    width: 100%;
    height: 100%;

    changed domain-active => {
        if domain-active {
            pre-nav-lock.focus();
            if was-last {
                was-last = false;
                domain-returned();
            }
        } else {
            self.exited();
        }
    }

    changed last-domain => {
        if last-domain == domain-layer {
            was-last = true;
        }
    }

    init => {
        self.domain-layer = DomainState.create-domain-id();

        if force-focus {
            enter-domain();
        }
    }

    pre-nav-lock := FocusScope {
        enabled: root.domain-active;
        width: 0;

        focus-gained(reason) => {
            if reason == FocusReason.tab-navigation {
                post-nav-lock.focus();
            } else {
                nav-front-forward();
            }
        }
    }

    if ApplicationState.debug-mode: Rectangle {
        width: 100%;
        height: 100%;
        background: domain-active ? red : transparent;
    }

    container := Rectangle {
        y: 0;
        clip: true;
        height: (root.domain-active && force-exit-strategy) ? root.height - exit-button-height : root.height;
        @children
    }

    exit := Button {
        visible: root.domain-active && root.force-exit-strategy;
        y: root.height - self.height;
        text: "Back";

        clicked => exit-domain();
    }

    post-nav-lock := FocusScope {
        enabled: root.domain-active;
        width: 0;

        focus-gained(reason) => {
            if reason == FocusReason.tab-navigation {
                pre-nav-lock.focus();
            } else if force-exit-strategy {
                exit.focus();
            } else {
                nav-end-backward();
            }
        }
    }
}
