import { ApplicationState, AccessibilitySettings, DebugSettings } from "../data/application_state.slint";

export global GlobalSizing {
    out property <length> button-height: 40px;
}

struct FocusBox {
    x: length,
    y: length,
    width: length,
    height: length,
    border-radius: length,
}

export global FocusState {
    out property <int> num-focuses: 1;
    out property <int> current-focus: 0;
    out property <int> force-focus-id;
    out property <bool> attempting-force-focus;
    out property <FocusBox> focus-box: { x: 0, y: 0, width: 0, height: 0, border-radius: 0 };

    private property <bool> i-force-complete;

    public function create-focus-id() -> int {
        self.num-focuses += 1;
        self.num-focuses - 1
    }

    public function force-focus(id: int) {
        self.force-focus-id = id;
        self.attempting-force-focus = true;
    }

    pure public function has-focus(id: int) -> bool {
        self.current-focus == id
    }

    public function set-focus-id(id: int) {
        self.current-focus = id;
    }

    public function force-complete(id: int) {
        if id == self.force-focus-id {
            self.attempting-force-focus = false;
        }
    }

    public function set-focus-box(focus-box: FocusBox) {
        self.focus-box = focus-box;
    }
}

export global DomainState {
    out property <int> num-domains: 1;
    out property <int> current-domain: 0;
    out property <int> last-domain: 0;

    out property <int> navigation-errors: 0;

    in-out property <FocusBox> focus-box: { x: 0, y: 0, width: 0, height: 0 };

    public function create-domain-id() -> int {
        num-domains += 1;
        num-domains - 1
    }

    public function enter-domain(domain-id: int) {
        self.last-domain = self.current-domain;
        self.current-domain = domain-id;
    }

    public function domain-exit(domain-id: int) -> bool {
        if domain-id == self.current-domain {
            enter-domain(self.last-domain);
            true
        }
        false
    }

    public function set-focus-coords(x: length, y: length, width: length, height: length) {
        if self.focus-box.x != x {
            self.focus-box.x = x;
        }
        if self.focus-box.y != y {
            self.focus-box.y = y;
        }
        if self.focus-box.width != width {
            self.focus-box.width = width;
        }
        if self.focus-box.height != height {
            self.focus-box.height = height;
        }
    }

    public function set-last-domain(id: int) {
        self.last-domain = id;
    }

    public function navigation-error-occured(id: int) {
        self.navigation-errors += 1;
    }
}

export component DebugHighlight {
    in property <brush> background <=> i-rect.border-color;

    width: 100%;
    height: 100%;

    i-rect := Rectangle {
        background: transparent;
        visible: ApplicationState.debug-mode && DebugSettings.debug-highlights;

        border-width: 2px;
        border-color: purple;
    }
}

export component FocusHoverRect inherits Rectangle {
    x: FocusState.focus-box.x;
    y: FocusState.focus-box.y;
    width: FocusState.focus-box.width;
    height: FocusState.focus-box.height;
    border-radius: FocusState.focus-box.border-radius;
    background: transparent;
    border-color: white;
    border-width: 2px;
}

export component AnimatedFocusHoverRect inherits FocusHoverRect {
    animate x, y, width, height, border-radius { duration: 60ms; }
}

export component ControlledFocusScope inherits Rectangle {
    in property <bool> force-focus: true;
    in property <bool> enabled <=> i-focus.enabled;

    out property <bool> has-focus <=> i-focus.has-focus;
    out property <bool> has-hover <=> i-touch.has-hover;
    out property <int> focus-id;

    private property <bool> state-attempting-force-focus: FocusState.attempting-force-focus;

    callback key-pressed(KeyEvent) -> EventResult;
    callback key-released(KeyEvent) -> EventResult;
    callback focus-gained(FocusReason);
    callback focus-lost(FocusReason);
    callback activated();
    callback init-ready();

    forward-focus: i-focus;

    function update-coords() {
        // TODO: tie to changes in geometry; https://github.com/slint-ui/slint/issues/7849
        FocusState.set-focus-box({
            x: root.absolute-position.x,
            y: root.absolute-position.y,
            width: root.width,
            height: root.height,
            border-radius: root.border-radius
        })
    }

    changed state-attempting-force-focus => {
        if state-attempting-force-focus && (FocusState.force-focus-id == root.focus-id) && root.enabled {
            root.focus();
            FocusState.force-complete(root.focus-id);
        }
    }

    init => {
        self.focus-id = FocusState.create-focus-id();
    }

    i-touch := TouchArea {
        enabled: root.enabled;

        clicked => root.focus();
        double-clicked => root.activated();
    }

    i-focus := FocusScope {
        width: 0;

        init => {
            if force-focus {
                self.focus();
            }
            root.init-ready();
        }
        key-pressed(event) => {
            if (event.text == Key.Return) || (event.text == Key.Space) {
                root.activated();
                accept
            } else {
                root.key-pressed(event)
            }
        }
        key-released(event) => root.key-released(event);
        focus-lost(reason) => root.focus-lost(reason);
        focus-gained(reason) => {
            if !FocusState.has-focus(root.focus-id) {
                update-coords();
                FocusState.set-focus-id(root.focus-id);
                root.focus-gained(reason);
            }
        }
    }
}

export component Button inherits Rectangle {
    in property <string> text <=> i-text.text;
    in property <TextHorizontalAlignment> text-alignment <=> i-text.horizontal-alignment;

    out property <bool> has-focus: FocusState.has-focus(i-focus.focus-id);
    out property <int> focus-id <=> i-focus.focus-id;

    private property <length> i-padding: 10px;

    callback focus-gained(FocusReason);
    callback focus-lost(FocusReason);
    callback init-ready();
    callback activated();

    border-radius: 2px;
    background: gray.darker(95%);
    forward-focus: i-focus;
    height: GlobalSizing.button-height;
    width: self.height * 2.5;

    HorizontalLayout {
        padding: i-padding;

        i-text := Text {
            color: white;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }

    i-focus := ControlledFocusScope {
        border-radius: root.border-radius;
        force-focus: false;

        focus-gained(FocusReason) => root.focus-gained(FocusReason);
        focus-lost(FocusReason) => root.focus-lost(FocusReason);
        activated => root.activated();
        init-ready => root.init-ready();
    }

    DebugHighlight {
        background: orange;
    }
}

export component FocusDomain inherits Rectangle {
    in property <bool> force-focus: true;
    in property <bool> force-exit-strategy: true;
    in property <length> exit-button-width <=> exit.width;

    out property <int> domain-id;
    out property <bool> domain-active: DomainState.current-domain == self.domain-id;

    private property <int> last-domain: DomainState.last-domain;
    private property <bool> was-last: false;

    callback nav-front-forward();
    callback nav-end-backward();
    callback exited();
    callback domain-returned();

    public function enter-domain() {
        DomainState.enter-domain(self.domain-id);
    }

    public function exit-domain() {
        DomainState.domain-exit(self.domain-id);
    }

    forward-focus: pre-nav-focus;
    width: 100%;
    height: 100%;

    changed domain-active => {
        if domain-active {
            DomainState.set-focus-coords(root.absolute-position.x, root.absolute-position.y, root.width, root.height);
            pre-nav-focus.focus();
            if was-last {
                was-last = false;
                // TODO: refocus the last selected focus when the domain was lost
                domain-returned();
            }
        } else {
            self.exited();
        }
    }

    changed last-domain => {
        if last-domain == domain-id {
            was-last = true;
        }
    }

    init => {
        self.domain-id = DomainState.create-domain-id();

        if force-focus {
            enter-domain();
        }
    }

    pre-nav-lock := FocusScope {
        width: 0;

        focus-gained(reason) => {
            DomainState.navigation-error-occured(root.domain-id);
            pre-nav-focus.focus();
        }
    }

    pre-nav-focus := FocusScope {
        enabled: root.domain-active;
        width: 0;

        focus-gained(reason) => {
            if reason == FocusReason.tab-navigation {
                post-nav-focus.focus();
            } else {
                nav-front-forward();
            }
        }
    }

    DebugHighlight {
        background: red;
        visible: domain-active;
    }

    container := Rectangle {
        y: 0;
        clip: true;
        height: (root.domain-active && force-exit-strategy) ? root.height - exit.height : root.height;

        @children
    }

    HorizontalLayout {
        alignment: center;
        y: root.height - exit.height;

        exit := Button {
            visible: root.domain-active && root.force-exit-strategy;
            text: "Back";

            activated => exit-domain();
        }
    }

    post-nav-focus := FocusScope {
        enabled: root.domain-active;
        width: 0;

        focus-gained(reason) => {
            if reason == FocusReason.tab-navigation {
                pre-nav-focus.focus();
            } else if force-exit-strategy {
                exit.focus();
            } else {
                nav-end-backward();
            }
        }
    }

    post-nav-lock := FocusScope {
        width: 0;

        focus-gained(reason) => {
            DomainState.navigation-error-occured(root.domain-id);
            pre-nav-focus.focus();
        }
    }
}

export global ComboBoxState {
    in property <string> current-value;
    in property <string> title;

    out property <[string]> model;
    public function set-model(model: [string]) {
        self.model = model;
    }

    out property <bool> visible: false;
    public function show-selection-box() {
        self.visible = true;
    }

    out property <FocusBox> focus-box;
    public function set-focus-coords(x: length, y: length, width: length, height: length) {
        if self.focus-box.x != x {
            self.focus-box.x = x;
        }
        if self.focus-box.y != y {
            self.focus-box.y = y;
        }
        if self.focus-box.width != width {
            self.focus-box.width = width;
        }
        if self.focus-box.height != height {
            self.focus-box.height = height;
        }
    }

    out property <bool> selection-made;
    out property <string> selection-value;
    out property <int> selection-index;

    in property <int> domain-id;

    public function make-selection(value: string, index: int) {
        self.selection-made = true;
        self.selection-value = value;
        self.selection-index = index;
    }

    public function complete-selection() {
        DomainState.domain-exit(self.domain-id);
        self.selection-made = false;
        self.visible = false;
    }
}

component ComboBoxSelectionBoxButton inherits Button {
    in property <bool> has-selection;
    width: self.height * 4;

    HorizontalLayout {
        padding: 6px;
        alignment: start;

        VerticalLayout {
            alignment: center;

            Rectangle {
                width: 6px;
                height: 90%;
                background: white;
                visible: has-selection;
                border-radius: 2px;
            }
        }
    }
}

export component ComboBoxSelectionBox inherits FocusDomain {
    in-out property <string> current-value: ComboBoxState.current-value;

    private property <int> first-model-focus-id;
    private property <int> last-model-focus-id;
    private property <bool> i-has-domain: ComboBoxState.visible;

    force-exit-strategy: false;
    background: black.transparentize(7.5%);
    // TODO: add animated version that fades in

    width: 100%;
    height: 100%;
    border-radius: 2px;

    function open() {
        if i-has-domain {
            root.focus();
        }
    }

    changed i-has-domain => open();

    // TODO: nav functions broke somehow
    nav-front-forward => FocusState.force-focus(self.first-model-focus-id);
    nav-end-backward => FocusState.force-focus(self.last-model-focus-id);
    init => open();

    HorizontalLayout {
        padding: 5px;
        alignment: center;

        i-layout := VerticalLayout {
            spacing: 5px;
            alignment: center;

            Text {
                height: self.font-size + 20px;
                color: white;
                text: ComboBoxState.title;
                font-size: 25px;
                horizontal-alignment: left;
                vertical-alignment: center;
            }

            for model[i] in ComboBoxState.model: HorizontalLayout {
                alignment: center;

                ComboBoxSelectionBoxButton {
                    text: model;
                    has-selection: root.current-value == model;

                    init-ready => {
                        if i == 0 {
                            root.first-model-focus-id = self.focus-id;
                        }
                        if i == (ComboBoxState.model.length - 1) {
                            root.last-model-focus-id = self.focus-id;
                        }
                    }

                    activated => {
                        ComboBoxState.domain-id = root.domain-id;
                        ComboBoxState.make-selection(model, i);
                    }
                }
            }
        }
    }
}

export component ComboBox inherits Button {
    in property <[string]> model;
    in property <string> title;

    in-out property <int> current-index: 0;
    in-out property <string> current-value: model[current-index];
    out property <bool> open;

    private property <bool> selection-state-made: ComboBoxState.selection-made;
    private property <int> domain-state-real-last;

    text: current-value;
    text-alignment: left;

    i-arrow := Rectangle {
        y: root.height / 2 - self.height / 2;
        x: root.width - self.width - (root.height - self.height) / 2;
        width: 12px;
        height: self.width;

        Path {
            fill: grey;
            viewbox-height: parent.height / 1px;
            viewbox-width: parent.width / 1px;

            MoveTo {
                x: 0;
                y: 0;
            }

            LineTo {
                x: parent.viewbox-width / 2;
                y: parent.viewbox-height;
            }

            LineTo {
                x: parent.viewbox-width;
                y: 0;
            }
        }
    }

    changed selection-state-made => {
        if open {
            root.current-index = ComboBoxState.selection-index;
            root.current-value = ComboBoxState.selection-value;
            ComboBoxState.complete-selection();
            DomainState.set-last-domain(root.domain-state-real-last);
            root.open = false;
        }
    }

    function activate-open() {
        root.domain-state-real-last = DomainState.last-domain;
        ComboBoxState.title = root.title;
        ComboBoxState.current-value = root.current-value;
        ComboBoxState.set-focus-coords(self.absolute-position.x, self.absolute-position.y, self.width, self.height);
        ComboBoxState.set-model(self.model);
        ComboBoxState.show-selection-box();
        root.open = true;
    }

    activated => activate-open();
}

component ToggleBoxInner inherits Rectangle {
    in property <brush> i-background: self.background;
    in property <length> i-x <=> i-switch.x;
    in property <bool> var;
    in property <bool> accessible-mode: true;

    private property <length> switch-padding: 4px;

    background: (accessible-mode || !var) ? grey.darker(80%) : green;
    border-radius: self.height / 2;
    clip: true;

    i-switch := Rectangle {
        border-radius: self.height / 1.5;
        background: lightgray;
        width: root.width * 65% - root.switch-padding - root.border-width;
        x: var ? root.width - root.border-width - root.switch-padding - self.width : root.border-width + root.switch-padding;
        y: root.height / 2 - self.height / 2;
        height: root.height - root.switch-padding * 2 - root.border-width * 2;

        if accessible-mode: Rectangle {
            off-indicator := Rectangle {
                x: parent.width - self.width - on-indicator.x;
                width: on-indicator.width;
                height: self.width;
                border-radius: self.height / 2;
                background: red;
            }

            on-indicator := Rectangle {
                visible: true;
                x: -(root.width - parent.width) / 2 - root.switch-padding / 2;
                width: 10px;
                height: self.width;
                border-radius: self.height / 2;
                background: green;
            }
        }
    }
}

component AnimatedToggleBoxInner inherits ToggleBoxInner {
    animate i-x, i-background { duration: 60ms; }
}

export component ToggleBox inherits Button {
    in property <bool> var;
    in property <bool> force-accessible-enaled: false;

    private property <bool> accessible-mode: force-accessible-enaled || AccessibilitySettings.accessible-switches;

    callback toggled(bool);
    activated => toggled(!var);

    background: transparent;
    border-radius: self.height / 2;
    width: self.height * 1.8;

    if !AccessibilitySettings.animations-enabled: ToggleBoxInner {
        var: root.var;
        border-radius: root.border-radius;
        accessible-mode: root.accessible-mode;
    }
    if AccessibilitySettings.animations-enabled: AnimatedToggleBoxInner {
        var: root.var;
        border-radius: root.border-radius;
        accessible-mode: root.accessible-mode;
    }
}

export component ModuleDebug inherits VerticalLayout {
    Text {
        color: purple;
        text: "FocusState";
    }

    Text {
        color: white;
        text: FocusState.num-focuses;
    }

    Text {
        color: white;
        text: FocusState.current-focus;
    }

    Text {
        color: white;
        text: "{" + FocusState.focus-box.x / 1px + ", " + FocusState.focus-box.y / 1px + "}";
    }

    Text {
        color: white;
        text: "{" + FocusState.focus-box.width / 1px + ", " + FocusState.focus-box.height / 1px + "}";
    }

    Text {
        color: purple;
        text: "DomainState";
    }

    Text {
        color: white;
        text: DomainState.num-domains;
    }

    Text {
        color: white;
        text: DomainState.current-domain;
    }

    Text {
        color: white;
        text: DomainState.last-domain;
    }

    Text {
        color: white;
        text: "{" + DomainState.focus-box.x / 1px + ", " + DomainState.focus-box.y / 1px + "}";
    }

    Text {
        color: white;
        text: "{" + DomainState.focus-box.width / 1px + ", " + DomainState.focus-box.height / 1px + "}";
    }

    Text {
        color: red;
        text: DomainState.navigation-errors;
    }
}
