import { SCarData } from "../data/car_data.slint";
import { Button, GridBox } from "std-widgets.slint";

export global DebugMenuState {
    callback debug-suspend();
    callback can-write-test();
}

export component DebugMenuWidget inherits Rectangle {
    forward-focus: suspend-button;
    background: purple;

    GridLayout {
        padding: 10px;
        spacing: 10px;

        suspend-button := Button {
            text: "Suspend";

            clicked => {
                DebugMenuState.debug-suspend();
            }
        }

        write-test-button := Button {
            text: "CAN Write Test";

            clicked => {
                DebugMenuState.can-write-test();
            }
        }
    }
}
