import { SCarData } from "../data/car_data.slint";
import { Button, GridBox } from "std-widgets.slint";

export global DebugMenuState {
    callback debug-suspend();
}

export component DebugMenuWidget inherits Rectangle {
    background: purple;

    GridLayout {
        padding: 10px;
        spacing: 10px;

        suspend-button := Button {
            text: "Suspend";

            clicked => {
                DebugMenuState.debug-suspend();
            }
        }
    }
}
