import { SCarData } from "../data/car_data.slint";
import { GridBox } from "std-widgets.slint";
import { Button, ComboBox } from "core.slint";
import { ModuleDebug as FocusDebug} from "core.slint";
import { ModuleDebug as ApplicationStateDebug} from "../data/application_state.slint";

export global DebugMenuState {
    callback debug-suspend();
    callback can-write-test();
}

export component DebugMenuWidget {
    forward-focus: suspend-button;

    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        GridLayout {
            suspend-button := Button {
                text: "Suspend";

                activated => {
                    DebugMenuState.debug-suspend();
                }
            }

            write-test-button := Button {
                text: "CAN Write Test";

                activated => {
                    DebugMenuState.can-write-test();
                }
            }
        }

        ComboBox {
            current-index: 0;
            model: ["test1", "test2", "test3"];
        }
    }
}

export component DebugOverlay {
    x: 0;
    y: 20px;
    VerticalLayout {
        Text {
            color: purple;
            text: "UI DEBUG";
        }

        ApplicationStateDebug { }

        FocusDebug { }
    }
}
