import { ApplicationState, AccessibilitySettings } from "../application/application_state.slint";

struct FocusBox {
    x: length,
    y: length,
    width: length,
    height: length,
}

export global FocusState {
    out property <int> num-focuses: 1;
    out property <int> current-focus: 0;
    in-out property <FocusBox> focus-box: { x: 0, y: 0, width: 0, height: 0 };

    public function create-focus-id() -> int {
        num-focuses += 1;
        num-focuses - 1
    }

    public function force-focus(id: int) {
        current-focus = id;
    }

    pure public function has-focus(id: int) -> bool {
        current-focus == id
    }

    public function set-focus-coords(x: length, y: length, width: length, height: length) {
        if self.focus-box.x != x {
            self.focus-box.x = x;
        }
        if self.focus-box.y != y {
            self.focus-box.y = y;
        }
        if self.focus-box.width != width {
            self.focus-box.width = width;
        }
        if self.focus-box.height != height {
            self.focus-box.height = height;
        }
    }
}

export global DomainState {
    out property <int> num-domains: 1;
    out property <int> current-domain: 0;
    out property <int> last-domain: 0;

    in-out property <FocusBox> focus-box: { x: 0, y: 0, width: 0, height: 0 };

    public function create-domain-id() -> int {
        num-domains += 1;
        num-domains - 1
    }

    public function enter-domain(domain-layer: int) {
        self.last-domain = self.current-domain;
        self.current-domain = domain-layer;
    }

    public function domain-exit(domain-layer: int) -> bool {
        if domain-layer == self.current-domain {
            enter-domain(self.last-domain);
            true
        }
        false
    }

    public function set-focus-coords(x: length, y: length, width: length, height: length) {
        if self.focus-box.x != x {
            self.focus-box.x = x;
        }
        if self.focus-box.y != y {
            self.focus-box.y = y;
        }
        if self.focus-box.width != width {
            self.focus-box.width = width;
        }
        if self.focus-box.height != height {
            self.focus-box.height = height;
        }
    }
}

component AnimatedHoverRect inherits Rectangle {
    background: transparent;
    border-color: white;
    border-width: 2px;
    border-radius: 2px;

    animate x, y, width, height { duration: 60ms; }
}

export component AnimatedFocusHoverRect inherits AnimatedHoverRect {
    x: FocusState.focus-box.x;
    y: FocusState.focus-box.y;
    width: FocusState.focus-box.width;
    height: FocusState.focus-box.height;
}

export component AnimatedFocusDomainRect inherits AnimatedHoverRect {
    x: DomainState.focus-box.x;
    y: DomainState.focus-box.y;
    width: DomainState.focus-box.width;
    height: DomainState.focus-box.height;
}

component HoverRect inherits Rectangle {
    background: transparent;
    border-color: white;
    border-width: 2px;
    border-radius: 2px;
}

export component FocusHoverRect inherits HoverRect {
    x: FocusState.focus-box.x;
    y: FocusState.focus-box.y;
    width: FocusState.focus-box.width;
    height: FocusState.focus-box.height;
}

export component FocusDomainRect inherits HoverRect {
    x: DomainState.focus-box.x;
    y: DomainState.focus-box.y;
    width: DomainState.focus-box.width;
    height: DomainState.focus-box.height;
}

export component ControlledFocusScope inherits Rectangle {
    in-out property <bool> force-focus: true;
    in-out property <bool> enabled <=> i-focus.enabled;

    out property <bool> has-focus <=> i-focus.has-focus;
    out property <bool> has-hover <=> i-touch.has-hover;
    out property <int> focus-id;

    private property <bool> i-has-focus: FocusState.has-focus(self.focus-id);

    callback key-pressed(KeyEvent) -> EventResult;
    callback key-released(KeyEvent) -> EventResult;
    callback focus-gained(FocusReason);
    callback focus-lost(FocusReason);
    callback activated();

    forward-focus: i-focus;

    function update-coords() {
        if (FocusState.focus-box.x != root.absolute-position.x) || (FocusState.focus-box.y != root.absolute-position.y) || (FocusState.focus-box.width != root.width) || (FocusState.focus-box.height != root.height) {
            FocusState.set-focus-coords(root.absolute-position.x, root.absolute-position.y, root.width, root.height);
        }
    }

    changed i-has-focus => {
        if root.enabled && root.i-has-focus && !root.has-focus {
            i-focus.focus();
        }
    }

    init => {
        self.focus-id = FocusState.create-focus-id();
    }

    i-touch := TouchArea {
        enabled: root.enabled;

        clicked => root.focus();
        double-clicked => root.activated();
    }

    i-focus := FocusScope {
        width: 0;

        init => {
            if force-focus {
                self.focus();
            }
        }
        key-pressed(event) => {
            if (event.text == Key.Return) || (event.text == Key.Space) {
                root.activated();
                accept
            } else {
                root.key-pressed(event)
            }
        }
        key-released(event) => root.key-released(event);
        focus-lost(reason) => root.focus-lost(reason);
        focus-gained(reason) => {
            if !root.i-has-focus {
                update-coords();
                FocusState.force-focus(root.focus-id);
                root.focus-gained(reason);
            }
        }
    }
}

export component ControlledFocusDomain inherits Rectangle {
    in-out property <bool> force-focus: true;
    in-out property <bool> force-exit-strategy: true;

    in property <length> exit-button-width <=> exit.width;
    in property <length> exit-button-height <=> exit.height;

    out property <int> domain-layer;
    out property <bool> domain-active: DomainState.current-domain == self.domain-layer;

    private property <int> last-domain: DomainState.last-domain;
    private property <bool> was-last: false;

    callback nav-front-forward();
    callback nav-end-backward();
    callback exited();
    callback domain-returned();

    public function enter-domain() {
        DomainState.enter-domain(self.domain-layer);
    }

    public function exit-domain() {
        DomainState.domain-exit(self.domain-layer);
    }

    forward-focus: pre-nav-lock;
    width: 100%;
    height: 100%;

    changed domain-active => {
        if domain-active {
            DomainState.set-focus-coords(root.absolute-position.x, root.absolute-position.y, root.width, root.height);
            pre-nav-lock.focus();
            if was-last {
                was-last = false;
                domain-returned();
            }
        } else {
            self.exited();
        }
    }

    changed last-domain => {
        if last-domain == domain-layer {
            was-last = true;
        }
    }

    init => {
        self.domain-layer = DomainState.create-domain-id();

        if force-focus {
            enter-domain();
        }
    }

    pre-nav-lock := FocusScope {
        enabled: root.domain-active;
        width: 0;

        focus-gained(reason) => {
            if reason == FocusReason.tab-navigation {
                post-nav-lock.focus();
            } else {
                nav-front-forward();
            }
        }
    }

    if ApplicationState.debug-mode: Rectangle {
        width: 100%;
        height: 100%;
        background: red;
        visible: domain-active;
    }

    container := Rectangle {
        y: 0;
        clip: true;
        height: (root.domain-active && force-exit-strategy) ? root.height - exit-button-height : root.height;
        @children
    }

    exit := Rectangle {
        forward-focus: i-exit-focus;
        visible: root.domain-active && root.force-exit-strategy;
        y: root.height - self.height;

        height: 25px;
        width: 40px;

        background: gray;

        Text {
            color: white;
            text: "Back";
        }

        i-exit-focus := ControlledFocusScope {

            force-focus: false;
            activated => exit-domain();
        }
    }

    post-nav-lock := FocusScope {
        enabled: root.domain-active;
        width: 0;

        focus-gained(reason) => {
            if reason == FocusReason.tab-navigation {
                pre-nav-lock.focus();
            } else if force-exit-strategy {
                exit.focus();
            } else {
                nav-end-backward();
            }
        }
    }
}

export component Button inherits Rectangle {
    in property <string> text <=> i-text.text;

    private property <length> i-padding: 10px;

    callback focus-gained(FocusReason);
    callback focus-lost(FocusReason);
    callback activated();

    border-radius: 2px;
    background: gray;
    forward-focus: i-focus;

    HorizontalLayout {
        pad-left := Rectangle {
            width: i-padding;
        }

        i-text := Text {
            color: white;
            text: "Back";
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        pad-right := Rectangle {
            width: i-padding;
        }
    }

    i-focus := ControlledFocusScope {
        force-focus: false;

        focus-gained(FocusReason) => root.focus-gained(FocusReason);
        focus-lost(FocusReason) => root.focus-lost(FocusReason);
        activated => root.activated();
    }
}

export component ModuleDebug inherits VerticalLayout {
    Text {
        color: purple;
        text: "FocusState";
    }

    Text {
        color: white;
        text: FocusState.num-focuses;
    }

    Text {
        color: white;
        text: FocusState.current-focus;
    }

    Text {
        color: white;
        text: FocusState.focus-box.x / 1px;
    }

    Text {
        color: white;
        text: FocusState.focus-box.y / 1px;
    }

    Text {
        color: white;
        text: FocusState.focus-box.width / 1px;
    }

    Text {
        color: white;
        text: FocusState.focus-box.height / 1px;
    }

    Text {
        color: purple;
        text: "DomainState";
    }

    Text {
        color: white;
        text: DomainState.num-domains;
    }

    Text {
        color: white;
        text: DomainState.current-domain;
    }

    Text {
        color: white;
        text: DomainState.focus-box.x / 1px;
    }

    Text {
        color: white;
        text: DomainState.focus-box.y / 1px;
    }

    Text {
        color: white;
        text: DomainState.focus-box.width / 1px;
    }

    Text {
        color: white;
        text: DomainState.focus-box.height / 1px;
    }
}
