import { Slider } from "std-widgets.slint";

export struct MapTile { x: length, y: length, tile-image: image}

export global NavMapProperties {
    //? TODO: make a flag to detect if the map widget is visible, and only perform network requests based on that
    callback flicked(length, length);
    callback zoom-changed(float);
    callback zoom-in(length, length);
    callback zoom-out(length, length);
    callback link-clicked();

    in property <length> visible_width;
    in property <length> visible_height;

    in-out property <length> viewport-x;
    in-out property <length> viewport-y;
    in-out property <length> viewport-width;
    in-out property <length> viewport-height;

    in-out property <float> zoom;

    in property <[MapTile]> tiles;

    public function set_viewport(ox: length, oy: length, width: length, height: length) {
        viewport-x = ox;
        viewport-y = oy;
        viewport-width = width;
        viewport-height = height;
    }
}

export component NavigationMap inherits Rectangle {
    background: grey;
    clip: true;

    VerticalLayout {
        spacing: 10px;

        fli := Flickable {
            init => {
                NavMapProperties.visible_width = self.width;
                NavMapProperties.visible_height = self.height;
            }
            changed width => {
                NavMapProperties.visible_width = self.width;
            }
            changed height => {
                NavMapProperties.visible_height = self.height;
            }

            viewport-x <=> NavMapProperties.viewport-x;
            viewport-y <=> NavMapProperties.viewport-y;
            viewport-width <=> NavMapProperties.viewport-width;
            viewport-height <=> NavMapProperties.viewport-height;

            for tile in NavMapProperties.tiles: Image {
                x: tile.x;
                y: tile.y;
                source: tile.tile-image;
            }

            flicked => {
                NavMapProperties.flicked(self.viewport-x, self.viewport-y);
            }

            TouchArea {
                scroll-event(event) => {
                    if event.delta-y > 0 {
                        NavMapProperties.zoom-in(self.mouse-x + parent.viewport-x, self.mouse-y + parent.viewport-y);
                        return accept;
                    } else if event.delta-y < 0 {
                        NavMapProperties.zoom-out(self.mouse-x + parent.viewport-x, self.mouse-y + parent.viewport-y);
                        return accept;
                    }
                    return reject;
                }
            }
        }

        HorizontalLayout {
            Slider {
                value: NavMapProperties.zoom;

                minimum: 1;
                maximum: 19;
                released => {
                    NavMapProperties.zoom-changed(self.value);
                }
            }
        }
    }
}
