import { Slider } from "std-widgets.slint";

export struct MapTile { x: length, y: length, tile-image: image}

export global NavMapProperties {
    //? TODO: make a flag to detect if the map widget is visible, and only perform network reads based on that
    callback flicked(length, length);
    callback zoom-changed(float);
    callback zoom-in(length, length);
    callback zoom-out(length, length);
    callback link-clicked();

    out property <length> visible_width;
    out property <length> visible_height;

    out property <length> viewport-x;
    out property <length> viewport-y;
    out property <length> viewport-width;
    out property <length> viewport-height;

    in-out property <float> zoom;

    in property <[MapTile]> tiles;

    public function set_viewport(ox: length, oy: length, width: length, height: length) {
        viewport-x = ox;
        viewport-y = oy;
        viewport-width = width;
        viewport-height = height;
    }
}

export component NavigationMap {
    VerticalLayout {
        spacing: 10px;

        Flickable {
            viewport-x: NavMapProperties.viewport-x;
            viewport-y: NavMapProperties.viewport-y;
            viewport-width: NavMapProperties.viewport-width;
            viewport-height: NavMapProperties.viewport-height;

            for tile in NavMapProperties.tiles: Image {
                x: tile.x;
                y: tile.y;
                source: tile.tile-image;
            }

            flicked => {
                NavMapProperties.flicked(self.viewport-x, self.viewport-y);
            }

            TouchArea {
                scroll-event(event) => {
                    if event.delta-y > 0 {
                        NavMapProperties.zoom-in(self.mouse-x + parent.viewport-x, self.mouse-y + parent.viewport-y);
                        return accept;
                    } else if event.delta-y < 0 {
                        NavMapProperties.zoom-out(self.mouse-x + parent.viewport-x, self.mouse-y + parent.viewport-y);
                        return accept;
                    }
                    return reject;
                }
            }
        }

        HorizontalLayout {
            Slider {
                value: NavMapProperties.zoom;

                minimum: 1;
                maximum: 19;
                released => {
                    NavMapProperties.zoom-changed(self.value);
                }
            }
        }
    }
}
