import { SCarData } from "../data/car_data.slint";
import { SymbolProperties } from "../themes/main_symbol_properties.slint";

export component RoadIndicatorWidget inherits Rectangle {
    background: transparent;

    in property <float> lane-top-y: self.height / 2.4phx;
    in property <float> lane-bottom-y: self.height / 1phx - self.height / 20phx;

    property <float> top-gradient: 1 - (lane-top-y / self.height * 1phx);
    property <float> bottom-gradient: 1 - (lane-bottom-y / self.height * 1phx);

    in property <float> lane-top-width: self.width / 3.2phx;
    in property <float> lane-bottom-width: self.width / 1.2phx;
    in property <float> lane-thickness: 3.5;

    in property <brush> left-lane-fill: brush-fill-normal;
    in property <brush> right-lane-fill: brush-fill-normal;

    property <float> top-x: self.width / 2phx - lane-top-width / 2;
    property <float> bottom-x: self.width / 2phx - lane-bottom-width / 2;

    in property <color> lane-color: #8a8787;

    property <brush> brush-fill-warn: @linear-gradient(0deg, #00000000 bottom-gradient, SymbolProperties.symbol_color_yellow 20%, SymbolProperties.symbol_color_yellow 35%, #00000000 top-gradient);
    property <brush> brush-fill-warn-approach: @linear-gradient(0deg, #00000000 bottom-gradient, SymbolProperties.symbol_color_yellow 20%, lane-color 25%, #00000000 top-gradient);
    property <brush> brush-fill-normal: @linear-gradient(0deg, #00000000 bottom-gradient, lane-color 20%, lane-color 35%, #00000000 top-gradient);

    property <bool> bsd_enabled: SCarData.rcta_enabled.value;

    lane-left := Path {
        viewbox-height: parent.height / 1phx;
        viewbox-width: parent.width / 1phx;

        fill: root.left-lane-fill;

        MoveTo {
            x: root.bottom-x;
            y: root.lane-bottom-y;
        }

        LineTo {
            x: root.top-x;
            y: root.lane-top-y;
        }

        LineTo {
            x: root.top-x + root.lane-thickness;
            y: root.lane-top-y;
        }

        LineTo {
            x: root.bottom-x + root.lane-thickness;
            y: root.lane-bottom-y;
        }

        property <bool> bsd_left_adjacent: SCarData.bsd_left_adjacent.value;
        property <bool> bsd_left_approaching: SCarData.bsd_left_adjacent.value;
        property <bool> rcta_left: SCarData.rcta_left.value;
        property <bool> left_turn_signal: SCarData.left_turn_signal_enabled.value;

        states [
            active when bsd_enabled && bsd_left_adjacent: {
                fill: brush-fill-warn;
            }
            active when bsd_enabled && bsd_left_approaching: {
                fill: brush-fill-warn-approach;
            }
            active when bsd_enabled && bsd_left_approaching && left_turn_signal: {
                fill: brush-fill-warn-approach; // TODO: animate flashing
            }
        ]
    }

    lane-right := Path {
        viewbox-height: parent.height / 1phx;
        viewbox-width: parent.width / 1phx;

        fill: root.right-lane-fill;

        MoveTo {
            x: parent.viewbox-width - root.bottom-x;
            y: root.lane-bottom-y;
        }

        LineTo {
            x: parent.viewbox-width - root.top-x;
            y: root.lane-top-y;
        }

        LineTo {
            x: parent.viewbox-width - root.top-x - root.lane-thickness;
            y: root.lane-top-y;
        }

        LineTo {
            x: parent.viewbox-width - root.bottom-x - root.lane-thickness;
            y: root.lane-bottom-y;
        }

        property <bool> bsd_right_adjacent: SCarData.bsd_right_adjacent.value;
        property <bool> bsd_right_approaching: SCarData.bsd_right_adjacent.value;
        property <bool> rcta_right: SCarData.rcta_right.value;
        property <bool> right_turn_signal: SCarData.right_turn_signal_enabled.value;

        states [
            active when bsd_enabled && bsd_right_adjacent: {
                fill: brush-fill-warn;
            }
            active when bsd_enabled && bsd_right_approaching: {
                fill: brush-fill-warn-approach;
            }
            active when bsd_enabled && bsd_right_approaching && right_turn_signal: {
                fill: brush-fill-warn-approach; // TODO: animate flashing
            }
        ]
    }
}
