import { ApplicationState, AccessibilitySettings, DebugSettings } from "../data/application_state.slint";
import { SUnitSystem } from "../data/units.slint";
import { ThemeSelectorWidget } from "../themes/themes.slint";
import { Button, FocusDomain, ComboBox, ToggleBox } from "core.slint";

export global UserSettings { } // TODO

export component SettingsMenu inherits FocusDomain {
    force-exit-strategy: false;

    nav-front-forward => theme-setting-widget.focus();
    nav-end-backward => exit-button.focus();

    // forward-focus: theme-setting-widget;

    init => {
        theme-setting-widget.focus();
    }

    VerticalLayout {
        alignment: center;
        spacing: 15px;

        theme-setting-widget := ThemeSelectorWidget {
            width: 100%;
            height: 30px;
        }

        user-unit-setting := HorizontalLayout {
            height: 30px;
            alignment: center;
            padding: 2px;

            Text {
                vertical-alignment: center;
                text: "Units: ";
            }

            ComboBox {
                model: ["USCS", "SI"];
                width: 100px;

                current-value: ApplicationState.user-unit == SUnitSystem.USCS ? "USCS" : "SI";

                changed current-value => {
                    ApplicationState.update-user-unit(self.current-value == "USCS" ? SUnitSystem.USCS : SUnitSystem.SI);
                }
            }
        }

        accessibility-animation-setting := HorizontalLayout {
            alignment: center;
            padding: 2px;

            Text {
                vertical-alignment: center;
                text: "Animations: ";
            }

            ToggleBox {
                var: AccessibilitySettings.animations-enabled;
                toggled(val) => AccessibilitySettings.update-animations-enabled(val);
            }
        }

        if ApplicationState.virtual_cluster: simulation-toggle-button := HorizontalLayout {
            alignment: center;
            padding: 2px;

            Text {
                vertical-alignment: center;
                text: "Simulation Running: ";
            }

            ToggleBox {
                var: ApplicationState.simulation-running;
                toggled(val) => ApplicationState.update_simulation_running(val);
            }
        }

        if ApplicationState.debug-mode: VerticalLayout {
            spacing: parent.spacing;
            alignment: parent.alignment;

            HorizontalLayout {
                height: 30px;
                alignment: center;
                padding: 2px;

                Text {
                    vertical-alignment: center;
                    text: "Debug Highlights: ";
                }

                ToggleBox {
                    var: DebugSettings.debug-highlights;
                    toggled(val) => DebugSettings.update-debug-highlights(val);
                }
            }

            HorizontalLayout {
                height: 30px;
                alignment: center;
                padding: 2px;

                Text {
                    vertical-alignment: center;
                    text: "Debug Overlay: ";
                }

                ToggleBox {
                    var: DebugSettings.debug-overlay-enabled;
                    toggled(val) => DebugSettings.update-debug-overlay-enabled(val);
                }
            }
        }

        HorizontalLayout {
            height: 30px;
            alignment: center;

            exit-button := Button {
                text: "Exit";

                activated => {
                    ApplicationState.settings-menu-visible = false;
                }
            }
        }
    }
}
