import { ApplicationState, AccessibilitySettings, DebugSettings, GeneralSettings } from "../data/application_state.slint";
import { SUnitSystem } from "../data/units.slint";
import { GlobalThemeData } from "../themes/themes.slint";
import { Button, FocusDomain, ComboBox, ToggleBox, DebugHighlight } from "core.slint";

export global SettingsState { }

component DecorationBar inherits Rectangle {
    height: 2px;
    background: white;
}

component SettingBarLabelTextBase inherits Text {
    font-size: 20px;
    horizontal-alignment: left;
    vertical-alignment: center;
}

component SettingBarLabelTextAnimated inherits SettingBarLabelTextBase {
    animate x { duration: 50ms; }
}

component SettingBarLabelText {
    in property <length> i-x;
    in property <string> text;
    if AccessibilitySettings.animations-enabled: SettingBarLabelTextAnimated {
        x: root.i-x;
        text: root.text;
    }
    if !AccessibilitySettings.animations-enabled: SettingBarLabelTextBase {
        x: root.i-x;
        text: root.text;
    }
}

component SettingsBarLabelBase {
    in property <string> text <=> i-label.text;
    in property <bool> has-focus: false;
    in-out property <length> selector-x: has-focus ? 6px : 0;

    i-selection-indicator := Rectangle {
        x: 0;
        width: root.selector-x;
        height: 6px;
        border-radius: 2px;
        background: white;
    }

    i-label := SettingBarLabelText {
        x: 0;
        i-x: root.has-focus ? 10px : 0;
    }
}

component SettingsBarLabelBaseAnimated inherits SettingsBarLabelBase {
    animate selector-x { duration: 50ms; }
}

component SettingBarLabel inherits Rectangle {
    in property <string> text;
    in property <bool> has-focus: false;

    if AccessibilitySettings.animations-enabled: SettingsBarLabelBaseAnimated {
        x: 0;
        text: root.text;
        has-focus: root.has-focus;
    }
    if !AccessibilitySettings.animations-enabled: SettingsBarLabelBase {
        x: 0;
        text: root.text;
        has-focus: root.has-focus;
    }

    DebugHighlight { }
}

component SettingBar inherits Rectangle {
    in property <string> label <=> i-label.text;
    in property <bool> has-focus <=> i-label.has-focus;

    property <length> i-padding: 5px;

    width: 500px;

    VerticalLayout {
        alignment: center;
        padding: i-padding;

        HorizontalLayout {
            i-label := SettingBarLabel { }

            i-container := Rectangle {
                DebugHighlight {
                    background: blue;
                }

                HorizontalLayout {
                    spacing: 5px;
                    alignment: end;

                    @children
                }
            }
        }
    }

    DebugHighlight {
        background: yellow;
    }
}

// TODO: implement pages for better settings organization
component SettingsPage inherits PopupWindow {
    width: 1920px;
    close-policy: PopupClosePolicy.no-auto-close;
    height: 1080px;

    Rectangle {
        width: 100%;
        height: 100%;
        background: red;
    }
}

export component SettingsMenu inherits FocusDomain {
    force-exit-strategy: false;

    nav-front-forward => theme-selection-box.focus();
    nav-end-backward => exit-button.focus();
    init => theme-selection-box.focus();

    width: 2400px;
    height: 900px;
    HorizontalLayout {
        alignment: center;

        VerticalLayout {
            alignment: center;
            spacing: 10px;

            DecorationBar { }

            HorizontalLayout {
                alignment: center;

                VerticalLayout {
                    spacing: parent.spacing;
                    alignment: parent.alignment;

                    SettingBar {
                        label: "Theme";

                        has-focus: theme-selection-box.has-focus;
                        theme-selection-box := ComboBox {
                            title: "Theme";
                            model: GlobalThemeData.themes;

                            current-value <=> GlobalThemeData.current-theme;

                            changed current-value => {
                                GlobalThemeData.update_current_theme(self.current-value);
                            }
                        }
                    }
                }
            }

            DecorationBar { }

            VerticalLayout {
                spacing: parent.spacing;
                alignment: parent.alignment;

                HorizontalLayout {
                    alignment: parent.alignment;

                    SettingBar {
                        label: "Units";

                        has-focus: units-i-element.has-focus;
                        units-i-element := ComboBox {
                            title: "Units";
                            model: ["USCS", "SI"];

                            current-value: ApplicationState.user-unit == SUnitSystem.USCS ? "USCS" : "SI";

                            changed current-value => {
                                ApplicationState.update-user-unit(self.current-value == "USCS" ? SUnitSystem.USCS : SUnitSystem.SI);
                            }
                        }
                    }
                }

                HorizontalLayout {
                    alignment: parent.alignment;

                    SettingBar {
                        label: "Disable Hill Assist Warning";

                        has-focus: disable-hill-assist-i-element.has-focus;
                        disable-hill-assist-i-element := ToggleBox {
                            var: GeneralSettings.disable-hill-assist;
                            toggled(val) => GeneralSettings.update-disable-hill-assist(val);
                        }
                    }
                }
            }

            DecorationBar { }

            VerticalLayout {
                spacing: parent.spacing;
                alignment: parent.alignment;
                HorizontalLayout {
                    alignment: parent.alignment;

                    SettingBar {
                        label: "Animations";
                        has-focus: animations-i-element.has-focus;
                        animations-i-element := ToggleBox {
                            var: AccessibilitySettings.animations-enabled;
                            toggled(val) => AccessibilitySettings.update-animations-enabled(val);
                        }
                    }
                }

                HorizontalLayout {
                    alignment: parent.alignment;

                    SettingBar {
                        label: "Alternate Switches";
                        has-focus: accessible-switches-i-element.has-focus;
                        accessible-switches-i-element := ToggleBox {
                            force-accessible-enaled: true;
                            var: AccessibilitySettings.accessible-switches;
                            toggled(val) => AccessibilitySettings.update-accessible-switches(val);
                        }
                    }
                }
            }

            if ApplicationState.virtual_cluster: VerticalLayout {
                spacing: parent.spacing;
                alignment: parent.alignment;

                DecorationBar { }

                HorizontalLayout {
                    alignment: parent.alignment;
                    SettingBar {
                        label: "Simulation Running";
                        has-focus: simulation-toggle-i-element.has-focus;

                        simulation-toggle-i-element := ToggleBox {
                            var: ApplicationState.simulation-running;
                            toggled(val) => ApplicationState.update_simulation_running(val);
                        }
                    }
                }
            }

            if ApplicationState.debug-mode: VerticalLayout {
                spacing: parent.spacing;
                alignment: parent.alignment;

                DecorationBar { }

                HorizontalLayout {
                    alignment: parent.alignment;

                    SettingBar {
                        label: "Debug Highlights";
                        has-focus: debug-highlights-i-element.has-focus;
                        debug-highlights-i-element := ToggleBox {
                            var: DebugSettings.debug-highlights;
                            toggled(val) => DebugSettings.update-debug-highlights(val);
                        }
                    }
                }

                HorizontalLayout {
                    alignment: parent.alignment;

                    SettingBar {
                        label: "Debug Overlay";
                        has-focus: debug-overlay-i-element.has-focus;
                        debug-overlay-i-element := ToggleBox {
                            var: DebugSettings.debug-overlay-enabled;
                            toggled(val) => DebugSettings.update-debug-overlay-enabled(val);
                        }
                    }
                }
            }

            DecorationBar { }

            HorizontalLayout {
                alignment: parent.alignment;

                exit-button := Button {
                    text: "Exit";

                    activated => {
                        ApplicationState.settings-menu-visible = false;
                    }
                }
            }
        }
    }
}
