import { Button } from "std-widgets.slint";

import { DebugMenuWidget, DebugMenuState } from "debug.slint";
import { RoadIndicatorWidget } from "../themes/default/components/road_indicators.slint";
import { ThemeSelectorWidget } from "../themes/themes.slint";
import { ApplicationState } from "../application/application_state.slint";
import { NavigationMap } from "navmap.slint";
import { CanDisplayWidget } from "can_display.slint";


global WidgetContainerState {
    in property <duration> page-animation-duration: 150ms;

    in-out property <int> current-page: 0;
    in property <int> num-pages: 0;

    function change-page(to-page: int) {
        current-page = to-page;
    }
}

component Widget {
    out property <int> page-number;

    init => {
        self.page-number = WidgetContainerState.num-pages;
        WidgetContainerState.num-pages += 1;
    }

    height: 100%;
    width: 100%;

    @children
}

export component WidgetContainer inherits Rectangle {
    init => {
        WidgetContainerState.num-pages = 0;
    }

    FocusScope {
        key-pressed(event) => {
            if ((event.text == Key.UpArrow) && (WidgetContainerState.current-page < (WidgetContainerState.num-pages - 1))) {
                WidgetContainerState.current-page += 1;
            } else if ((event.text == Key.DownArrow) && (WidgetContainerState.current-page > 0)) {
                WidgetContainerState.current-page -= 1;
            }
            accept
        }
    }

    out property <length> buffer: 2.5px;

    background: transparent;

    center-widget-container-indicator := Rectangle {
        width: parent.width;
        height: parent.height - center-widget-container-inner.height;

        y: 0;

        property <length> indicator-width: self.height;
    }

    center-widget-container-inner := Rectangle {
        width: 80%;
        height: 90%;

        y: parent.height - self.height;
        clip: true;

        center-widget-container-layout := HorizontalLayout {
            spacing: 10px;

            x: -WidgetContainerState.current-page * center-widget-container-inner.width - self.spacing * WidgetContainerState.current-page;
            animate x {
                duration: WidgetContainerState.page-animation-duration;
                easing: ease-in-out;
            }

            road-indicator-widget := Widget {
                RoadIndicatorWidget {
                    height: 100%;
                    width: 100%;
                }
            }

            if ApplicationState.cfg-three-d: threed-container-image := Widget {
                Image {
                    height: 100%;
                    width: 100%;
                }
            }

            if ApplicationState.cfg-network: Widget {
                NavigationMap {
                    height: 100%;
                    width: 100%;
                }
            }

            Widget {
                VerticalLayout {
                    padding: 20px;

                    theme-setting-widget := ThemeSelectorWidget {
                        width: 100%;
                    }

                    Rectangle {
                        Button {
                            width: 100px;
                            height: 25px;
                            x: parent.width / 2 - self.width / 2;

                            text: "Toggle Settings";

                            clicked => {
                                ApplicationState.settings-menu-visible = !ApplicationState.settings-menu-visible;
                            }
                        }
                    }
                }
            }

            Widget {
                CanDisplayWidget {
                    running: WidgetContainerState.current-page == parent.page-number;
                    height: 100%;
                    width: 100%;
                }
            }

            if ApplicationState.debug-mode: Widget {
                DebugMenuWidget {
                    height: 100%;
                    width: 100%;
                }
            }
        }
    }
}
