import { SFDataParameter, SIDataParameter } from "@data/data_parameter.slint";
import { SymbolLight } from "../../default/theme_main.slint";
import { SymbolProperties } from "../../default/symbol_properties.slint";


export component PillGauge {
    in property <SFDataParameter> data_parameter;
    private property <float> radius: min(self.height / 2px, self.width / 2px);
    in property <float> progress: data_parameter.value / data_parameter.max;
    in property <float> line-thickness: 2;
    in property <float> bar-padding: 2;

    outline := Path {
        fill: white;
        viewbox-height: root.height / 1px;
        viewbox-width: root.width / 1px;

        MoveTo {
            x: radius;
            y: 0;
        }

        ArcTo {
            radius-x: 1;
            radius-y: 1;
            x: radius;
            y: radius * 2;
        }

        LineTo {
            x: radius;
            y: radius * 2 - line-thickness;
        }

        ArcTo {
            radius-x: 1;
            radius-y: 1;
            sweep: true;
            x: radius;
            y: line-thickness;
        }

        LineTo {
            x: root.width / 1px - radius;
            y: line-thickness;
        }

        ArcTo {
            radius-x: 1;
            radius-y: 1;
            sweep: true;
            x: root.width / 1px - radius;
            y: radius * 2 - line-thickness;
        }

        LineTo {
            x: radius;
            y: radius * 2 - line-thickness;
        }

        LineTo {
            x: radius;
            y: radius * 2;
        }

        LineTo {
            x: root.width / 1px - radius;
            y: radius * 2;
        }

        ArcTo {
            radius-x: 1;
            radius-y: 1;
            x: root.width / 1px - radius;
            y: 0;
        }
    }

    Rectangle {
        background: transparent;
        clip: true;
        x: (line-thickness) * 0.5px;
        height: root.height - (line-thickness + bar-padding) * 2px;
        property <length> max-bar-width: root.width - (line-thickness) * 0.5px;

        width: max-bar-width * root.progress;

        Path {
            height: parent.height;
            width: root.width;

            x: -parent.x;
            y: 0;

            fill: white;

            viewbox-height: self.height / 1px;
            viewbox-width: self.width / 1px;

            MoveTo {
                x: radius;
                y: 0;
            }

            ArcTo {
                radius-x: 1;
                radius-y: 1;

                x: radius;
                y: parent.viewbox-height;
            }

            LineTo {
                x: parent.viewbox-width - radius;
                y: parent.viewbox-height;
            }

            ArcTo {
                radius-x: 1;
                radius-y: 1;

                x: parent.viewbox-width - radius;
                y: 0;
            }
        }
    }

    @children
}

export enum SideAlignment {
    right,
    left
}

export component PillGaugeContainer inherits Rectangle {
    in property <image> image <=> symbol.source;
    in property <float> image-scale <=> symbol.scale;
    in property <SFDataParameter> data_parameter <=> gauge.data_parameter;
    in property <SideAlignment> symbol-alignment: SideAlignment.right;

    height: 26px;

    symbol := SymbolLight {
        scale: 30%;
        colorize: SymbolProperties.symbol_color_white;

        x: symbol-alignment == SideAlignment.right ? root.width - self.width : 0;
    }

    gauge := PillGauge {
        private property <color> needle-sweep-color:  SymbolProperties.symbol_color_white;

        width: root.width - symbol.width;
        height: 100%;

        x: symbol-alignment == SideAlignment.right ? 0 : root.width - self.width;
    }
}
