import "@fonts/Montserrat/fonts/ttf/Montserrat-Black.ttf";
import "@fonts/Montserrat/fonts/ttf/Montserrat-Bold.ttf";
import "@fonts/Montserrat/fonts/ttf/Montserrat-ExtraLight.ttf";
import "@fonts/Montserrat/fonts/ttf/Montserrat-Light.ttf";
import "@fonts/Montserrat/fonts/ttf/Montserrat-Medium.ttf";
import "@fonts/Montserrat/fonts/ttf/Montserrat-Regular.ttf";
import "@fonts/Montserrat/fonts/ttf/Montserrat-SemiBold.ttf";
import "@fonts/Montserrat/fonts/ttf/Montserrat-Thin.ttf";

import { WidgetContainer } from "@widgets/widget_container.slint";

export component DebugTheme inherits Rectangle {
    background: transparent;
    height: 100%;
    width: 100%;

    WidgetContainer {
        height: 100%;
        width: 100%;
    }
}
