import { Button, VerticalBox } from "std-widgets.slint";
import { GaugeCircle } from "components/instrument_gauge.slint";
import { DataParameter } from "core/car_data.slint";

export component AppWindow inherits Window {
    in property <DataParameter> engine_rpm: { min_value: 0, max_value: 1, value: 0 };

    height: 720px;
    width: 1920px;

    background: black;

    title: "WRX Digital Instrument Cluster";

    EngineRPMGauge := GaugeCircle {
        width: 625px;
        height: self.width;
        x: 50px;
        y: root.height / 2 - self.height / 2;
        // inner-radius: 25%;
        // brush: #7b4e4e;
        // progress: engine_rpm.value / (engine_rpm.max_value - engine_rpm.min_value);
    }

    VehicleSpeedGauge := GaugeCircle {
        width: 625px;
        height: self.width;
        x: root.width - self.width - EngineRPMGauge.x;
        y: root.height / 2 - self.height / 2;
        // inner-radius: 25%;
        // brush: #7b4e4e;
        // progress: engine_rpm.value / (engine_rpm.max_value - engine_rpm.min_value);
    }
}
