import { Button, VerticalBox } from "std-widgets.slint";
import { IDataParameter, FDataParameter, MTGearParameter, SUnits } from "core/car_data.slint";
import { InstrumentGauge, GaugeArc } from "components/instrument_gauge.slint";

export global CarData {
    in property <IDataParameter> engine_rpm: { min_value: 0, max_value: 1, value: 0 };

    in property <MTGearParameter> mt_gear: { value: 0, display: "GEAR" };

    in property <FDataParameter> odometer: { min_value: 0, max_value: 1, value: 0 };
    in property <FDataParameter> vehicle_speed: { min_value: 0, max_value: 1, value: 0 };

    in property <bool> lowbeams_enabled: true;
    in property <bool> right_turn_signal_enabled: true;
    in property <bool> left_turn_signal_enabled: true;

    in-out property <SUnits> units: SUnits.USCS;
}

export global SymbolColors {
    out property <color> symbol_color_blue: #0000ff;
    out property <color> symbol_color_dark_grey: #4b4b4b;
    out property <color> symbol_color_green: #00e600;
    out property <color> symbol_color_grey: #7d7d7d;
    out property <color> symbol_color_red: #ff0000;
    out property <color> symbol_color_white: #ffffff;
    out property <color> symbol_color_yellow: #ffb300;
}

export component AppWindow inherits Window {

    title: "WRX Digital Instrument Cluster";

    preferred-height: 720px;
    preferred-width: 1920px;

    background: black;

    property <length> icon_size: 75px;

    Text {
        x: 0;
        y: 0;

        text: CarData.units == SUnits.USCS ? "USCS" : "SI";
        color: white;
    }

    EngineRPMGauge := InstrumentGauge {
        width: self.height;
        height: root.height * 80%;
        x: root.width * 5%;
        y: root.height / 2 - self.height / 2;
        range: 75%;
        start: -50% + 25% / 2;

        inner_radius: self.width / 2px - 75;
        background_inner_radius: self.width / 2px + 1;

        progress: CarData.engine_rpm.value / (CarData.engine_rpm.max-value - CarData.engine_rpm.min-value);

        property <int> ticks: 8;
        property <int> minor_ticks: 3;
        property <color> tick_color: #ffffff;
        property <float> tick_size: 0.175%;
        property <float> tick_step: self.range / self.ticks;
        property <float> minor_tick_step: tick_step / (self.minor_ticks + 1);

        for tick in ticks: Rectangle {
            property <int> display_tick: tick + 1;
            property <float> start: parent.start - display_tick * parent.tick_step;
            property <length> real_radius: parent.inner_radius * 1px + 35px - rpm-tick-label.font-size;

            width: parent.width;
            height: parent.height;

            rpm-tick-line := GaugeArc {
                viewbox-width: parent.width / 1px;
                viewbox-height: parent.height / 1px;

                fill: EngineRPMGauge.tick_color;
                inner_radius: EngineRPMGauge.inner_radius + 35;
                progress: EngineRPMGauge.tick_size;
                start: parent.start - 0.25 + (75% / EngineRPMGauge.ticks);
                range: 75%;
            }

            rpm-tick-label := Text {
                text: display_tick;
                color: white;
                font-size: 20px;
                x: parent.width / 2 + real_radius * cos(-parent.start * 360deg) - self.width / 2;
                y: parent.height / 2 + real_radius * sin(-parent.start * 360deg) - self.height / 2;
            }

            for minor_tick in minor_ticks: Rectangle {
                property <float> start: parent.start - (minor_tick + 1) * EngineRPMGauge.minor_tick_step;
                width: parent.width;
                height: parent.height;

                rpm-minor-tick-line := GaugeArc {
                    viewbox-width: parent.width / 1px;
                    viewbox-height: parent.height / 1px;

                    fill: EngineRPMGauge.tick_color;
                    inner_radius: (minor-tick + 1) == (EngineRPMGauge.minor_ticks + 1) / 2 ? EngineRPMGauge.inner_radius + 52 : EngineRPMGauge.inner_radius + 60;
                    progress: EngineRPMGauge.tick_size;
                    start: parent.start - 0.25 + (EngineRPMGauge.range / EngineRPMGauge.ticks);
                    range: 75%;
                }
            }
        }

        GaugeArc {
            viewbox-width: parent.width / 1px;
            viewbox-height: parent.height / 1px;

            fill: EngineRPMGauge.tick_color;
            inner_radius: EngineRPMGauge.inner_radius + 40;
            progress: EngineRPMGauge.tick_size;
            start: parent.start;
            range: 75%;
        }

        MTGearLabel := Text {
            text: CarData.mt_gear.display;
            color: white;
            font-size: 50px;
        }
    }

    VehicleSpeedGauge := InstrumentGauge {
        width: self.height;
        height: root.height * 80%;
        x: root.width - self.width - root.width * 5%;
        y: root.height / 2 - self.height / 2;
        range: 75%;
        start: -50% + 25% / 2;

        inner_radius: self.width / 2px - 75;
        background_inner_radius: self.width / 2px + 1;

        progress: CarData.vehicle_speed.value / (CarData.vehicle_speed.max-value - CarData.vehicle_speed.min-value);

        property <int> ticks: 18;
        property <int> minor_ticks: 1;
        property <color> tick_color: #ffffff;
        property <float> tick_size: 0.175%;
        property <float> tick_step: self.range / self.ticks;
        property <float> minor_tick_step: tick_step / (self.minor_ticks + 1);

        for tick in ticks: Rectangle {
            property <int> display_tick: tick + 1;
            property <float> start: parent.start - display_tick * parent.tick_step;
            property <length> real_radius: parent.inner_radius * 1px + 35px - speed-tick-label.font-size;

            width: parent.width;
            height: parent.height;

            speed-tick-line := GaugeArc {
                viewbox-width: parent.width / 1px;
                viewbox-height: parent.height / 1px;

                fill: VehicleSpeedGauge.tick_color;
                inner_radius: VehicleSpeedGauge.inner_radius + 35;
                progress: VehicleSpeedGauge.tick_size;
                start: parent.start - 0.25 + (75% / VehicleSpeedGauge.ticks);
                range: 75%;
            }

            speed-tick-label := Text {
                text: display_tick * 10;
                color: white;
                font-size: 15px;
                x: parent.width / 2 + real_radius * cos(-parent.start * 360deg) - self.width / 2;
                y: parent.height / 2 + real_radius * sin(-parent.start * 360deg) - self.height / 2;
            }

            for minor_tick in minor_ticks: Rectangle {
                property <float> start: parent.start - (minor_tick + 1) * VehicleSpeedGauge.minor_tick_step;
                width: parent.width;
                height: parent.height;

                speed-minor-tick-line := GaugeArc {
                    viewbox-width: parent.width / 1px;
                    viewbox-height: parent.height / 1px;

                    fill: VehicleSpeedGauge.tick_color;
                    inner_radius: (minor-tick + 1) == (VehicleSpeedGauge.minor_ticks + 1) / 2 ? VehicleSpeedGauge.inner_radius + 52 : VehicleSpeedGauge.inner_radius + 60;
                    progress: VehicleSpeedGauge.tick_size;
                    start: parent.start - 0.25 + (VehicleSpeedGauge.range / VehicleSpeedGauge.ticks);
                    range: 75%;
                }
            }
        }

        GaugeArc {
            viewbox-width: parent.width / 1px;
            viewbox-height: parent.height / 1px;

            fill: VehicleSpeedGauge.tick_color;
            inner_radius: VehicleSpeedGauge.inner_radius + 40;
            progress: VehicleSpeedGauge.tick_size;
            start: parent.start;
            range: 75%;
        }

        VehicleSpeedLabel := Text {
            text: round(CarData.vehicle_speed.value);
            color: white;
            font-size: 45px;

            vertical-alignment: TextVerticalAlignment.center;
            horizontal-alignment: TextHorizontalAlignment.center;
        }

        ParkingBrakeWarning := Image {
            height: icon_size * 1.3;
            width <=> self.height;

            y: parent.height - self.height - 125px;

            source: @image-url("../resources/images/brake-warning-indicator-light-letters-only.png");
            colorize: SymbolColors.symbol_color_red;

            visible: CarData.right_turn_signal_enabled;
        }
    }

    HeadlightIndicatorLight := Image {
        height: icon_size;
        width <=> self.height;

        source: @image-url("../resources/images/headlight-indicator-light.png");
        colorize: SymbolColors.symbol_color_green;

        visible: CarData.lowbeams_enabled;
    }

    RightTurnSignal := Image {
        height: icon_size * 0.9;
        width <=> self.height;

        x: VehicleSpeedGauge.x - self.width + 50px;
        y: VehicleSpeedGauge.y;

        source: @image-url("../resources/images/turn-signal-arrow.png");
        colorize: SymbolColors.symbol_color_green;

        visible: CarData.right_turn_signal_enabled;
    }

    LeftTurnSignal := Image {
        height <=> RightTurnSignal.height;
        width <=> RightTurnSignal.width;

        x: EngineRPMGauge.x + EngineRPMGauge.width - 50px;
        y: EngineRPMGauge.y;

        image-fit: ImageFit.contain;
        source: @image-url("../resources/images/turn-signal-arrow.png");
        colorize: SymbolColors.symbol_color_green;

        visible: CarData.left_turn_signal_enabled;
        rotation-angle: 180deg;
    }

    OdometerText := Text {
        color: white;
        text: CarData.odometer.value;
        font-size: 35px;
        x: root.width / 2 - self.width / 2;
        y: root.height - self.height - 20px;
    }
}
