import { Button, VerticalBox } from "std-widgets.slint";
import { InstrumentGauge, GaugeArc } from "components/instrument_gauge.slint";

import "../resources/fonts/Montserrat/fonts/ttf/Montserrat-Black.ttf";
import "../resources/fonts/Montserrat/fonts/ttf/Montserrat-Bold.ttf";
import "../resources/fonts/Montserrat/fonts/ttf/Montserrat-ExtraLight.ttf";
import "../resources/fonts/Montserrat/fonts/ttf/Montserrat-Light.ttf";
import "../resources/fonts/Montserrat/fonts/ttf/Montserrat-Medium.ttf";
import "../resources/fonts/Montserrat/fonts/ttf/Montserrat-Regular.ttf";
import "../resources/fonts/Montserrat/fonts/ttf/Montserrat-SemiBold.ttf";
import "../resources/fonts/Montserrat/fonts/ttf/Montserrat-Thin.ttf";

export global SymbolColors {
    out property <color> symbol_color_blue: #0000ff;
    out property <color> symbol_color_dark_grey: #4b4b4b;
    out property <color> symbol_color_green: #00e600;
    out property <color> symbol_color_grey: #7d7d7d;
    out property <color> symbol_color_red: #ff0000;
    out property <color> symbol_color_white: #ffffff;
    out property <color> symbol_color_yellow: #ffb300;
}

component PrimarySection inherits Rectangle {
    background: transparent;
}

export component AppWindow inherits Window {
    in property <int> engine_rpm;
    in property <string> mt_gear;
    in property <float> vehicle_speed;
    in property <float> odometer;
    in property <bool> lowbeams_enabled;
    in property <bool> right_turn_signal_enabled;
    in property <bool> left_turn_signal_enabled;
    in property <bool> handbrake_sw;

    property <length> icon_size: 75px;

    default-font-family: "Montserrat";
    default-font-weight: 400;

    title: "WRX Digital Instrument Cluster";

    preferred-height: 720px;
    preferred-width: 1920px;

    background: black;

    VerticalLayout {
        top_span := PrimarySection {
            background: Colors.cadetblue;
            height: max(40px, root.height * 1 / 20);
        }

        HorizontalLayout {
            left_tri := PrimarySection {
                background: Colors.aquamarine;
                width: parent.width * 38%;

                EngineRPMGauge := InstrumentGauge {
                    width: self.height;
                    height: min(parent.height, parent.width * 70%);
                    range: 75%;
                    start: -50% + 25% / 2;

                    inner_radius: self.width / 2px - self.width / 6px;
                    background_inner_radius: self.width / 2px - 2;

                    progress: engine_rpm / 8191;

                    property <int> ticks: 8;
                    property <int> minor_ticks: 3;
                    property <color> tick_color: #ffffff;
                    property <float> tick_size: 0.175%;
                    property <float> tick_step: self.range / self.ticks;
                    property <float> minor_tick_step: tick_step / (self.minor_ticks + 1);

                    for tick in ticks: Rectangle {
                        property <int> display_tick: tick + 1;
                        property <float> start: parent.start - display_tick * parent.tick_step;
                        property <length> real_radius: parent.inner_radius * 1px + 35px - rpm-tick-label.font-size;

                        width: parent.width;
                        height: parent.height;

                        rpm-tick-line := GaugeArc {
                            viewbox-width: parent.width / 1px;
                            viewbox-height: parent.height / 1px;

                            fill: EngineRPMGauge.tick_color;
                            inner_radius: EngineRPMGauge.inner_radius + EngineRPMGauge.width / 15px;
                            progress: EngineRPMGauge.tick_size;
                            start: parent.start - 0.25 + (75% / EngineRPMGauge.ticks);
                            range: 75%;
                        }

                        rpm-tick-label := Text {
                            text: display_tick;
                            color: white;
                            font-size: 25px;
                            x: parent.width / 2 + real_radius * cos(-parent.start * 360deg) - self.width / 2;
                            y: parent.height / 2 + real_radius * sin(-parent.start * 360deg) - self.height / 2;
                        }

                        for minor_tick in minor_ticks: Rectangle {
                            property <float> start: parent.start - (minor_tick + 1) * EngineRPMGauge.minor_tick_step;
                            width: parent.width;
                            height: parent.height;

                            rpm-minor-tick-line := GaugeArc {
                                viewbox-width: parent.width / 1px;
                                viewbox-height: parent.height / 1px;

                                fill: EngineRPMGauge.tick_color;
                                inner_radius: EngineRPMGauge.inner_radius + EngineRPMGauge.width / ((minor-tick + 1) == (EngineRPMGauge.minor_ticks + 1) / 2 ? 8px : 9.5px);
                                progress: EngineRPMGauge.tick_size;
                                start: parent.start - 0.25 + (EngineRPMGauge.range / EngineRPMGauge.ticks);
                                range: 75%;
                            }
                        }
                    }

                    GaugeArc {
                        viewbox-width: parent.width / 1px;
                        viewbox-height: parent.height / 1px;

                        fill: EngineRPMGauge.tick_color;
                        fill-rule: FillRule.nonzero;
                        inner-radius: 50;
                        progress: EngineRPMGauge.tick_size;
                        start: parent.start;
                        range: 75%;
                    }

                    MTGearLabel := Text {
                        text: mt_gear;
                        color: white;
                        font-size: 50px;
                    }
                }
            }

            mid_tri := PrimarySection {
                background: Colors.powderblue;
            }

            right_tri := PrimarySection {
                background: Colors.blueviolet;
                width: left-tri.width;

                VehicleSpeedGauge := InstrumentGauge {
                    width: self.height;
                    height: EngineRPMGauge.height;
                    // x: parent.width - parent.width - root.width * 5%;
                    // y: parent.height / 2 - self.height / 2;
                    range: 75%;
                    start: -50% + 25% / 2;

                    inner_radius: EngineRPMGauge.inner_radius;
                    background_inner_radius: EngineRPMGauge.background_inner_radius;

                    progress: vehicle_speed / 290;

                    property <int> ticks: 18;
                    property <int> minor_ticks: 1;
                    property <color> tick_color: #ffffff;
                    property <float> tick_size: 0.175%;
                    property <float> tick_step: self.range / self.ticks;
                    property <float> minor_tick_step: tick_step / (self.minor_ticks + 1);

                    for tick in ticks: Rectangle {
                        property <int> display_tick: tick + 1;
                        property <float> start: parent.start - display_tick * parent.tick_step;
                        property <length> real_radius: parent.inner_radius * 1px + 35px - speed-tick-label.font-size;

                        width: parent.width;
                        height: parent.height;

                        speed-tick-line := GaugeArc {
                            viewbox-width: parent.width / 1px;
                            viewbox-height: parent.height / 1px;

                            fill: VehicleSpeedGauge.tick_color;
                            inner_radius: VehicleSpeedGauge.inner_radius + 35;
                            progress: VehicleSpeedGauge.tick_size;
                            start: parent.start - 0.25 + (75% / VehicleSpeedGauge.ticks);
                            range: 75%;
                        }

                        speed-tick-label := Text {
                            text: display_tick * 10;
                            color: white;
                            font-size: 15px;
                            x: parent.width / 2 + real_radius * cos(-parent.start * 360deg) - self.width / 2;
                            y: parent.height / 2 + real_radius * sin(-parent.start * 360deg) - self.height / 2;
                        }

                        for minor_tick in minor_ticks: Rectangle {
                            property <float> start: parent.start - (minor_tick + 1) * VehicleSpeedGauge.minor_tick_step;
                            width: parent.width;
                            height: parent.height;

                            speed-minor-tick-line := GaugeArc {
                                viewbox-width: parent.width / 1px;
                                viewbox-height: parent.height / 1px;

                                fill: VehicleSpeedGauge.tick_color;
                                inner_radius: VehicleSpeedGauge.inner_radius + VehicleSpeedGauge.width / ((minor-tick + 1) == (VehicleSpeedGauge.minor_ticks + 1) / 2 ? 7.5px : 9px);
                                progress: VehicleSpeedGauge.tick_size;
                                start: parent.start - 0.25 + (VehicleSpeedGauge.range / VehicleSpeedGauge.ticks);
                                range: 75%;
                            }
                        }
                    }

                    GaugeArc {
                        viewbox-width: parent.width / 1px;
                        viewbox-height: parent.height / 1px;

                        fill: VehicleSpeedGauge.tick_color;
                        inner_radius: VehicleSpeedGauge.inner_radius + 40;
                        progress: VehicleSpeedGauge.tick_size;
                        start: parent.start;
                        range: 75%;
                    }

                    VehicleSpeedLabel := Text {
                        text: round(vehicle_speed);
                        color: white;
                        font-size: 45px;

                        vertical-alignment: TextVerticalAlignment.center;
                        horizontal-alignment: TextHorizontalAlignment.center;
                    }

                    ParkingBrakeWarning := Image {
                        height: icon_size * 1.1;
                        width: icon_size;

                        y: parent.height - self.height - 90px;

                        source: @image-url("../resources/images/brake-warning-indicator-light-letters-only.png");
                        colorize: SymbolColors.symbol_color_red;

                        visible: handbrake_sw;
                    }
                }
            }
        }

        bottom_span := PrimarySection {
            background: Colors.purple;
            height: top_span.height;
        }
    }





    // HeadlightIndicatorLight := Image {
    //     height: icon_size;
    //     width <=> self.height;

    //     source: @image-url("../resources/images/headlight-indicator-light.png");
    //     colorize: SymbolColors.symbol_color_green;

    //     visible: lowbeams_enabled;
    // }

    // RightTurnSignal := Image {
    //     height: icon_size * 0.9;
    //     width <=> self.height;

    //     x: VehicleSpeedGauge.x - self.width + 50px;
    //     y: VehicleSpeedGauge.y + 20px;

    //     source: @image-url("../resources/images/turn-signal-arrow.png");
    //     colorize: SymbolColors.symbol_color_green;

    //     visible: right_turn_signal_enabled;
    // }

    // LeftTurnSignal := Image {
    //     height <=> RightTurnSignal.height;
    //     width <=> RightTurnSignal.width;

    //     x: EngineRPMGauge.x + EngineRPMGauge.width - 50px;
    //     y: RightTurnSignal.y;

    //     image-fit: ImageFit.contain;
    //     source: @image-url("../resources/images/turn-signal-arrow.png");
    //     colorize: SymbolColors.symbol_color_green;

    //     visible: left_turn_signal_enabled;
    //     rotation-angle: 180deg;
    // }

    // OdometerText := Text {
    //     color: white;
    //     text: odometer;
    //     font-size: 35px;
    //     x: root.width / 2 - self.width / 2;
    //     y: root.height - self.height - 20px;
    // }
}
