import {
    ControlledFocusScope,
    FocusDomain,
    FocusHoverRect,
    AnimatedFocusHoverRect,
    ComboBoxSelectionBox,
    ComboBoxState,
    SliderSelectionBox,
    SliderState,
} from "@lib/core.slint";
import {
    DebugMenuWidget,
    DebugMenuState,
    DebugOverlay,
} from "@widgets/debug.slint";
import { SettingsMenu } from "@widgets/settings.slint";
import {
    SFDataParameter,
    SIDataParameter,
    SBDataParameter,
    SStrDataParameter,
} from "@data/data_parameter.slint";
import { SCarData } from "@data/car_data.slint";
import { SUnitSystem } from "@lib/units.slint";
import {
    ApplicationState,
    AccessibilitySettings,
    DebugSettings,
    GeneralSettings,
} from "@lib/state.slint";
import { GlobalThemeData } from "@themes/themes.slint";
import { ThemeLoader } from "@themes/theme_loader_gen.slint";
import { CanDisplay, SCanFrameDisplay } from "@widgets/can_display.slint";
import { WidgetContainerState } from "@widgets/widget_container.slint";

// themes
import { DefaultTheme } from "@themes/default/theme_main.slint";

// default fonts
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Black.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Bold.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-ExtraLight.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Light.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Medium.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Regular.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-SemiBold.ttf";
import "../../resources/fonts/Montserrat/fonts/ttf/Montserrat-Thin.ttf";

import "../../resources/fonts/JetBrainsMono/fonts/ttf/JetBrainsMono-Regular.ttf";

// Export types
export { SFDataParameter, SIDataParameter, SBDataParameter, SStrDataParameter, SUnitSystem, SCanFrameDisplay }
// Export globals
export { SCarData, DebugMenuState, GlobalThemeData, CanDisplay, WidgetContainerState }
export * from "@lib/state.slint";

export component App inherits Window {
    default-font-family: "Montserrat";
    default-font-weight: 400;

    title: "WRX Digital Instrument Cluster";

    preferred-width: 2400px;
    preferred-height: 900px;

    background: black;

    // foreground
    // TODO: revert settings menu to appear as a "floating window"
    if ApplicationState.settings-menu-visible: settings-menu := SettingsMenu { }
    if !ApplicationState.settings-menu-visible: theme-loader := ThemeLoader { }

    // popup layer
        //*

    // popup highest layer
    // TODO: add single component that handles these singleton-popups
    if ComboBoxState.visible: ComboBoxSelectionBox { }
    if SliderState.visible: SliderSelectionBox { }

    // Highest layer
    if AccessibilitySettings.animations-enabled: AnimatedFocusHoverRect { }
    if !AccessibilitySettings.animations-enabled: FocusHoverRect { }

    // debug layer
    if (DebugSettings.debug-mode && DebugSettings.debug-overlay-enabled): DebugOverlay { }
}
